### ISSUE TITLE
Mock a struct method within an external library

### ISSUE THREAD

**Issue by seanybaggins** [asomers/mockall#105]
I am trying to mock the `bind` method within `std::net::TcpListener`.

```rust
use std::net::{Ipv4Addr, SocketAddrV4, TcpListener};
use mockall::*;
use cfg_if::cfg_if;

mock! {
    TcpListener {
        pub fn bind<A: ToSocketAddrs + 'static>(addr: A) -> Result<TcpListener>;
    }
}

cfg_if! {
    if #[cfg(test)] {
        use MockTcpListener as TcpListener;
    }
}

// This function is not finished yet
pub(self) fn establish_connection(address: Ipv4Addr, port: u16) {
    let socket = SocketAddrV4::new(address, port);
    let tcp_listener = TcpListener::bind(socket); // invocation of the method I am trying to mock
}

#[cfg(test)]
mod tests;
```

But this gives me errors from the compiler.

```txt
error: unexpected end of input, Unsupported in this context
  --> src/network/mod.rs:9:1
   |
9  | / mock! {
10 | |     TcpListener {
11 | |         pub fn bind<A: ToSocketAddrs + 'static>(addr: A) -> Result<TcpListener>;
12 | |     }
13 | | }
   | |_^

error[E0432]: unresolved import `MockTcpListener`
  --> src/network/mod.rs:17:13
   |
17 |         use MockTcpListener as TcpListener;
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `MockTcpListener` external crate


error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `rust_code`.
```

Any suggestions/examples to mock a struct that is defined in an external library?

**Comment by asomers** [comment]
To get a better error message, you can enable the `nightly` feature of Mockall.  You'll have to use a nightly compiler, of course.

**Comment by seanybaggins** [comment]
Trying to get the macro backtrace using the following

```
rustup run nightly cargo -Z macro-backtrace test
```

but am getting the following

```txt
error: unknown `-Z` flag specified: macro-backtrace
```

any field you see I am entering improperly?

**Comment by asomers** [comment]
Don't bother with that.  Just activate the `nightly` feature in your `Cargo.toml` like so:
```toml
mockall = { version = "0.6.0", features = ["nightly"] }
```
Then build and test as normal.

**Comment by seanybaggins** [comment]
Okay I think I am a little closer. Here is the code now as it stands.

```rust
use std::net::{Ipv4Addr, SocketAddrV4};
use cfg_if::cfg_if;

cfg_if! {
    
    if #[cfg(test)] {

        use mockall::*;
        use std::io::Result;
        use std::net::ToSocketAddrs;

        mock! {
            pub TcpListener {
                fn bind<A: ToSocketAddrs + 'static>(addr: A) -> Result<TcpListener>;
            }
        }

        use MockTcpListener as TcpListener;
    }

    else {
        use std::net::TcpListener;
    }
}

// This function is not finished yet
pub(self) fn establish_connection(address: Ipv4Addr, port: u16) {
    let socket = SocketAddrV4::new(address, port);
    let tcp_listener = TcpListener::bind(socket); // invocation of the method I am trying to mock
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn establish_connection() {
        let mock_tcp_listener = MockTcpListener::new();
        mock_tcp_listener.expect_bind();
    }
}
```

The only problem is now is `expect_bind` does not appear to be a method of `MockTcpListener`.
Even though I made the `TcpListener` public (as suggested in Issue #83 ) within the macro definition.

```txt
error[E0599]: no method named `expect_bind` found for type `network::MockTcpListener` in the current scope
  --> src/network/mod.rs:42:27
   |
16 |         }
   |         - method `expect_bind` not found for this
...
42 |         mock_tcp_listener.expect_bind();
   |                           ^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `rust_code`.
```

**Comment by asomers** [comment]
That's because `bind` isn't an instance method of `TcpListener`.  It's a static method, because it has no `self` argument.  You need to invoke it like `MockTcpListener::bind`, not `MockTcpListener::new().bind`.

**Comment by seanybaggins** [comment]
Thanks for the help @asomers . I managed to get the unit tests to work. Super impressed with the functionality of the library you have written. Here is the code if anyone is interested.

```rust
use std::net::{Ipv4Addr, SocketAddrV4, SocketAddr};
use std::io;
use cfg_if::cfg_if;

cfg_if! {

    if #[cfg(test)] {

        use mockall::*;
        use std::io::Result;
        use std::net::ToSocketAddrs;

        mock! {
            pub TcpStream {}
        }

        use MockTcpStream as TcpStream;

        mock! {
            pub TcpListener {
                fn bind<A: ToSocketAddrs + 'static>(addr: A) -> Result<TcpListener>;
                fn set_nonblocking(&self, nonblocking: bool) -> Result<()>;
                fn accept(&self) -> Result<(TcpStream, SocketAddr)>;
            }
        }

        use MockTcpListener as TcpListener;
    }

    else {
        use std::net::{TcpListener, TcpStream};
    }
}

const GUIDANCE_IP: Ipv4Addr = Ipv4Addr::new(192, 168, 1, 1);
const CONTROL_PORT: u16 = 31401;

// This function is not finished yet
pub(self) fn establish_connection(address: Ipv4Addr, port: u16) -> io::Result<(TcpStream, SocketAddr)> {
    let socket = SocketAddrV4::new(address, port);
    let tcp_listener = match TcpListener::bind(socket) {
        Ok(tcp_listener) => tcp_listener,
        Err(error) => panic!("unable to bind {:?}", error)
        // TODO: Send message to UI
    };

    match tcp_listener.set_nonblocking(true) {
        Ok(_) => (),
        Err(error) => unimplemented!() // TODO: Send message to UI we were not able to set nonblocking
    }

    tcp_listener.accept()
    
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::net::IpAddr;

    #[test]
    #[should_panic]
    fn establish_connection_unable_to_bind() {

        let mock_bind = MockTcpListener::bind_context();
        mock_bind.expect()
            // The error returned is arbitrary. Just want to make sure that if there is an error,
            // we notify the UI and Panic
            .returning(|_: SocketAddrV4| Err(io::Error::last_os_error())); 

        let _ = establish_connection(GUIDANCE_IP, CONTROL_PORT);
    }

    #[test]
    fn establish_connection_able_to_bind_non_blocking() {
        
        let mock_bind = MockTcpListener::bind_context();
        mock_bind.expect()
            // Please ignore the type parameter to the input of returning since it is unused to set the
            // return.
            .returning(|_: SocketAddrV4| {

                let mut mock_tcp_listener = MockTcpListener::new();
                mock_tcp_listener.expect_set_nonblocking()
                    .returning(|_| Ok(()));

                mock_tcp_listener.expect_accept()
                    .returning(|| Ok((
                        MockTcpStream::new(), 
                        SocketAddr::new(IpAddr::V4(GUIDANCE_IP), CONTROL_PORT))
                    )); // Return stating non-blocking was successful

                Ok(mock_tcp_listener)
            });

        assert!(establish_connection(GUIDANCE_IP, CONTROL_PORT).is_ok());
    }
}
```
 I did notice in the documentation for static functions that you mention...

**Mockall can also mock static methods. But be careful! The expectations are global. If you want to use a static method in multiple tests,  you must provide your own synchronization.**

After running my tests a few times with the current code, it is apparent that the mocks are subject to race conditions. Just want to check, does this contradict some of the guarantees of safe rust or is there an underlying unsafe keyword that is allowing this to happen? Lastly, is there a possibility of improving the use of mocked static functions in the future so that race conditions are not possible?

**Comment by asomers** [comment]
Nope and nope.  This isn't technically unsafe Rust.  It's beyond the boundaries of Rust's safety guarantees.  And there's no possibility of the library eliminating these races automatically, because where would the expectations be stored?  Since those methods have no `self` parameter, the expectations must be global.  What you need to do is to provide your own synchronization.  For example, `BAR_MTX`, as used in the following file, does exactly that: https://github.com/asomers/mockall/blob/356f96886ecd87232678d4baaea7df949bdfca08/mockall/tests/mock_struct_with_static_method.rs#L16 .

**Comment by seanybaggins** [comment]
Is it possible for the user of the library to get an error from the compiler if they try to use a static method without synchronization? Perhaps by making the `expect` method on `Context` unsafe? This would likely signal to the user that they need to explicitly opt into the possibility of a race condition by their use of the unsafe keyword.

**Comment by asomers** [comment]
No, `unsafe` has a more specific meaning than that.  It means "this method may violate Rust's safety guarantees", not merely "bugs may result if this method is used incorrectly".  The clue is that setting an expectation on a static method obviously involves changing global variables.  That comes up frequently when writing tests in Rust, and it requires synchronization.

**Comment by seanybaggins** [comment]
I am not sure if I agree with the specific meaning of `unsafe` that has been provided. From the [book](https://doc.rust-lang.org/book/ch19-01-unsafe-rust.html), regarding unsafe functions.

**Calling an Unsafe Function or Method**

**The second type of operation that requires an unsafe block is calls to unsafe functions. Unsafe functions and methods look exactly like regular functions and methods, but they have an extra unsafe before the rest of the definition. The unsafe keyword in this context indicates the function has requirements we need to uphold when we call this function, because Rust can’t guarantee we’ve met these requirements. By calling an unsafe function within an unsafe block, we’re saying that we’ve read this function’s documentation and take responsibility for upholding the function’s contracts.**

I would say that the `expect` method for `Context` has a requirement that it must be synchronized by the person writing the test in order to avoid a race condition.  In addition, it is proven that the `expect` method cannot guarantee that synchronization has been provided, thus, warranting the use of the `unsafe` keyword.

If the `unsafe` keyword is used for the `expect` method for `Context`, I find it less probable that the writer of the tests will mistakenly have a race condition, and If they do, then they have small blocks of code they can inspect to debug the issue.

In either case, `unsafe` keyword or not, race conditions are possible, but with the addition of the `unsafe` keyword, there is an automated check from the compiler that the user has read the documentation of how to use the method correctly.

I feel sometimes when discussing details of implementation, that a sense of appreciation can be lost. I just want to state my appreciation for how responsive you have been on this issue, how respectful and constructive you have been with your feedback, and how well you have written this library. Thank you. `unsafe` keyword or not, I respect your decision. You have clearly demonstrated you are an individual who makes good technical discissions by writing this library.

If you feel harbor any misconceptions of the `unsafe` keyword, please feel free to point me in the direction of some documentation so I may further educate myself.

**Comment by asomers** [comment]
No, this situation does not call for `unsafe`.  Not all race conditions are data races.  For example, if two threads open the same file in append mode and write some text, that's racy.  The file's final state depends on which thread ran first.  Rust's safety model can't protect you from that any more than it can protect you from setting expectations on a static method with Mockall.

I'm going to close this issue for now.  But if you think of a good API that can provide this synchronization automatically, that's backwards-compatible and not prone to lock order reversals, please open an enhancement request.
