### ISSUE TITLE
Improve mocking of static methods and add mocking of plain functions

### ISSUE THREAD

**Issue by Gerschtli** [asomers/mockall#110]
Hey,

during my search for a mocking framework for rust, I came across various libraries with various limitations. For my taste, this crate seems to be the best fit for my use case except the fact that mockall cannot mock functions and the mocks of static methods is not very flexible.

I found https://github.com/CodeSandwich/Mocktopus which allows to mock functions in a pretty low level way, but nonetheless it is possible to mock functions on a per test scope and thread safe.

Maybe someone could have a look in this crate to check if there a concepts used that are compatible with mockall's architecture.

I would love to see this feature integrated in mockall and I think it should be possible to achieve this.

If I get the time and maybe someone could give me some pointers, I would love to help implementing this.

**Comment by asomers** [comment]
Yes, I'm familiar with Mocktopus.  It works on a completely different principle, but replacing mocked functions at runtime at the linker level.  Mockall works at compile time.  And did you know that Mockall can mock functions too when `nightly` is enabled?  See
https://docs.rs/mockall/0.6.0/mockall/#modules
You also might want to look at https://asomers.github.io/mock_shootout/ for a detailed comparison of different mocking libraries.

**Comment by Gerschtli** [comment]
Oh thank you! I totally missed that when reading the docs! I will have a deeper look at mockall ;)

**Comment by mknet** [comment]
Is there any example or doc describing how to mock plain functions? I try to build one by myself but it's a bit hard for me.
Thx

**Comment by asomers** [comment]
You need to put the plain functions into a module.  See https://docs.rs/mockall/0.7.1/mockall/#modules .

**Comment by mknet** [comment]
Okay, now I got something. I'm gonna publish it as git repo and link it here in the next couple of days.
Thx anyways, @asomers
