### ISSUE TITLE
Mock concrete structs implementing generic traits

### ISSUE THREAD

**Issue by GabrielMajeri** [asomers/mockall#119]
I'm trying to use `mockall` to mock a [generic API](https://github.com/gfx-rs/gfx/issues/1794). This API consists of a few generic traits.

I've read through the documentation, but it's not clear how to get `mock!` to work in the following situation:

```rust
trait Generic<T: Clone> {
    fn function() -> T;
}

mock! {
    pub SomeStruct {}

    trait Generic<i32> {
        fn function() -> i32;
    }
}
```

Currently, this gives an error (`unexpected type argument`).

The code I hope `mockall` to generate would be something like:

```rust
pub struct MockSomeStruct {}

impl Generic<i32> for SomeStruct {
	fn function() -> i32 { /*...*/ }
}
```

Is this at all possible? If so, what would be the syntax? Apologies if this has been answered before.

**Comment by asomers** [comment]
You've found a case that Mockall can't yet handle: concrete structs implementing generic traits.  Thanks for bringing it to my attention.  Until this is solved, the best workaround I can recommend would be to make the mock struct generic, too, like this:
```rust
trait Generic<T: Clone> {
    fn function() -> T;
}

mock! {
    pub SomeStruct<T: Clone + 'static> {}

    trait Generic<T> {
        fn function() -> T;
    }
}
```

**Comment by asomers** [comment]
Surprisingly, this turns out to be not very hard to support.  After PR #155, that is.  I couldn't have done it before then.  The hardest part will be writing the documentation, and deciding whether to deprecate the old `mock!` syntax.  The new syntax will look like this:
```rust
trait Foo<T: 'static> {
    fn foo(&self, x: T) -> T;
}
mock! {
    Bar {}
    impl Foo<i32> for Bar {
        fn foo(&self, x: i32) -> i32;
    }
}
```

**Comment by asomers** [comment]
Ok, it's merged.  The old syntax is deprecated, and will generate a warning.  Please let me know if you have any trouble with it.
