### ISSUE TITLE
Panic on reference impl trait argument

### ISSUE THREAD

**Issue by GabrielMajeri** [asomers/mockall#120]
After trying the solution suggested in #119, I've ran into another issue. The following example won't work:

```rust
trait Generic<T: Clone> {
    fn function(foo: &impl Eq) -> T;
}

mock! {
    pub SomeStruct<T: Clone + 'static> {}

    trait Generic<T> {
        fn function(foo: &impl Eq) -> T;
    }
}
```

This example will make the proc macro panic with `help: message: deimplify should've already been run on this output type`

**Comment by asomers** [comment]
Mockall doesn't support that syntax for `function`, because it's very uncommon.  Try the equivalent `fn function<E: Eq>(foo: &E) -> T;` instead.

**Comment by asomers** [comment]
Closing with ETIMEOUT.  Feel free to reopen if you still have questions.

**Comment by luca992** [comment]
If this could be reconsidered, impl in a trait argument would be nice... For no other reason than it looks nicer to me.

**Comment by asomers** [comment]
@luca992 it might be possible, but it would be a lot of work. The ROI for this feature is just too low.
