### ISSUE TITLE
FFI mock gives strange error

### ISSUE THREAD

**Issue by AloeareV** [asomers/mockall#126]
When I try to use the example mock_ffi code, I get this error. 
`error: expected one of '<', '=', or 'where', found ';'`
` --> src/content/mock.rs:7:5`
`  |`
`7 |     #[automock(mod mock;)]`
`  |     ^^^^^^^^^^^^^^^^^^^^^^`

`error: aborting due to previous error`

`error: could not compile 'zingo_webextension'.`

Code is 

`  1 #[allow(warnings)]   `                                                           
`  2 pub(crate) mod web_extension { `                                                 
`  3     use js_sys::{Object, Promise};   `                                           
`  4     use mockall::automock;`                                                      
`  5     use wasm_bindgen::JsValue;  `                                                
`  6   `                                                                              
`  7     #[automock(mod mock)]  `                                                     
`  8     extern "C" {    `                                                            
`  9         pub type Runtime;  `                                                     
` 10  `                                                                               
` 11         pub fn send_message(  `                                                  
` 12             this: &Runtime,  `                                                   
` 13             extension_id: Option<&str>,`                                         
` 14             message: &JsValue, `                                                 
` 15             options: Option<&Object>,`                                           
` 16         ) -> Promise; `                                                          
` 17`                                                                                 
` 18         pub fn on_message(this: &Runtime) -> Event;`                             
` 19`                                                                                 
` 20     }`                                                                           
` 21 }`

**Comment by asomers** [comment]
I can't reproduce this.  If you want help, please post a full working example that doesn't depend on any external crates.

**Comment by AloeareV** [comment]
I'll work on that, but I tried `cargo +nightly test` I don't get the error. Am I supposed to need to use nightly?

**Comment by asomers** [comment]
I suspect that this error has nothing to do with Mockall.  Rather, I think that this is the key:
```
error[E0658]: extern types are experimental
  --> mockall/examples/issue_126.rs:16:9
   |
16 |         pub type Runtime;
   |         ^^^^^^^^^^^^^^^^^
   |
   = note: see issue #43467 <https://github.com/rust-lang/rust/issues/43467> for more information
   = help: add `#![feature(extern_types)]` to the crate attributes to enable
```

**Comment by AloeareV** [comment]
Hm. My co-devoloper ran my exact code and didn't get my error, so there's probably something weird with one of our local states. 

Also, you're right that I don't get the error if I don't use extern type. It's weird that the compiler gave me an error pointing at the automock flag and not the extern type, but that's sort of tangential. I'm gonna go ahead and close this, thanks for finding that issue!

**Comment by zancas** [comment]
Hi!   I am on:

```
rustc --version
rustc 1.43.1 (8d69840ab 2020-05-04)

cargo --version
cargo 1.43.0 (2cbe9048e 2020-05-03)
```

@AloeareV was on an older version.
