### ISSUE TITLE
Declarative macro for conditional import of mocks

### ISSUE THREAD

**Issue by joshleeb** [asomers/mockall#128]
I'm still fairly new to using this crate, but one of the things that's been just a bit of an itch of mine is the way that I've been conditionally importing either the mock or the real type at compile time. It usually looks something like...

```rust
cfg_if! {
    if #[cfg(test)] {
        use a::Real;
    } else {
        use a::MockReal as Real;
    }
}
```

Now, there's nothing wrong with this. But personally, it's a little verbose for my taste. So, I've started putting together a declarative macro to bundle it up behind syntax that's a little nicer.

```rust
use_mock!(a::{Real, MockReal});
```

<details>
<summary>Macro Impl (so far)</summary>

```rust
#[macro_export]
macro_rules! use_mock {
    ($start: ident $(:: $mid: ident)* :: {$real: ident, $mock: ident }) => {
        #[cfg(not(test))]
        use $start $(:: $mid)* :: $real;

        #[cfg(test)]
        use $start $(:: $mid)* :: $mock as $real;
    };
}
```
</details>

So far I've been using it along with struct mocking but it also looks like this should work with trait mocking too.

Though before I just put up a PR, I'm keen to get some thoughts on this. Whether it is something that would be useful to add to the crate? And if so, any feedback or suggestions on the macro syntax and impl?

Anyway, great crate! I've been finding it very useful and quite easy to use, especially with `#[automock]` and struct mocking which are both :1st_place_medal: Thanks for all your work!! :100: 

_Update_
Just seen that this is perhaps related to #71.

**Comment by asomers** [comment]
Yeah, this is definitely something that I'd like to have.  It's on the feature list already, as https://github.com/asomers/mockall/issues/71 .  Closing as duplicate.
