### ISSUE TITLE
[question]How mock trait like Add trait?

### ISSUE THREAD

**Issue by Norbytus** [asomers/mockall#135]
```
#[cfg_attr(test, automock)]
pub trait Example<Data=Self> {
    fn insert(&self, input: Data);
}
```

**Comment by asomers** [comment]
What's your problem, exactly?  Is it the associated type that's confusing you?  If so, see https://docs.rs/mockall/0.7.1/mockall/#associated-types-1 .

**Comment by Norbytus** [comment]
It's not confusing. I try did next
```
#[automock(type Input=String;)]
trait Example<Input=Self> {
    fn data(&self, input: Input);
}


 #[cfg(test)]
 mod tests {
     use super::MockExample;

     #[test]
     fn insert() {
         let mut mock = MockExample::new::<String>();
     }
 }
```

And i get error about 'static life time. So i try understand what i did wrong,  and find answer here. My case it's not just simple association

**Comment by asomers** [comment]
Please post the full error you're seeing.  And BTW, you'll get a more helpful error message if you build mockall with the `nightly` feature (as the name suggests, that requires a nightly toolchain).

**Comment by Norbytus** [comment]
```
error[E0310]: the parameter type `Input` may not live long enough
   --> src/storage/mod.rs:114:25
    |
114 |   trait Example<Input=Self> {
    |  _______________-----_____^
    | |               |
    | |               help: consider adding an explicit lifetime bound...: `Input: 'static`
115 | |     fn data(&self, input: Input);
    | |___________^
    |
note: ...so that the type `Input` will meet its required lifetime bounds
   --> src/storage/mod.rs:114:25
    |
114 |   trait Example<Input=Self> {
    |  _________________________^
115 | |     fn data(&self, input: Input);
    | |___________^

error: aborting due to previous error; 2 warnings emitted

For more information about this error, try `rustc --explain E0310`.
```

**Comment by asomers** [comment]
Ok, this isn't that hard.  The `=Self` part is red herring.  That basically doesn't matter.  It only comes into play for trait implementations that don't specify it.  But with Mockall, you must specify it.  And the warning about static lifetimes is de rigueur for Mockall, see https://docs.rs/mockall/0.7.1/mockall/#generic-traits-and-structs .  So your code should look like this:
```rust
#[automock]
trait Example<Input: 'static> {
    fn data(&self, input: Input);
}


 #[cfg(test)]
 mod tests {
     use super::MockExample;

     #[test]
     fn insert() {
         let mut mock = MockExample::<String>::new();
     }
}
```

**Comment by Norbytus** [comment]
Cool, thank. And sorry maybe. It's my mistake. Really thank you

**Comment by asomers** [comment]
Glad to help.  Happy hacking!
