### ISSUE TITLE
Mockall does not support mocking Fn objects

### ISSUE THREAD

**Issue by bgallet** [asomers/mockall#139]
I am running in a mockall limitation I do not know how to handle. I use the fuse_mt crate, In this crate, I need to implement a trait that includes this:
```rust
/// Read from a file.
///
/// Note that it is not an error for this call to request to read past the end of the file, and
/// you should only return data up to the end of the file (i.e. the number of bytes returned
/// will be fewer than requested; possibly even zero). Do not extend the file in this case.
///
/// * `path`: path to the file.
/// * `fh`: file handle returned from the `open` call.
/// * `offset`: offset into the file to start reading.
/// * `size`: number of bytes to read.
/// * `result`: a callback that must be invoked to return the result of the operation: either
///    the result data as a slice, or an error code.
///
/// This function has no return value; call the `result` function instead.
fn read(&self, _req: RequestInfo, path: &Path, fh: u64, offset: u64, size: u32, handler: impl FnOnce(Result<&[u8], libc::c_int>)) {
    debug!("read({:?}, {:?}, {:?})", path, offset, size);
    println!("  read ->{:?}, {:?}, {:?}", path, offset, size);
    if fh == 0 {
        error!("read: missing fh");
        return handler(Err(libc::EINVAL));
    }

    self.fs.read(fh, offset, size, handler);
}
```

I implement this by calling my filesystem with the same handler parameter. As this is a FnOnce, I cannot mock it at all. Is there a way to circumvent this by refactoring the code?

**Comment by asomers** [comment]
What error do you get when you try?

**Comment by bgallet** [comment]
Sorry. I put it in the title: Mockall does not support mocking Fn objects

**Comment by asomers** [comment]
In your bug report, please paste both your actual code snippet and the whole error message.

**Comment by bgallet** [comment]
The exact code is below:

#[automock]
pub trait BlockProvider: Debug + Send + Sync + 'static {
    fn size(&self) -> u64;
    // fn write(&self, offset: u64, payload: &[u8]) -> Result<(usize, usize), BlockStorageError> ;
    fn read(&self, offset: u64, size: u32, handler: impl FnOnce(Result<&[u8], BlockStorageError>));
}

The error is:
error: custom attribute panicked
  --> src/block/block_storage.rs:20:1
   |
20 | #[automock]
   | ^^^^^^^^^^^
   |
   = help: message: Mockall does not support mocking Fn objects.  More information may be available when mockall is built with the "nightly" feature.

error: aborting due to previous error

**Comment by asomers** [comment]
The reason I didn't implement support for for that syntax is because it isn't very common.  But it's equivalent to this:
```rust
type F = Box<dyn FnOnce(Result<&[u8], BlockStorageError>) + 'static>;

#[automock]
pub trait BlockProvider {
    fn size(&self) -> u64;
    fn read(&self, offset: u64, size: u32, handler: F);
}
```
Or, almost equivalent to this:
```rust
#[automock]
pub trait BlockProvider {
    fn size(&self) -> u64;
    fn read<F: FnOnce(Result<&[u8], BlockStorageError>) + 'static>(&self, offset: u64, size: u32, handler: F);
}
```

**Comment by bgallet** [comment]
Well, it works perfectly! Thanks for the help.

**Comment by tvolk131** [comment]
I ran into the same problem and got a bit stuck until I stumbled onto this solution. It'd be nice to see support for Fn objects. But if that's not feasible, could we change the error message to link to this bug? Currently the compiler error doesn't give any suggestions so I initially assumed that what I was trying to do wasn't possible, when it's actually a pretty simple change.

**Comment by asomers** [comment]
I should be possible.  It shouldn't even be too hard.  But I'm sure that I won't have time to do it for at least another month.  I'll tweak the error message in the meantime.

**Comment by tvolk131** [comment]
Awesome, thanks!

**Comment by refaelsh** [comment]
I just wanna also thank you for linking to this issues in the error message, it saved me :-)
