### ISSUE TITLE
Simplify mocking external traits

### ISSUE THREAD

**Issue by unaiur** [asomers/mockall#140]
I would be great to mock DynamoDB trait (which contains tens of methods) without having to enumerate all its methods, with some code like:
```rust
    use mockall::automock;
    use rusoto_dynamodb::DynamoDb;

    #[automock]
    trait DDB: DynamoDb {}
```

Unfortunately, that code doesn't work because mockall does not implement inherited methods from DynamoDb trait.

**Comment by asomers** [comment]
Unfortunately, that's not possible.  Proc Macros have no way to get that information.  Your only options are to use `mock!`, or to convince the DynamoDB crate to export mocks themselves.
