### ISSUE TITLE
mock! gives " error: unexpected end of input, Unsupported in this context"

### ISSUE THREAD

**Issue by arnabcs17b006** [asomers/mockall#143]
Here are attached screenshots for reference.
![1](https://user-images.githubusercontent.com/46973323/84040808-b6911d80-a9c0-11ea-8d9b-3773a3f12591.png)
![2](https://user-images.githubusercontent.com/46973323/84040812-b85ae100-a9c0-11ea-9116-434236818e1a.png)

**Comment by asomers** [comment]
Please enable the "nightly" feature of Mockall and try building again.  You'll get a much better error message.

**Comment by arnabcs17b006** [comment]
![1](https://user-images.githubusercontent.com/46973323/84044818-acbde900-a9c5-11ea-9480-7d251b8f722a.png)
I get the above message

**Comment by asomers** [comment]
That doesn't look like the full error message.  Are you sure you enabled the nightly feature?  Would you mind showing your Cargo.toml?

**Comment by asomers** [comment]
Would you mind posting your code someplace where I can copy/paste it?  Either push your branch to GH, or just copy/paste the `mock!` block into this issue.

**Comment by asomers** [comment]
You need to remove the visibility specifiers from your `mock!`.  Methods in  `mock!` are always written like trait methods, so they can't have visibility specifiers.  Instead, they inherit the visibility specifier of the struct.  Change `pub fn` to merely `fn`.

**Comment by asomers** [comment]
BTW, using `pub fn` in that location actually used to be accepted, so you may see it in old code some places.  A change to the `syn` crate released in version 1.0.15 is why it isn't accepted any longer.
https://github.com/dtolnay/syn/commit/09f2f5c0939e9bcbdbd0f4c95b75d239293049ae
