### ISSUE TITLE
Trying to mock functions having Result<> return type throws error

### ISSUE THREAD

**Issue by arnabcs17b006** [asomers/mockall#145]
On declaring the following function inside mock!,
mock!{
    KVMi
    {
        fn get_registers(&self, vcpu: u16) -> Result<(kvm_regs, kvm_sregs, kvm_msrs), Error>;
    }
}
the following error is shown:
error[E0277]: the size for values of type `(dyn std::error::Error + 'static)` cannot be known at compilation time

**Comment by asomers** [comment]
Are you intending to use `std::error::Error` there, or did you have in mind some concrete type?  If you really meant it, just try changing it to `Error + Sized`.

**Comment by arnabcs17b006** [comment]
On substituting Error with Error + Sized, it throws the following error.
error[E0225]: only auto traits can be used as additional traits in a trait object

**Comment by asomers** [comment]
Closer examination of the error message reveals the real problem.  You have an import error somewhere.  The error message thinks you're trying to return `std::error::Error`.  But the real function returns `std::io::Error`.

**Comment by arnabcs17b006** [comment]
Thanks it worked.
Is there any slack or irc channel for discussing about mockall?

**Comment by arnabcs17b006** [comment]
Also on running tests, i am getting the following messages and it seems to be not stopping. Any ideas??
running 1 test
test driver::kvm::tests::test_read_register ... test driver::kvm::tests::test_read_register has been running for over 60 seconds

**Comment by asomers** [comment]
That hang is almost certainly caused by something in your code, not in Mockall.  The only way you can cause Mockall to hang would involve setting expectations for multiple static methods or bare functions in the same test.

**Comment by arnabcs17b006** [comment]
But i am setting expectation for only a single function. Please find the link to the code below.
https://github.com/arnabcs17b006/libmicrovmi/blob/ornib_summer/src/driver/kvm.rs#L322

**Comment by asomers** [comment]
Yeah, so the hang is probably happening somewhere in `Kvm::read_registers`.  I don't even think your mock function is getting called.  If so, it will probably panic, because you haven't set a return value.

**Comment by arnabcs17b006** [comment]
Can you provide some more help, like why mock function is not getting called and where I went wrong with the code. Actually I am new to rust. 
Thanks

**Comment by asomers** [comment]
The problem doesn't like in Mockall.  It must lie somewhere in the kvmi crate.  You need to debug it just as you would any other problem.

**Comment by arnabcs17b006** [comment]
OK. Thanks
