### ISSUE TITLE
Support &dyn T arguments

### ISSUE THREAD

**Issue by ChrisGreenaway** [asomers/mockall#152]
Whilst we wait for async trait to make it to stable, I'm following the workaround outlined in https://github.com/asomers/mockall/issues/75

But for the following code:
```
#[cfg(test)]
mock! {
    pub MyTrait {
        async fn my_method(&self, value: &dyn MyOtherTrait) -> Result<(), MyError>;
    }
}
```

I get the error:

```
error[E0621]: explicit lifetime required in the type of `value`
mock! {
    pub MyTrait {
        async fn my_method(&self, value: &dyn MyOtherTrait) -> Result<(), MyError>;
                                  ^^^^^ lifetime `'static` required
    }
}
- help: add explicit lifetime `'static` to the type of `value`: `&'static (dyn MyOtherTrait + 'static)`
```

This looks to be due to the generated implementation of the mock - in that ties together the lifetime of value and the returned Result object.

Not sure if this is async specific.

**Comment by asomers** [comment]
In this case the `Result` is already `'static`, so that's not it.  The problem I think is the `&dyn`.  That's an uncommon syntax, so Mockall doesn't support it.  Try this syntax instead:
```rust
async fn my_method(&self, value: &Box<dyn MyOtherTrait>) -> Result<(), MyError>;
```

**Comment by ChrisGreenaway** [comment]
Indeed using `&Box` does fix the problem - it's the workaround I already starting using for now.

However I don't agree that `&dyn` is an uncommon syntax. Indeed clippy complains about `&Box` and says that a normal reference should be used - so I've had to add a clippy ignore. And clippy is quite right - why have an extra Box when a borrow would be fine.

Further, I'm calling into `my_method` with a borrowed object and converting that to a Box involves taking ownership - which I can't do (it's only a borrow) or a copying / cloning type of operation - which isn't something that `MyOtherTrait` provides.

The problem is caused in the implementation of the mock macro somewhere - the compiler is clever enough to look through the implementation to see that the static Result depends on the incoming value parameter and is essentially complaining that the value should be static because the returned Result is static.

**Comment by asomers** [comment]
No, it has nothing to do with the result type.  Try removing the result entirely, and you'll get the same error.  If you really want to know the nitty-gritty details, the error comes from the code that Mockall generates to match arguments.  In order to do something like this:
```rust
let mut my_mock = MockMyTrait::new();
let expected: dyn MyOtherTrait = something_something;
my_mock.expect_my_method()
    .with(eq(expected));
```
`expected` must have `'static` lifetime.  Notice that its type is now `dyn MyOtherTrait`, and a value of that same type gets stored internally to the mock object.

So you can guess why it would take some work for Mockall to support this syntax.  However, the compiler's suggested solution is more restrictive than necessary.  You don't need for the actual reference to be static, just the referenced type.  Try this:
```rust
#[cfg(test)]
mock! {
    pub MyTrait {
        async fn my_method(&self, value: &(dyn MyOtherTrait + 'static)) -> Result<(), MyError>;
    }
}
```

**Comment by ChrisGreenaway** [comment]
I guess I'd leaned too heavily on the example in the E0621 section of https://doc.rust-lang.org/error-index.html where the lifetime of the parameter gets ignored when the return value is created. But reading more carefully, I can see it can just be how the parameters are used in the implementation rather than necessarily the implementation linking parameters to the return value.

I tried putting `&(dyn MyOtherTrait + 'static)` as the parameter type on the method in the `mock!`. The compiler wanted that propagated to the trait and so on, but things seem to fit together OK once I do that. Thanks for the suggestion.

I can't say I 100% understand what that `+ 'static` does. From what I can find, I'm guessing it says that `MyOtherTrait` isn't parameterised with a lifetime or, if it does, then the parameterised lifetime is `'static`.

Is the plan to ultimately implement this syntax (i.e. without the `'static`)?

**Comment by asomers** [comment]
> I guess I'd leaned too heavily on the example in the E0621 section of https://doc.rust-lang.org/error-index.html where the lifetime of the parameter gets ignored when the return value is created. But reading more carefully, I can see it can just be how the parameters are used in the implementation rather than necessarily the implementation linking parameters to the return value.
> 
> I tried putting `&(dyn MyOtherTrait + 'static)` as the parameter type on the method in the `mock!`. The compiler wanted that propagated to the trait and so on, but things seem to fit together OK once I do that. Thanks for the suggestion.
> 
> I can't say I 100% understand what that `+ 'static` does. From what I can find, I'm guessing it says that `MyOtherTrait` isn't parameterised with a lifetime or, if it does, then the parameterised lifetime is `'static`.

Yes

> 
> Is the plan to ultimately implement this syntax (i.e. without the `'static`)?

Yes.  I can do it by special-casing the generation code, to accept an owned `Box<dyn MyOtherTrait>` for the matching functions, while not altering the signature of the mocked method itself.

**Comment by iddm** [comment]
> So the problem isn't as bad as I initially thought. Boxed trait objects have an implicit `'static` lifetime unless otherwise specified, and internal to Mockall is a boxed trait object that is parameterized on your function's argument type. Mockall tries to compare that boxed trait object to your function's argument, but the types are different (`dyn Trait + static` vs `dyn Trait`) 😞 .
> 
> So I can suggest a better workaround: Instead of adding `'static` to your function's signature, add a lifetime parameter. Rustc won't complain about the same `method not compatible with trait` error, and you will have more flexibility in how you call it. Do it like this:
> 
> #[cfg(test)]
> mock! {
>     pub MyTrait {
>         async fn my_method<'a>(&self, value: &(dyn MyOtherTrait + 'a)) -> Result<(), MyError>;
>     }
> }

This seems to work perfectly for my #645 issue as well (using `#[automock]`). I wonder if we could create something like `serde.rs` with `mdbook` to provide a single knowledge base? I am really sorry I couldn't find a solution to this one myself, and thanks for pointing me to it, @asomers !

**Comment by iddm** [comment]
> [@iddm](https://github.com/iddm) I've tried to keep all of the necessary documentation in rustdoc, in the "User Guide" section. I'm not necessarily averse to converting that to mdbook. But would the doctests still cover it? And would that took really organize it better than rustdoc?

I am also not sure of a better way myself. I just wish I could have avoided asking you and spending your and my time and could have simply found this ticket or at least the relevant information :-) I guess this mentioned in the rustdoc is fine as well :-) It mentions the Box, after all :-)
