### ISSUE TITLE
[question] how would you use the `mock!` macro to mock a trait that implements e.g. `FromStr`

### ISSUE THREAD

**Issue by jjmark15** [asomers/mockall#153]
I can see in the [docs](https://docs.rs/mockall/0.7.1/mockall/#associated-types-1) that you can mock a trait with associated types like this with automock, however I want to be able to do something like the following with the `mock!` macro:

```rust
trait ComplexTrait: FromStr {
    fn returns_a_number() -> u8;
}

#[cfg(test)]
mock! {
    pub ComplexTraitImpl {}

    trait ComplexTrait {
        fn returns_a_number() -> u8;
    }

    trait FromStr {
        fn from_str(s: &str) -> Result<Self, Self::Err>;
    }
}
```

Would this be possible?

**Comment by asomers** [comment]
Sure, you can use associated types with `mock!`.  What you want to do sounds a lot like this test case:
https://github.com/asomers/mockall/blob/master/mockall/tests/mock_struct_with_trait_with_associated_types.rs

**Comment by jjmark15** [comment]
Ah brilliant, thank you so much
