### ISSUE TITLE
Question: #[automock] code generation

### ISSUE THREAD

**Issue by andreytkachenko** [asomers/mockall#16]
[fill free to close anytime]
Am I right #[automock]  generates bunch of stuff always (both when testing and when building/running/checking)?
in that case how can I add some `cfg` to prevent code generation (and compilation) when build/run/check?

**Comment by asomers** [comment]
Yep.  If you only want to generate code during your unit tests, you should do this:
```rust
#[cfg_attr(test, automock)]
trait Whatever {}
```

**Comment by ondrowan** [comment]
@asomers Maybe I misunderstand something, but I'm using `#[cfg(test)] use mockall::automock` and `#[cfg_attr(test, automock)]` on trait and my test code says "failed to resolve: could not find `MockTrait` in `module`".

**Comment by asomers** [comment]
@ondrowan you probably have an incorrect it missing use statement, or you're trying to use mockall in an integration test. Crates get built without cfg(test) for integration tests.  I can take a look, if you can show me your code.

**Comment by ondrowan** [comment]
@asomers you're right, I'm trying to use it in integration tests, so I'll have to figure out either how to write those as unit tests or play with feature flags as you've explained in other answers. Thanks for clarification!

**Comment by asomers** [comment]
@ondrowan my personal preference is to only use mock objects in unit tests, but of course you don't have to agree.  Another option for you is to use `mock!` in your integration tests instead of `#[automock]` in your src.

**Comment by bradwood** [comment]
> Yep. If you only want to generate code during your unit tests, you should do this:
> 
> ```rust
> #[cfg_attr(test, automock)]
> trait Whatever {}
> ```

Just to be clear, assuming this is the approach adopted, I must still set the `mockall` as a full, and not dev dependency? Is this correct?  Thanks!

**Comment by asomers** [comment]
> > Yep. If you only want to generate code during your unit tests, you should do this:
> > ```rust
> > #[cfg_attr(test, automock)]
> > trait Whatever {}
> > ```
> 
> Just to be clear, assuming this is the approach adopted, I must still set the `mockall` as a full, and not dev dependency? Is this correct? Thanks!

Not correct.  If that's your desired approach, then mockall only needs to be a dev dependency.

**Comment by bradwood** [comment]
Ok... I'm not getting this... (sorry for being slow). If I do this I get the compiler complaining saying `cannot find attribute `automock` in this scope`. 

I think this is because I've not added:

```
use mockall::*;
use mockall::predicate::*;
```
So, I add these to the top of my file, but, as it's a dev dependency, the compiler then states:

```
failed to resolve: use of undeclared type or module `mockall`
```

What am I doing wrong?

And thank you, in advance, for your help.

**Comment by asomers** [comment]
On Sat, Apr 25, 2020 at 5:39 AM Bradley Wood <notifications@github.com>
wrote:

> Ok... I'm not getting this... (sorry for being slow). If I do this I get
> the compiler complaining saying cannot find attribute automock in this
> scope.
>
> I think this is because I've not added:
>
> use mockall::*;
> use mockall::predicate::*;
>
> So, I add these to the top of my file, but, as it's a dev dependency, the
> compiler then states:
>
> failed to resolve: use of undeclared type or module `mockall`
>
> What am I doing wrong?
>
> And thank you, in advance, for your help.
>

You need to conditionally use mockall, like this:
```rust
#[cfg(test)]
use mockall::{*, predicate::*};
```
