### ISSUE TITLE
[Question] Is it possible to make generated mocks public

### ISSUE THREAD

**Issue by ta32** [asomers/mockall#160]
I have the following project structure 
crate_a **( dep of b )** 
crate_b

crate_a is a path dependency of crate_b
both crates use mockall and crate_a has a trait foo, which has the attribute #[cfg_attr(test, automock)]

Now, i wanted to use the auto_generated mocks for foo, in crate_b.
Currently i can create the mock for foo using "mock!" and this is how you would mock an external trait in a crate you don't control. 

However, all the traits in crate_a that i want visible are in a public trait module and have #[cfg_attr(test, automock)]
is it possible to also make the generated mocks visible to? 

If it's not i guess this would be an enhancement, would something like this be theoretically possible/simple to implement?

**Comment by asomers** [comment]
Yes.  In fact, it's really easy to make the mocks public.  Just change that `#[cfg_attr(test, automock)]` into a`#[automock]`.  That's all there is to it!  HOWEVER, if you do that then the mocks will always be generated, even for production code.  So I recommend you create an off-by-default feature and use that to control the generation of the mocks instead.  For example, in Cargo.toml:
```toml
[features]
mocks = []
```
and in your library:
```rust
#[cfg_attr(mocks, automock]
```

**Comment by ta32** [comment]
wow thanks that was really easy
to enable that feature in my test all i had to do was 
``  #[test]
    #[cfg(feature = "mocks")]
    fn test_something() { }
``
then i could use the mocks from the create_b. I can also label which traits i want mockable by the consumer of my crate. If usage of this crate becomes standard by other third crate developers it will become really easy mock things without any boilerplate code!

**Comment by asomers** [comment]
glad to help
