### ISSUE TITLE
Support DerefMut for mocks

### ISSUE THREAD

**Issue by bradforj287** [asomers/mockall#191]
I ran into a bit of a snag testing code involving a lot of smart pointers. 

I wanted to do something like this:

1) create the mock in an Arc
2) set some expectations on the mock
3) pass a pointer to the mock to the code under test.
4) trigger the code utilizing the mock
5) checkpoint()
6) repeat, go back to step 2

I couldn't accomplish this because this code won't compile:
This code:
```
    let mut mock = Arc::new(MockMyService::new());
    mock.expect_get_current()
        .times(1)
        .returning(|input| {
        input * input
    });

```

fails with a compiler error:
```
error[E0596]: cannot borrow data in an `Arc` as mutable
  --> src/main.rs:50:5
   |
50 |     mock.expect_get_current()
   |     ^^^^ cannot borrow as mutable
   |
   = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `std::sync::Arc<MockMyService>`
```

I'm wondering if it makes sense to support DerefMut to make testing with smart pointers easier?

**Comment by asomers** [comment]
No.  The problem here is that setting expectations requires mutable access to the mock.  But Arc does not provide interior mutability.  What you want is either to use an `Arc<Mutex<MockMyService>>`, or else set the expectations before you Arc it, like this:
```rust
let mut mock = MockMyService::new();
mock.expect_get_current()
        .times(1)
        .returning(|input| {
        input * input
    });
let arcmock = Arc::new(mock);
```

**Comment by bradforj287** [comment]
Yup, setting expectations before mocking is the workaround i went with. There is another workaround involving unsafe code. Example:
```
#![feature(get_mut_unchecked)]
use std::sync::Arc;

fn main() {

    let mut v: Vec<i32> = Vec::new();
    v.push(1);

    println!("data: {:?}", v);
    let a = Arc::new(v);

    unsafe {
        let mut aa = a.clone();
        let mut d = Arc::get_mut_unchecked(&mut aa);
        d.push(55);
    }
    println!("data: {:?}", a);
}
```

**Comment by YarekTyshchenko** [comment]
After some searching I found a solution to this: https://github.com/asomers/mockall/discussions/327#discussioncomment-10693846

**Comment by DerFetzer** [comment]
@YarekTyshchenko Could you please elaborate how this problem would be solved by your linked comment?
Sorry if this is obvious but I can not make sense out of it.

**Comment by YarekTyshchenko** [comment]
@DerFetzer Iirc I could never get it to work with ‘DerefMut’ :( I was hoping that ‘Arc<Mutex<_>>’ would implement ‘DerefMut’ but I don’t think it can generically.
It doesn’t impact me much as all the struts I have don’t need mutability, they hide it internally with mutexes.

Can you distil what you’re stuck on into a playground link I can look at?

**Comment by DerFetzer** [comment]
Thanks for the quick reply!

I do not need mutability inside my regular structs as well, but when using mocks I want to set expectations after wrapping my Api inside an `Arc`.

I tried to summarize what I want to do in the playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=5902909521c934db1d6ebec3792c39f2

The Api is auto-generated but I have control over this process so I can alter the Apis as I like. The published crate is still in alpha state so I needn't think about breaking compatibility.
I experimented a bit with changing the `&dyn` return type to something else but this did not get me very far.

**Comment by YarekTyshchenko** [comment]
Don’t think you’ll be able to set different expectations after wrapping it in the arc. Can you restructure your tests not to need that?

**Comment by DerFetzer** [comment]
Thank you very much. I will keep the idea with the helper functions in mind.
Of course, I can restructure my tests. It would just be nice for the users of my crate to have this functionality.

I could not think of a way to achieve this and then I read your comment with a possible solution. So I got a bit more hopeful, again.😉

**Comment by YarekTyshchenko** [comment]
If you think about it, it doesn’t make sense for mocks to be mutable and sharable without extra steps. If automock did implement some sort of locking for interior mutability, your actual impl of a trait could be pickles’s, so your tests would hang even though real impl would work. there’s just no way for the mock to know what’s the correct behaviour.

As a last thought, this may be a bad idea but nothing stops you from wrapping the mock into a struct (that impl your trait as well) that proxies all the methods to an internally mutexed mock instance (including having a way to change its expectations part way through)
