### ISSUE TITLE
Help with an example of mocking generic arguments

### ISSUE THREAD

**Issue by jjmark15** [asomers/mockall#192]
I have tried following the example in:
https://github.com/asomers/mockall/blob/a7cf2e2f24560c2837935efbb9e6d3f5324c8b3d/mockall/tests/mock_generic_arguments.rs#L7-L17

But have had no luck trying to mock the following:
```rust
use std::path::Path;

pub trait TestTrait {
    fn method<P>(&self, argument: P) -> Result<String, ()>
    where
        P: AsRef<Path>;
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use mockall::*;

    use super::*;

    mock! {
        pub TestTrait {}

        trait TestTrait {

            fn method<P>(&self, argument: P) -> Result<String, ()>
            where
                P: 'static + AsRef<Path>;
        }
    }
}
```

Would it be possible to get a steer on where I am going wrong here?

**Comment by asomers-ax** [comment]
What error did you get?  Also, if you enable the "nightly" feature, you'll get better error messages.

**Comment by jjmark15** [comment]
I get:

```
4  | /     fn method<P>(&self, argument: P) -> Result<String, ()>
5  | |     where
6  | |         P: AsRef<Path>;
   | |_______________________- definition of `method` from trait
...
17 |       mock! {
   |       ^^^^^ impl has extra requirement `P: 'static`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

I have tried running with ` -Z macro-backtrace` but I get `error: unknown `-Z` flag specified: macro-backtrace`

**Comment by asomers-ax** [comment]
The error message says it all: your trait impl doesn't match the trait definition.  You need to add the `'static` bound to the trait definition.  Either that, or remove it from the mock! section.

**Comment by jjmark15** [comment]
removing `'static` doesn't seem to solve the issue for me.

originally I didn't have the `'static` lifetime which resulted in `error[E0310]: the parameter type `P` may not live long enough` and the suggestion to add the static lifetime. I thought from looking at the mock of `foo` above which does use `'static` that using `'static` might solve the issue. Do you have a suggestion for how to resolve this without modifying the original trait, since as far as I can tell removing `'static` doesn't solve the issue?

**Comment by asomers** [comment]
Modify the original trait, but only in test mode.  That's the way to do it:
```rust
pub trait TestTrait {
    #[cfg(not(test))]
    fn method<P>(&self, argument: P) -> Result<String, ()>
    where
        P: AsRef<Path>;
    #[cfg(test)]
    fn method<P>(&self, argument: P) -> Result<String, ()>
    where
        P: AsRef<Path> + 'static;
}
```

**Comment by jjmark15** [comment]
thanks, I'll do that from now on. Hadn't thought properly about the effect of the `AsRef` on the lifetime requirements of the mock
