### ISSUE TITLE
Mocking Trait with a method that include generics panics

### ISSUE THREAD

**Issue by boaz-codota** [asomers/mockall#209]
```rust
pub type Token = i32;

#[automock]
pub trait Decoder {
  fn decode(&self, tokens: impl IntoIterator<Item = Token>) -> Result<String>;
}
```
This fails with the following error message:
```
error: custom attribute panicked
  --> thing.rs:29:1
   |
29 | #[automock]
   | ^^^^^^^^^^^
   |
   = help: message: deimplify should've already been run on this output type
```

I've also tried `#[automock(type Token=i32;)]` which also fail.

What am I doing wrong?

**Comment by asomers** [comment]
Firstly, if you build Mockall with the `nightly` feature, you'll get better error messages.
Secondly, which version of Mockall are you using?  You should always report the version number whenever you report a bug to any project.
Thirdly, you can probably fix your problem by redefining your method to this equivalent syntax:
```rust
fn decode<T: IntoIterator<Item = Token>>(&self, tokens: T) -> Result<String>;
```
