### ISSUE TITLE
Mocking trait objects which make use of upcasts

### ISSUE THREAD

**Issue by Matthias247** [asomers/mockall#210]
I'm trying to mock an interface which looks similar to:

```rust
pub trait DataSink {
    fn process_data(
        &'a self,
        data: [&'a [u8],
    ) -> Result<(), Error>;
}

pub trait Component: DataSink {
    /// A manual upcast from &dyn Component to &dyn DataSink - since Rust doesn't support it out of the box
    fn as_data_sink(&self) -> &dyn DataSink;

    fn do_other_stuff(&self) -> Result<(), Error>;
}
```

Overall the software will use `Arc<dyn Component>`  in a few places.

I'm now trying to figure out how to mock `Component` but I'm running into a few issues here:

First of all I tried to just apply `automock` on `Component` and/or `DataSink`- but this didn't work out.
Then I read up on the docs that I had to use the `mock!` macro, so I went for:

```rust
#[cfg(test)]
mock! {
    struct Sink {}
    pub trait DataSink {
         fn process_data(
            &'a self,
            data: [&'a [u8],
        ) -> Result<(), Error>;
    }

    pub trait Component: DataSink {
         fn as_data_sink(&self) -> &dyn DataSink;

         fn do_other_stuff(&self) -> Result<(), Error>;
     }
}
```

Doing this will lead to an error along:

>   = help: within `Component::__as_data_sink::Expectation`, the trait `std::marker::Sized` is not implemented for `(dyn DataSink + 'static)`

But it's not a great solution anyway - I would just want `as_data_sink()` to always return `self` and not want to mock it.

Is there any way to get this running? Leaving the `as_data_sink` out of the `mock!` declaration and trying to write it manually does not seem to work. As well as just having an implementation of it inside the `mock!` block:

```rust
#[cfg(test)]
mock! {
    struct Sink {}
    pub trait DataSink {
         fn process_data(
            &'a self,
            data: [&'a [u8],
        ) -> Result<(), Error>;
    }

    pub trait Component: DataSink {
         // This does not work
         fn as_data_sink(&self) -> &dyn DataSink {
             self
         }

         fn do_other_stuff(&self) -> Result<(), Error>;
     }
}

// This also doesn't work
impl DataSink for MockSink {
    fn as_data_sink(&self) -> &dyn DataSink {
        self
    }
}
```

If there is a way to work around the `Expectation: Sized` issue I guess another way to work around it could be to to configure the mock using a constructor function to always return `self` when asked for `as_data_sink`, but it seems a bit more verbose.

**Comment by asomers-ax** [comment]
1) Try writing `-> &impl DataSink` instead of `-> &dyn DataSink`.  That might work.  `&dyn DataSink` could be made to work, but it would require some changes to Mockall.
2) As you've discovered, you can't split a trait's impl block into two.  Rust doesn't allow that.  And `mock!` doesn't allow you do declare methods that aren't mocked.  But there are three things you could do:
  a) Define a default implementation for that method in the trait's definition.
  b) Don't mock the trait implementation.  Instead, add inherent methods to the mock object like `_do_other_stuff` and wrap them in a separate trait impl block.
  c) Just go ahead and mock the method.

**Comment by Matthias247** [comment]
Thanks for the fast response!

> 1. Try writing -> &impl DataSink instead of -> &dyn DataSink. That might work. &dyn DataSink could be made to work, but it would require some changes to Mockall.

This doesn't work, since the trait wouldn't be object-safe anymore. I need this for this use-case, since otherwise it spreads out generic parameters too far.

> a) Define a default implementation for that method in the trait's definition.

That's what I initially tried. Unfortunately the rust compiler then fails with:
> help: the trait `std::marker::Sized` is not implemented for `Self`

And if I add `Component: Sized` it again isn't object-safe anymore.
