### ISSUE TITLE
Is it possible to return in order?

### ISSUE THREAD

**Issue by linxiulei** [asomers/mockall#211]
I want the mock trait to return a result according to the sequence of invocations. For example

```
mock_thing = MockThing::new();
mock_thing.expect_call().returning(|| 1).returning(|| 2);

assert_eq!(mock_thing.call(), 1);
assert_eq!(mock_thing.call(), 2);
```

**Comment by asomers** [comment]
Yes, just use a `Sequence`: https://docs.rs/mockall/0.8.1/mockall/#sequences
