### ISSUE TITLE
Clippy warnings when mocking impl trait with String parameters in methods

### ISSUE THREAD

**Issue by MaximeJEUSS** [asomers/mockall#212]
**Mockall version : 0.7.2** (Can't compile 0.8.* versions with windows)

Clippy generates warnings when I mock impl traits with a method that has String parameters : 

Exemple : 
```rust
pub struct Structure;
#[automock]
impl Structure {
    pub fn method(string_param: String) {}
}
```

generates the following warning : 

```
writing `&String` instead of `&str` involves a new object where a slice will do.
 
note: `#[warn(clippy::ptr_arg)]` on by default
help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg
```

The warning should occur only for &String parameters, shouldn't it ?

Thanks in advance

**Comment by asomers-ax** [comment]
This is already fixed by #195.  However, what's wrong with 0.8 on Windows?  Could you please open a separate issue for that?  I don't have access to Windows, so I'm not aware of any trouble there.

**Comment by MaximeJEUSS** [comment]
Sorry for the duplicate.
I will create a new issue for the windows compilation error 
Thanks !

**Comment by dmolokanov** [comment]
I believe this change didn't make it to the 0.8.x release? At least I didn't see changes in the r0.8.1 branch. Could you please release this change?

**Comment by asomers-ax** [comment]
Yeah, I think I can do a point release for this change.  I'll probably have time on Monday.

**Comment by asomers** [comment]
Done: v0.8.2.

**Comment by dmolokanov** [comment]
Thanks, @asomers! Really appreciate that!
