### ISSUE TITLE
Question: is it possible to mock functions that belong to external modules?

### ISSUE THREAD

**Issue by rbruggem** [asomers/mockall#219]
For instance, [`tokio::time::delay_for`](https://docs.rs/tokio/0.2.6/tokio/time/fn.delay_for.html).

**Comment by asomers-ax** [comment]
Sure.  You can use `automock` like this:
```rust
#[cfg(test)]
#[automock]
mod time {
    fn delay_for();
}

#[cfg(test)]
use mock_time as time;
#[cfg(not(test))]
use time;
```

**Comment by asomers** [comment]
I'm going to close this issue, because I think you're satisfied by that answer.  But BTW, the `[#double]` attribute might help you, too.
https://docs.rs/mockall_double/0.1.0/mockall_double/attr.double.html

**Comment by jinq0123** [comment]
> ```rust
> #[cfg(test)]
> #[automock]
> mod time {
>     fn delay_for();
> }
> ```
should be
```rust
fn delay_for() {}
```
else
```
error: custom attribute panicked
   = help: message: Unsupported item.
```
