### ISSUE TITLE
clippy::default_trait_access warning

### ISSUE THREAD

**Issue by dmolokanov** [asomers/mockall#221]
Some projects rely heavily on clippy code checks. When it is set to `pedantic` it doesn't tolerate even nits.
Please find repro below.

lib.rs
```rust 
#![deny(rust_2018_idioms, warnings)]
#![deny(clippy::all, clippy::pedantic)]

#[derive(Debug)]
pub struct Bar;

#[mockall::automock]
impl Bar {
    pub fn bar(&self) {
        dbg!(&self);
    }
}
```

```
> cargo clippy
    Checking mockall-example v0.1.0 (/home/dmolokan/code/mockall-example)
error: Calling `__mock_MockBar::__bar::Expectations::default()` is more clear than this expression
 --> src/lib.rs:7:1
  |
7 | #[mockall::automock]
  | ^^^^^^^^^^^^^^^^^^^^
  |
note: the lint level is defined here
 --> src/lib.rs:2:22
  |
2 | #![deny(clippy::all, clippy::pedantic)]
  |                      ^^^^^^^^^^^^^^^^
  = note: `#[deny(clippy::default_trait_access)]` implied by `#[deny(clippy::pedantic)]`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_trait_access
  = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by asomers** [comment]
What's the warning that Clippy reports for that code?

**Comment by dmolokanov** [comment]
I updated description

**Comment by dmolokanov** [comment]
Any estimates when the next release will be available? Perhaps with this change?

**Comment by asomers** [comment]
I've been dithering on whether to make a new release.  The concern is that Mockall's master branch is slightly incompatible with the 0.8 release series.  Alternatively, I could rework things in order to preserve backwards compatibility.  But that would be a lot of work, which is why I haven't done it.

**Comment by dmolokanov** [comment]
I see. I guess I can cherry-pick this patch on top of the `0.8` branch? Will that simplify the release process?

**Comment by asomers** [comment]
Release as 0.8.3
