### ISSUE TITLE
fail to mock trait with dyn arguments

### ISSUE THREAD

**Issue by petar-dambovaliev** [asomers/mockall#232]
```
trait Connection {
    fn execute<T>(&self, statement: &T, params: &[&(dyn ToSql + Sync)]) -> Result<u64, Error>
    where
        T: ?Sized + ToStatement;
}
```

> the parameter type `T` may not live long enough E0310 Help: consider adding an explicit lifetime bound...
> use of undeclared lifetime name `'__mockall_params` E0261 Help: consider introducing lifetime `'__mockall_params` here Help: consider introducing lifetime `'__mockall_params` here

**Comment by asomers** [comment]
Wow, that's a complicated method!  There are four problems with it:
* First of all, as you've probably figured out by now, Mockall can only handle generic type arguments that are `'static`.  So you'll have to add a `T: 'static` bound.
* Secondly, whenever a Rust function contains a reference, that reference must always have a lifetime.  Almost always you can elide the lifetimes and the compiler will figure it out.  But that's not always the case with Mockall, which generates oodles of code for each mocked method.  So it helps to make it explicit, like this:
```rust
fn execute<'a, T: 'static>(&self, statement: &'a T, params: &'a[&'a (dyn ToSql + Sync)]) -> Result<u64, Error>
    where
        T: ?Sized  + ToStatement;
```
* The `(dyn ToSql + Sync)` is a trait object.  Mockall needs to know what the trait object's lifetime is.  The easiest way is to write it like this: `(dyn ToSql + Sync + 'static)`.
* Fourth, this method combines generic types with lifetime parameters in a single method.  That combination is currently unsupported.  It probably could be, but it would take some work.

So sadly Mockall doesn't work for you ATM.  If you can make that method non-generic, then it would work fine.

**Comment by petar-dambovaliev** [comment]
> Wow, that's a complicated method!  There are four problems with it:
> * First of all, as you've probably figured out by now, Mockall can only handle generic type arguments that are `'static`.  So you'll have to add a `T: 'static` bound.
> * Secondly, whenever a Rust function contains a reference, that reference must always have a lifetime.  Almost always you can elide the lifetimes and the compiler will figure it out.  But that's not always the case with Mockall, which generates oodles of code for each mocked method.  So it helps to make it explicit, like this:
> ```rust
> fn execute<'a, T: 'static>(&self, statement: &'a T, params: &'a[&'a (dyn ToSql + Sync)]) -> Result<u64, Error>
>     where
>         T: ?Sized  + ToStatement;
> ```
> * The `(dyn ToSql + Sync)` is a trait object.  Mockall needs to know what the trait object's lifetime is.  The easiest way is to write it like this: `(dyn ToSql + Sync + 'static)`.
> * Fourth, this method combines generic types with lifetime parameters in a single method.  That combination is currently unsupported.  It probably could be, but it would take some work.
> 
> So sadly Mockall doesn't work for you ATM.  If you can make that method non-generic, then it would work fine.

I just created a mock by hand for this type. For other simpler types I can use mockfall

**Comment by asomers** [comment]
Glad you found a solution..
