### ISSUE TITLE
Question about mocking external structs

### ISSUE THREAD

**Issue by johnoneil** [asomers/mockall#235]
I've been through the documentation and the examples but can't quite find something that covers my use case. I've found Mockall to be very easy to use but am running into an issue that I can't seem to resolve.

I'm writing tests for a crate (lib) on one package, which has a dependency on a crate i(lib) n another package. The dependency does not expose any traits. I could add them but I'm reluctant to do so currently.

Still I would like to mock the structs exposed by the dependency crate. My thoughts about how to do this are as follows

1. Add the automock trait to the structs in the dependent package ant then (conditionally on test) expose the generated mocks to clients. Reluctant to do this (even if it would work) as it sounds bad. I would think the mocks should only be present in the module I'm testing.

2. Do something like this. https://github.com/asomers/mockall/issues/60#issuecomment-552108151 . But this would require me to write quite a bit of difficult to maintain code, kind of defeating the purpose of auto-mocking.

If you have any thoughts I'd appreciate it. At least for the moment mockall has helped us get considerable test coverage with little effort. Very much appreciated.

**Comment by asomers** [comment]
You have two options: export mocks from the dependency, or use `mock!`.
1. Export mocks from the dependency.  Don't gate them on `#[cfg(test)]`, as that is only for unit tests.  Instead, create a new off-by-default crate feature, e.g. `mocks`.  Then put `#[cfg_attr(mocks, automock)]` on all of the structs that you want to mock.
2. Use `mock!` in the consuming crate.  This doesn't require you to make any changes to the dependency, but it's a little bit fragile, because you may not notice if the dependency changes its API.

Neither option is "best".  You'll just have to figure out what works for you.

**Comment by johnoneil** [comment]
Thank you asomers. I believe I will try the first option you mention.
Going to close this issue but it should remain searchable for people with the same question.
thx

**Comment by johnoneil** [comment]
Just wanted to update this issue with the direction we had to go.
 Option 1here: https://github.com/asomers/mockall/issues/235#issuecomment-744606261 didn't quite work out. The idea is to tie `automock` mocks in the separate package with a feature (say `mocks`) and then turn that feature on when testing against it.
That doesn't seem to work out. Cargo doesn't seem to allow having the same dependency with different features in a `test` build. To my knowledge we'd have to explicitly turn on the feature on via `cargo test --cfg feature_name` or other. That seems pretty clumsy. Cargo seems to have no end of limitations like that. Very frustrating.

We did decide to go with Option 2 but it also required using the `cfg-if` crate, to swap in struct mocks built using `mock1`. On the plus side we only needed to mock the methods called in that module (just a subset of the struct's methods), which makes it more robust, but it takes more code (upwards of 60+ lines).
Taking that approach also introduces a (non development) dependency on `cfg-if` which we're not crazy about.

In the end if any other solutions for this are apparent, please bump this issue. We've got something working, but it could def use improvement.

**Comment by asomers** [comment]
I wouldn't worry about bringing in cfg-if.  It's pretty tiny, and already used all over the place.  If you look in your Cargo.lock, you'll probably find that it's already in there.  But if you REALLY want to remove it, you can replace it like this:
```rust
#[cfg(test)] 
use MockMyStruct as MyStruct;
#[cfg(not(test))]
use my_crate::MyStruct;
```
Or, if you want to save a bit of typing, you can use the [mockall_double](https://docs.rs/mockall_double/0.1.0/mockall_double/) crate, like this:
```rust
use mockall_double::double;
pub mod my_mod {
    pub use my_crate::MyStruct;
    mock! {
        pub MyStruct {
            ...
        }
    }
}
#[double]
use my_mod::MyStruct;
```

**Comment by huy-vuong** [comment]
Hey there, I was trying to get this to work, but I'm having a lot of trouble since my production code now expects `MockMyStruct` instead of `MyStruct`. Is there a good example I could follow that shows where to put each of these snippets of code?

**Comment by asomers** [comment]
@huy-vuong it sounds like you've got some kind of `#[cfg()]` statement wrong.  If you want help, open a new issue and show me what you're trying to do.
