### ISSUE TITLE
Can't set simultaneous expectations of different types on generic method whose generic parameters only appear in output

### ISSUE THREAD

**Issue by Kormick** [asomers/mockall#236]
I'm trying to mock a struct with the generic method. And for the case when we use generic parameter only as return type, expectation set panics if we use different types. But it will be ok if we set expectations for the same type, or if we add the generic parameter as a method argument.
I've created a minimal example in this repo: https://github.com/Kormick/mockall-test. Please take a look.

I'm using `rustc 1.50.0-nightly (eb4fc71dc 2020-12-17) (from rustc 1.50.0-nightly (6645da366 2020-12-01))` toolchain

Panic message: ```panicked at 'called `Result::unwrap()` on an `Err` value: TypeMismatch { expected: "[ONLY ON NIGHTLY]", found: "[ONLY ON NIGHTLY]" }'```
For some reason, I always have the `[ONLY ON NIGHTLY]` message, even though I'm using the nightly toolchain. 

Backtrace:
```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/6645da366eed0c61258a04265bea513e94df7ea6/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/6645da366eed0c61258a04265bea513e94df7ea6/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/6645da366eed0c61258a04265bea513e94df7ea6/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /home/kormick/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:973:23
   4: mockall_test::__mock_MockStorage::__get::GenericExpectations::expect
             at ./src/lib.rs:5:1
   5: mockall_test::MockStorage::expect_get
             at ./src/lib.rs:5:1
   6: mockall_test::test_get_different_types
             at ./src/lib.rs:32:5
   7: mockall_test::test_get_different_types::{{closure}}
             at ./src/lib.rs:29:1
   8: core::ops::function::FnOnce::call_once
             at /home/kormick/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/6645da366eed0c61258a04265bea513e94df7ea6/library/core/src/ops/function.rs:227:5
```

**Comment by asomers** [comment]
To get a more useful error message, you must not only use the nightly toolchain, but also build mockall with the "nightly" crate feature.

**Comment by Kormick** [comment]
Adding `features = ["nightly"]` in `Cargo.toml` for `mockall` should be enough, right? I've tried this and with the cloned `mockall` repo, but still get `[ONLY ON NIGHTLY]`

**Comment by asomers** [comment]
Oh, I see.  That "ONLY ON NIGHTLY" message is coming from the downcast crate, which also has a nightly feature.  You've found a bug.  I'll try to fix it as time allows.

**Comment by Kormick** [comment]
Ok, thank you! 👍
