### ISSUE TITLE
Mock FFI module generated with bindgen

### ISSUE THREAD

**Issue by johannes-mueller** [asomers/mockall#240]
I am generating an FFI module using bindgen and tried to mock it like this
``` rust
#[cfg(test)]
use mockall::automock;

#[cfg_attr(test, automock)]
pub mod ffi {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}
```
Running `cargo +nightly test` gives
```
error: Unsupported item
 --> src/pugl.rs:8:5
  |
8 |     include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

Any chances?

BTW: any guesses when mocking an entire module will no longer need `+nightly`?

**Comment by asomers** [comment]
What's happening is that rustc is trying to expand `automock` _before_ it expands `include!`.  Maybe you can use a `build.rs` script to insert the `automock` directly into `bindings.rs`?

And BTW: mocking an entire module no longer requires nightly as of 0.9.0, released four days ago.

**Comment by johannes-mueller** [comment]
Tried it.

`bindings.rs` now looks like:
``` rust
#[cfg(test)]
use mockall::automock;

#[cfg_attr(test, automock)]
pub mod ffi {
/* automatically generated by rust-bindgen 0.56.0 */
...
}
```
Error message:
```
error: custom attribute panicked
 --> /home/joh/Devel/Rust/lv2/pugl-sys/target/debug/build/pugl-sys-286f2c2bad3d4b0a/out/bindings.rs:5:18
  |
5 | #[cfg_attr(test, automock)]
  |                  ^^^^^^^^
  |
  = help: message: Mockall does not yet support deriving nested mocks.  More information may be available when mockall is built with the "nightly" feature.
```
Then the `ffi` module is not found.

The project builds fine and also, when I drop the line `#[cfg_attr(test, automock)]` the testing (I don't have tests that need the mock, yet) is running fine.
`

**Comment by asomers** [comment]
This error happens because your module contains another module, enum, struct, union, or trait.  Enabling the "nightly" feature will show you which.

**Comment by johannes-mueller** [comment]
Ok. Now I worked around this by splitting the bindgen process. First I blacklist all the functions to generate a module with all the FFI types. In a second I blacklist all the types and generate a `#[automock]`ed module with only the functions, because the functions are all I want to actually mock.

Now I am struggling with `Predicate`s. I have lots of functions of the style `void mystruct_set_foo(mystruct *ms, foo_t foo)`. My idea was to test that like
```rust
let ctx: ffi::mystruct_set_foo_context();
ctx.expect().with(predicate::always, predicate::eq(expected_value))
/// code that is supposed to call mystruct_set_foo() with expected_value
```
And I get something like
```
720 |         ctx.expect().with(
    |                      ^^^^ the trait `Predicate<*mut MyStruct>` is not implemented for `fn() -> predicates::constant::BooleanPredicate {mockall::predicate::always}`

```

**Comment by asomers** [comment]
Hm.  Apparently `always` isn't implemented for raw pointers.  I didn't realize that.  You could make a feature request at https://github.com/assert-rs/predicates-rs to add it.  And in the meantime, you can use Mockall's `withf` method, like this:
```rust
let ctx: ffi::mystruct_set_foo_context();
ctx.expect()
    ..withf(|_ms, foo| foo == expected_value)
```

**Comment by johannes-mueller** [comment]
`.withf()` indeed solves it and the tests do compile. However I am now running into an issue at runtime `No matching expectation found.`

This might be due to my lack of understanding about how expectations are supposed to work. Generally my goal is to mock functions of an external C-library in order to test if my Rust abstraction layer is calling the external functions properly, i.e. with sanitizitions like null-terminating strings etc.

Is there some OSS-project that does this, where I can check how this can be done?

Thanks for your help.

**Comment by asomers** [comment]
Offhand I don't know of any other projects that use Mockall exactly the way that you do.  But the best way to check is to look through Mockall's reverse dependencies on crates.io.

https://crates.io/crates/mockall/reverse_dependencies

**Comment by johannes-mueller** [comment]
Ok. Finally got the tests running. The problem was, that I needed to actually call the functions that were mocked by `#[automock]`. I could solve that by setting up an expectations that uses `.returning()` to call the actual function.

For those interested: the code is here. 
* [set up the expectations](https://github.com/johannes-mueller/pugl-sys/blob/c225dd4ecb070e11b68fe05c8a3c3051da95ddec/src/view.rs#L581). 
* [run a test with a special expectation](https://github.com/johannes-mueller/pugl-sys/blob/c225dd4ecb070e11b68fe05c8a3c3051da95ddec/src/view.rs#L854) 

Not sure it is the smartest way to do it. Feedback welcome.

Closing issue, thanks for your help.
