### ISSUE TITLE
Sequence: output on failure identifying which calls were missed

### ISSUE THREAD

**Issue by WasabiFan** [asomers/mockall#241]
Hi!

Today was my first experience with `Sequence`. I set up a `Sequence` with five operations, and in the process had a mismatch between my test and the module under test -- the implementation invoked two functions twice, rather than each only once as the test expected. The result was:

```
thread 'drivers::current_regulator::tle7242_current_regulator::tests::check_connectivity_succeeds' panicked at 'assertion failed: `(left == right)`   
  left: `4`,
 right: `3`: Method sequence violation', C:\Users\kaeli\.cargo\registry\src\github.com-1ecc6299db9ec823\mockall-0.9.0\src\lib.rs:1530:9
stack backtrace:
<...>
```

Through traversing the call stack, I found the invocation of a mocked function which caused the panic, and from there with a bit of reasoning I was able to diagnose the root cause. I had a good amount of trouble discerning what went wrong, since it wasn't clear without looking at the implementation what the two values being asserted were, it was hard to tell whether something was being called _too many_ times or _too few_, and I wasn't sure what had already been called vs. what was skipped.

Ideally, it would be nice to get an error message printed before the panic which told me where we were in the sequence (including which method was just called!), which calls had correctly occurred, and which ones _hadn't_ correctly (or yet) occurred.

Firstly, is there any interest in this? Is there something else I should be seeing or doing here instead?

I'd be up for giving some improvements a shot in the next few days, if that's welcome and warranted. Is there a straightforward way to implement a more thorough readout without too large a change?

Looking at the way that `Sequence`s are implemented, I must admit, it's quite elegant! Unfortunately, there just isn't a lot of context to go off of. I think if we wanted fully detailed panic messages, there would likely need to be a Vec of call metadata or similar stored in the sequence, to allow it to report on context upon validation failure. Probably wrapped in a mutex. Was this intentionally avoided? It looks like there's no heap allocation at all required in the current implementation, which makes me wonder whether there were perf or other goals here.

**Comment by asomers** [comment]
Would it be useful if the panic message said something like `Method sequence violation.  5th method called before 3rd.`?  That would be an easy change.

**Comment by WasabiFan** [comment]
Yeah, I think such a message would be appreciated. That being said, it's rather hard to tell _which_ is the 3rd or 5th — e.g., in my case, some of them are added by helper methods. Capturing names of the functions as part of the mock macro and then including those as well may help, and I think that would be not too much extra from an implementation perspective.

Ideally, what would really be nice — and I recognize there are implementation challenges here — would be to print the ordered function names in a list, so I can visually see which were skipped too.

**Comment by asomers** [comment]
After doing #246 , I realize that it wouldn't be too hard to print the offending method's name and arguments when a Sequence violation occurs.  I'm going to try that next.

**Comment by WasabiFan** [comment]
I think that would definitely be a welcome feature!
