### ISSUE TITLE
Skip generating mock methods

### ISSUE THREAD

**Issue by KaiserKarel** [asomers/mockall#242]
I've ran into the already described problems of generic arguments needing to be `'static`. In my case I could do with implementing the method on the `MockFoo` myself, and simply making it a noop. Is there some way to annotate a method in a trait such that automock generates a noop for that method? I am mocking a trait, thus I cannot write a separate impl block.

Perhaps something like:

```
#[automock]
trait Foo {
    #[automock(path="local_fn")]
    fn bar<A>(a: A) -> A;
}

local_fn<A>(a: A) -> A { a }
```

**Comment by asomers** [comment]
Here are two workarounds:

- In test mode, add `'static` bounds.  That's easiest.  It's what I usually do.  But it does impose some restrictions:
  ```rust
  #[cfg_attr(test, automock)]
  trait Foo {
      #[cfg(test)]
      fn bar<A: 'static>(a: A) -> A;
      #[cfg(not(test))]
      fn bar<A>(a: A) -> A;
  ```
- Use mock! to generate inherent methods, and then manually implement the trait in terms of the inherent methods.  This works well on traits with a small number of methods:
```rust
  mock! {
      Foo {
          fn foo_(&self, x: i32) -> i32;
      }
  }
  impl Foo for MockFoo {
      fn foo(&self, x: i32) -> i32 {self.foo_(x)}
      fn bar<A>(a: A) -> A {A {a} }
  }
  ```

I'll mull over your suggestion some more.  Some feature along these lines might be a good idea.

**Comment by KaiserKarel** [comment]
I'll give that second option a shot; the trait is not very complicated; but even in testing situations, the `'static` bounds won't do.

**Comment by ljw1004** [comment]
I think this issue shouldn't be marked as closed. The suggestion "allow to skip generating mock methods" is a good one, and even though you found a workaround, it's not a great workaround when traits have more than a few methods...

**Comment by ljw1004** [comment]
I can't get the second suggestion to work when the trait is in a module... it complains that the methods generated by `mock!` are private.
```
mod moo {
    pub trait Foo {
        fn foo(&self, x: i32) -> i32;
        fn bar<A>(a: A) -> A;
    }

    mockall::mock! {
        pub Foo {
            fn foo_(&self, x: i32) -> i32;
        }
    }
    impl Foo for MockFoo {
        fn foo(&self, x: i32) -> i32 {
            self.foo_(x)
        }
        fn bar<A>(a: A) -> A {
            a
        }
    }
}

pub fn main() {
    let mut m = moo::MockFoo::new();
    m.expect_foo_().returning(|x| x + 1); // ERROR: associated function is private
    println!("{}", m.foo(2)); // ERROR: no method for foo in current scope
}
```

**Comment by asomers** [comment]
@ljw1004 the inherent methods in `mock!` are inherent methods, not trait methods.  As such, they have a visibility attribute.  Go ahead and add `pub` there are it should fix your problem.
