### ISSUE TITLE
[question] Cross crate dependencies - expected struct / found struct

### ISSUE THREAD

**Issue by lfrancke** [asomers/mockall#248]
Thank you for your project. I'm currently trying to use it for the first time with structs and am hitting a stumbling block.

I have two crates where one depends on the other.

crate `a`:
```rust
pub mod a {
    pub struct FooBar {}

    #[mockall::automock]
    impl FooBar {
        pub fn test_foobar() {
            println!("Test Foobar");
        }
    }
}

pub mod b {
    #[mockall_double::double]
    use crate::a::FooBar;

    pub struct BarFoo {}

    #[mockall::automock]
    impl BarFoo {
        pub fn new() -> BarFoo {
            BarFoo {}
        }
        pub fn test_barfoo(&self, foobar: FooBar) {
            println!("Test barfoo");
        }
    }
}
```
crate `b`:
```rust
#[mockall_double::double]
use a::a::FooBar;
#[mockall_double::double]
use a::b::BarFoo;

fn main() {
    let foobar = FooBar {};
    let barfoo = BarFoo::new();

    barfoo.test_barfoo(foobar);
}

#[cfg(test)]
mod tests {

    use super::*;

    #[test]
    fn test() {}
}
```

Running `cargo test` for crate `b` fails with:
```
error[E0308]: mismatched types
  --> b/src/lib.rs:10:24
   |
10 |     barfoo.test_barfoo(foobar);
   |                        ^^^^^^ expected struct `FooBar`, found struct `MockFooBar`
```

If I copy everything from crate `a` to crate `b` it works.
I'm a bit stumped. This is similar to #122 but not the same I believe.

**Comment by asomers** [comment]
You didn't specify which command was failing.  Was that `cargo test --lib`?  And are the two code snippets from separate crates?  In that case, the problem is that the first crate gets built in normal mode when it's used as part of the second crate's unit tests.  So The second crate is creating a `MockFooBar`, but is supplying it to a function that wants a `FooBar`.  You can't use `mockall_double` to create stuff you want to be publicly exported.

**Comment by lfrancke** [comment]
Thank you for the super quick response. I'm sorry about the missing information, no excuse for that.
I edited the issue but you are already spot on.

I assumed, _wrongly_ it seems, that the `test` mode is transitive (I'm still new to Rust).
In that case I understand why `mockall_double` is out, so is the manual way of doing `#[cfg(not(test))] ...` because it'll have the same issue.

Is there another workaround you can think of?

**Comment by asomers** [comment]
Most people only use Mockall within a single crate.  You're trying to publicly export mocks.  That's unusual, but not disallowed.  It seems like this `test_barfoo` function is only intended to be used from other crates' unit tests?  In that case, just declare it as `fn test_barfoo(&self, foobar: MockFooBar)`.  OTOH, if you actually want two version of the function, one for a real `FooBar` and one for a `MockFooBar`, then you'll have to declare two separate functions.

**Comment by lfrancke** [comment]
Thank you.
No, `test_barfoo` is a regular method.
It's quite the opposite actually in my case. It's only used in production code but because that lives in the same module as code under test it has its `FooBar` replaced by `MockFooBar`.
My code is actually open-source so I'd be happy to point at it but I tried to provide a minimal example which should be easier to read.

I had the idea of publicly exporting the Mocks so users of my library can easily use them in their own unit tests but this isn't as easy as I had hoped as I don't really want to declare each function in two versions.
Either way this helped me a lot to understand what's going on.
