### ISSUE TITLE
[question] How to see the actual call arguments

### ISSUE THREAD

**Issue by SuperCuber** [asomers/mockall#249]
Say I have this code:
```rust
obj.expect_foo()
    .times(1)
    .with(eq(5))
    .returning(|| ())

obj.foo(4)
```
I get the error `Obj::foo: No matching expectation found`.

How can I know what was the actual argument `foo` was called with?

**Comment by asomers** [comment]
You couldn't, until last week!  I just added that feature in #246 .

**Comment by asomers** [comment]
There are two conditions that must be met to see the function arguments:
* The must implement `Debug`
* You must activate mockall's `nightly` feature (but not if you use the git master branch)
