### ISSUE TITLE
fakeable (dual of mockable)

### ISSUE THREAD

**Issue by dzmitry-lahoda** [asomers/mockall#250]
```rust
#[fakeable] 
trait Bark<T> { 
 fn tell(&self) -> T;
}

#[fakeable] 
trait Meow<T> 
{ 
 fn tell(&self) -> T;
}

// ...

#[fake(Bark<String>,Meow<u128>)] 
pub struct FakeZoo{
}

let zoo = FakeZoo{};

// setup expect for zoo calls per trait

let what_cat_said: u128 = zoo.tell();
let what_dog_said: String = zoo.tell();

fn tell<T:Bark<K>, K>(noise_maker:&T) {
...
}

tell(&zoo);
```

**Comment by asomers** [comment]
Are you asking for a new feature?  The code sample isn't enough for me to understand what you want.  Could you please spell it out?

**Comment by dzmitry-lahoda** [comment]
1. new feature. yes.
2. image I have `Database` struct. I have various traits for it impemented, like `GetById<T>`, `GetByname<T>` etc.  I want implement these traits in FakeDatabase via mockall by DSL as described above. it is not possible with current mockall implemenetation.

**Comment by asomers** [comment]
What DSL?  You didn't describe any.  I still don't understand what you hope the `fake` and `fakeable` macros will do.

**Comment by asomers** [comment]
Closing for lack of information.

**Comment by dzmitry-lahoda** [comment]
i see. will implement by hand. the problem is that current mock all does not allows one struct, many traits (e.g. one DB many Getters) to be mocked well (needs cfg_if and mock! - it not well). i say that there is no need for declarative macro with fakes. dsl will write auto what i do manually
