### ISSUE TITLE
Wait on method invocation

### ISSUE THREAD

**Issue by ChrisGreenaway** [asomers/mockall#254]
I want to make sure that a method is called by my unit under test, but that might happen in an async way.

It would be good to be able to have a future that completes when a matching call to a mock happens. Then, at the end of my test, I can await on that future.

**Comment by asomers** [comment]
The easiest way to do this is by adding a side effect to your method's `returning` closure.  Something like this:
```rust
let (tx, rx) = futures::channel::oneshot::<()>();
let mut mock = MockFoo::new();
let mut runtime = tokio::runtime::Runtime::new();
mock.expect_foo()
    .return_once(move |_| {
        tx.send(()).unwrap();
    });
...
runtime.block_on(rx)
```

**Comment by ChrisGreenaway** [comment]
Yes - I've done something similar in my current code - using Arc<AtomicBool> rather than a channel.

But a code-reviewer asked whether there was direct support for waiting like this in `mockall`. Which seemed like a reasonable question.

Thanks for the prompt reply.

**Comment by asomers** [comment]
I don't think that it's possible to implement such a thing within Mockall.  Should the future complete before or after your mock method returns?  In my example, the future completes slightly before.  It would be safer if it completed slightly after.  However, Mockall doesn't have any way to run code at that point.
