### ISSUE TITLE
Mocking free functions from modules in another file - in 2021

### ISSUE THREAD

**Issue by falconmick** [asomers/mockall#260]
see original issue: #49

I've been beating my head against the keyboard on this one for a good 3 hours and cannot make any purmutations of code that satisfy the compiler.

Basically I have a module that I want to use as a mock, I then wish to write assertions against the calls of the functions inside of this module. I have based my code off of it:
https://github.com/asomers/mockall/issues/49#issuecomment-531379223

My only guess to why my implementation isn't working is that the `mockall_double` package didn't exist back in 2019 so now some of the code has moved there, however I am unable to find any good exampels of how to use doubles with free functions that exist within a module in a separate file, I can only find the example within the docs which is in a single file :(

Example:

some_module.rs
```rust
use cfg_if::cfg_if;
#[cfg(test)]
use mockall::automock;

#[cfg_attr(test, automock)]
pub mod thread {
    use std::{thread, time};

    pub fn spawn<F, T>(f: F) -> thread::JoinHandle<T>
    where
        F: FnOnce() -> T,
        F: Send + 'static,
        T: Send + 'static,
    {
        println!("adapter spawn in use!");
        thread::spawn(f)
    }

    pub fn sleep(dur: time::Duration) {
        println!("adapter sleep in use!");
        thread::sleep(dur);
    }
}


cfg_if! {
    if #[cfg(test)] {
        pub use mock_thread::*;
    } else {
        pub use thread::*;
    }
}
```

thing_that_uses_it_test.rs
```rust
use super::*;

#[cfg(test)]
mod tests {
    use std::net::UdpSocket;
    use super::*;
    use adapter::std::thread;

    #[test]
    fn test_thread() {
        let ctx = thread::spawn_context();

        rtp_manager(UdpSocket::bind("127.0.0.1:12322").unwrap(), "foo:");
    }
}
```

This is what the error looks like:
![image](https://user-images.githubusercontent.com/713449/109459551-f392c800-7a99-11eb-823e-7a588a47a64e.png)

For now I am just going to pretend that I am writing my tests like a good boy and just keep pushing foward

**Comment by asomers** [comment]
How is `thing_that_uses_it_test.rs` including the first file?  I don't see any `use some_module;` statement there.

**Comment by falconmick** [comment]
ah ok to clarify this is closer to the structure of my code:

thread_adapter.rs
```rust
use cfg_if::cfg_if;
#[cfg(test)]
use mockall::automock;

#[cfg_attr(test, automock)]
pub mod thread {
    use std::{thread, time};

    pub fn spawn<F, T>(f: F) -> thread::JoinHandle<T>
    where
        F: FnOnce() -> T,
        F: Send + 'static,
        T: Send + 'static,
    {
        println!("adapter spawn in use!");
        thread::spawn(f)
    }

    pub fn sleep(dur: time::Duration) {
        println!("adapter sleep in use!");
        thread::sleep(dur);
    }
}


cfg_if! {
    if #[cfg(test)] {
        pub use mock_thread::*;
    } else {
        pub use thread::*;
    }
}
```
rtp_manager.rs
```rust
//... snip

#[cfg(test)]
mod rtp_manager_test;

pub fn rtp_manager<A: std::net::ToSocketAddrs>(socketAddress: A) -> Result<(), &'static str> {
//... snip
    let handle = thread::spawn(move || {
        //... snip
    });
//... snip
}
```

rtp_manager_test.rs
```rust
use super::*;

#[cfg(test)]
mod tests {
    use std::net::UdpSocket;
    use super::*;
    use adapter::std::thread;

    #[test]
    fn test_thread() {
        let ctx = thread::spawn_context();

        rtp_manager(UdpSocket::bind("127.0.0.1:12322").unwrap(), "foo:");
    }
}
```

I've ive been too snippy let me know what you want to see, I'ts just allot of unrelated code so I'm trying to keep things clear

**Comment by asomers** [comment]
I still don't see any line like `use thread_adapter::*;`.  Where does it get included?

**Comment by falconmick** [comment]
At the bottom of the adapter

‘’’rust
cfg_if! {
    if #[cfg(test)] {
        pub use mock_thread::*;
    } else {
        pub use thread::*;
    }
}
‘’’

doesn’t this basically expose all of the free functions, structs, etc as the module?

**Comment by asomers** [comment]
That would allow other modules to do `use thread_adapter::spawn`.  But you haven't pasted anything that `use`s the thread_adapter file at all.  Where does it get connected?

**Comment by falconmick** [comment]
I was too snip happy:

rtp_manager.rs
```rust
use thread_adapter::thread; // note: the real version of this is actually `use adapter::std::thread` but I have simplified this example
//... snip

#[cfg(test)]
mod rtp_manager_test;

pub fn rtp_manager<A: std::net::ToSocketAddrs>(socketAddress: A) -> Result<(), &'static str> {
//... snip
    let handle = thread::spawn(move || {
        //... snip
    });
//... snip
}
```

**Comment by asomers** [comment]
So by doing `thread_adapter::thread` you've completely bypassed the `if #[cfg(test)]` logic at the bottom of thread_adapter.rs.  thread_adapter.rs is publishing its stuff through two different paths, which could get confusing.  I recommend you remove the `pub` from `pub mod thread`, and only use the exports at the bottom.  The exports currently look like this:

* `thread` - the real thread module
* `mock_thread` - the mock thread module, only when `cfg(test)`
* `spawn` and `sleep` - real or mock, depending on `cfg(test)`
* `spawn_context` and `sleep_context`, when `cfg(test)`

**Comment by asomers** [comment]
Based on the lack of activity, I'm assuming the OP's issue is solved now
