### ISSUE TITLE
Mockall doesn't play nice with source-based code coverage reporting

### ISSUE THREAD

**Issue by bugadani** [asomers/mockall#262]
I'm guessing the generated code implements everything instead of using externally implemented logic. This is fine, except when I use mockall, my code coverage drops steeply. I haven't looked more closely at the implementation, so I may ask something stupid, but would it be possible to reduce the amount of logic generated?

**Comment by asomers** [comment]
Nope!  Believe me, I've tried.  Instead, you'll have to teach your coverage checker to exclude the generated code.  What coverage checker are you using?

**Comment by bugadani** [comment]
The built-in one: https://doc.rust-lang.org/beta/unstable-book/compiler-flags/source-based-code-coverage.html

**Comment by bugadani** [comment]
So, since you've tried, that's good enough of an answer, thanks :) I guess this will need to go to rustc, then. Either I don't set some option to ignore expansions, or that option doesn't exist (yet).

**Comment by asomers** [comment]
It seems like this should be a problem for all proc macros.  If you do find a solution, please let me know.  And BTW, kcov doesn't seem to have the same problem.
