### ISSUE TITLE
allow a feature that triggers the mock doubling

### ISSUE THREAD

**Issue by thedavidmeister** [asomers/mockall#264]
using `#[cfg(test)]` means that if we want to include mocked code in another crate then the double won't be used

if there was a feature for this then that would could be enabled downstream

**Comment by asomers** [comment]
Say what?

**Comment by thedavidmeister** [comment]
if i have crate A that has mocked something using `double` and crate B uses it as a dependency then crate B cannot access the mocks for its testing

`#[cfg(test)]` is only true when the current crate is running tests, not when it is a dependency

**Comment by asomers-ax** [comment]
Yes, that's correct.  The whole point of `double` is that it switches the implementation based on whether the build is in test mode.  If you want to export mocks to another crate you'll have to `mock!` or `#[automock]` unconditionally (or conditionally based on a crate feature).

**Comment by thedavidmeister** [comment]
it could also be behind a feature flag and would be usable downstream, a relatively small change here i think?

**Comment by asomers** [comment]
No.  The whole point of double is that it handles `#[cfg(test)]` for you.  It doesn't do anything else.  If you don't want it to do that, then don't use it.

**Comment by thedavidmeister** [comment]
these are not exclusive things, consider `#[cfg(any(test, feature = "double"))]`

**Comment by asomers** [comment]
At this point, you've nearly rewritten the double macro.  Not only that, but you've hard-coded a feature name which may conflict with a feature name chosen by other consumers of mockall_double.

It would be better for you to rewrite double, or simply inline its logic.

**Comment by thedavidmeister** [comment]
features don't conflict like that, they are re-exported under arbitrary names by consuming crates

**Comment by asomers** [comment]
There is still no reason why you can't implement this logic yourself.  You've provided no reason why it ought to be done within mockall_double instead.  I'm going to close this issue now.  You may reopen it if you have something new to add.

**Comment by thedavidmeister** [comment]
@asomers not sure i understand what you're asking me to justify... can't i say the same about any/all crates?

why is it "better" that i reinvent this wheel than to use a feature flag for what already exists and works well?
