### ISSUE TITLE
How to correctly mock a struct?

### ISSUE THREAD

**Issue by augustocdias** [asomers/mockall#266]
I have a struct that performs operations in the database. I have to sets of tests: unit tests that needs mocked objects for this struct and end to end tests that run on an actual database. 

I run my tests unit tests with something like this:

```rust
let storage = MockStorage::default();
storage.expect_insert_object()
    .withf(...)
    .returning(...);
let result = my_func(obj, storage);
// assert result
```

I tried using the `double` derive but then it breaks the end 2 end tests. Is there a way to accomplish this? If I use double it will inject the mock in the tests that I want the actual implementation as well. If I don't, I can't have the mocks for unit tests.

I also tried using the `mock!` macro but I'm not sure it would solve the problem as the function expects the other type and not the mocked version.

The only way I can imagine is creating a trait, but then it would also introduce the dependency of `async_trait` in my project (which I don't need at the moment).

**Comment by asomers-ax** [comment]
> I have a struct that performs operations in the database. I have to sets of tests: unit tests that needs mocked objects for this struct and end to end tests that run on an actual database.

That's the preferred way to use Mockall, so you're on the right track.

> 
> I run my tests unit tests with something like this:
> 
> ```rust
> let storage = MockStorage::default();
> storage.expect_insert_object()
>     .withf(...)
>     .returning(...);
> let result = my_func(obj, storage);
> // assert result
> ```
> 
> I tried using the `double` derive but then it breaks the end 2 end tests. Is there a way to accomplish this? If I use double it will inject the mock in the tests that I want the actual implementation as well. If I don't, I can't have the mocks for unit tests.

It shouldn't.  You're probably using `mockall_double` incorrectly.  Could you show me how you're trying to use it?

> 
> I also tried using the `mock!` macro but I'm not sure it would solve the problem as the function expects the other type and not the mocked version.
> 
> The only way I can imagine is creating a trait, but then it would also introduce the dependency of `async_trait` in my project (which I don't need at the moment).

**Comment by augustocdias** [comment]
In the place I use the mockable struct I've just added `#[cfg_attr(test, double)]` in the import of my object

```rust
#[cfg_attr(test, double)]
use storage_mod::Storage;

async fn insert_user(storage: Storage) -> Result<()> {}
```
I want to unit test this `insert_user` function. This works fine. The problem is in that I have to add the `double` derive where I call the `insert_user` also. 

```rust
#[cfg_attr(test, double)]
use storage_mod::Storage;

async fn my_endpoint() -> Result<()> {
   let storage = Storage::new();
   insert_user(storage);
}
```

If I don't add the double derive in there, my tests fails to compile. If I add they compile fine.

But then I have some e2e tests, in which I don't want to mock anything and I just call the high level functions. Now the problem is since it is also with the cfg test on for this, it tries to use the mock object there instead of the real one and then it fails because  I don't configure any expectation or anything in mockall.

**Comment by asomers** [comment]
I understand the problem now.  Your unit tests live in the lib, where `test` is set, and your e2e tests also live in the lib.  My suggestion is if you can, change the e2e tests into functional tests in the `tests` directory rather than `lib`.  That way the lib will be compiled without `test` .
Also, you don't need to use `#[cfg_attr(test...` with `double`.  `double` includes the check for `test`; that's its whole point.  Just do
```rust
#[double]
use storage_mod::Storage;
```

**Comment by augustocdias** [comment]
Yeah... I think that makes sense. thank you for the help

**Comment by augustocdias** [comment]
Hi,
Let me ask another question

Lets say I have a static function in a struct
and at some point in my function this static fn is called

```rust
struct StaticStruct;

#[automock]
impl StaticStruct {
   fn my_func() {}
}

// in another file
#[double]
use crate::StaticStruct;

fn my_function_to_test() -> Result<()> {
   StaticStruct::my_func();
}
```

Using the `#[double]` am I able to still expect and verify calls in this function?
In my test can I use something like this?

```rust
let ctx = MockStaticStruct::my_func_context();
ctx.expect()// ... add the returning and param verification

let result = my_function_to_test();
assert!(result.is_ok());
```

**Comment by asomers** [comment]
Yes, that's exactly how you should do it.
