### ISSUE TITLE
Mockall - used by open source projects?

### ISSUE THREAD

**Issue by clue-arch** [asomers/mockall#268]
Hi.

I want to use Mockall for my project but I am facing some problems. In order to have a better overview and to be familiar, I would like to look at open-source projects(complex examples) and how it is applied. Do you know any open-source projects that use a Mockall library?

Thx.

**Comment by asomers** [comment]
Sure.  Just ask crates.io: https://crates.io/crates/mockall/reverse_dependencies .  But the most complete usage of Mockall is likely by bfffs, the project for which Mockall was written: https://github.com/bfffs/bfffs .
