### ISSUE TITLE
Can't set simultaneous expectations of different types on generic method whose generic parameters appear neither in args nor in return type

### ISSUE THREAD

**Issue by twz123** [asomers/mockall#269]
Related to #236, if generic args are neither referenced in method arguments nor in the return type, it's not possible to set expectations for different types.

I've created a test case that shows the problem. The `regular_impl` test shows a regular trait implementation and passes. The `generic_only` test uses a `mock!`ed trait implementation along with expectations and panics:

> thread 'generic_only' panicked at 'called `Result::unwrap()` on an `Err` value: TypeMismatch { expected: "[ONLY ON NIGHTLY]", found: "[ONLY ON NIGHTLY]" }'

Following the code:

```rust
use mockall::*;

trait Bar {
    const BAZ: &'static str;
}

impl Bar for i32 {
    const BAZ: &'static str = "BAZ/i32";
}

impl Bar for u32 {
    const BAZ: &'static str = "BAZ/u32";
}

trait Foo {
    fn foo<T: Bar + 'static>(&self) -> &'static str;
}

mock! {
    MyStruct {}
    impl Foo for MyStruct {
        fn foo<T: Bar + 'static>(&self) -> &'static str;
    }
}

#[test]
fn generic_only() {
    let mut mock = MockMyStruct::new();
    mock.expect_foo::<i32>().return_const("foo/i32");
    mock.expect_foo::<u32>().return_const("foo/u32");
    assert_eq!("foo/i32", mock.foo::<i32>());
    assert_eq!("foo/u32", mock.foo::<u32>());
}

#[test]
fn regular_impl() {
    struct RegularFoo {}
    impl Foo for RegularFoo {
        fn foo<T: Bar>(&self) -> &'static str {
            T::BAZ
        }
    }

    let regular_foo = RegularFoo {};
    assert_eq!("BAZ/i32", regular_foo.foo::<i32>());
    assert_eq!("BAZ/u32", regular_foo.foo::<u32>());
}
```

**Comment by asomers** [comment]
Wow!  That bug title's a mouthful.  First of all, your panic message will be more informative if you build mockall with the `nightly` crate feature.  Secondly, from Mockall's perspective that method isn't really generic at all.  So the fact that `mock.expect_foo::<T>` even compiles indicates a bug.  The expectation should be concrete.  I'll fix it.

**Comment by asomers** [comment]
@twz123 could you please test your application using Mockall at 274a539da71634b14310df1fce7dfeefdc4b4d1e ?  And `expect_foo` isn't concrete after all; it should be generic just the way you wrote it.

**Comment by twz123** [comment]
@asomers Works as expected! Thanks for fixing :+1:
