### ISSUE TITLE
Documentation example fails

### ISSUE THREAD

**Issue by jonnius** [asomers/mockall#270]
I need to create a mocked struct implementing a specific trait. The first example in [mock documentation](https://docs.rs/mockall/0.9.1/mockall/macro.mock.html#examples) looks like what I need, but it results in a compiler error:
```rust
error: expected `trait`
  --> src/arm/control.rs:94:9
   |
94 |         impl Foo for MyStruct {
   |         ^^^^
```

I am using stable Rust 1.47.0.

Update: this fails on current nightly, too.

**Comment by asomers** [comment]
That syntax requires Mockall 0.9.0 or newer.  What version are you using?

**Comment by jonnius** [comment]
True, I was still with 0.8. Thanks for the fast reply!
