### ISSUE TITLE
Macro expansion for generic trait function

### ISSUE THREAD

**Issue by crocme10** [asomers/mockall#277]
Hello,

Thank you for your project, which I am trying to add to my project. I have bumped on a compiler message that I can't find a solution to, and I am wondering if you could help me.
I have created a test case here: https://github.com/crocme10/test-mockall
The program runs fine (`cargo build --release`)
But if i try to use `automock` on the `Generic` trait, I get a message about `adding an explicit lifetime bound`. But is that really necessary?

Here is the trait definition:

```rust
// This trait is not object safe.
#[async_trait]
// #[mockall::automock]
trait Generic {
    async fn generic_fn<S>(&self, mut stream: S) -> Result<i32, std::io::Error>
    where
        S: Stream<Item = i32> + Send + Sync + Unpin;
}
```

Thank you for your suggestion

**Comment by asomers** [comment]
Yes, the lifetime bound really is necessary, because of all the stuff that Mockall does under the hood.  You should add `S: 'static`.  

Also, you should reconsider using `&self` in an `async fn`.  The returned future will capture the lifetime of `&self`, which is rarely what you want.

**Comment by asomers** [comment]
Oh, I just noticed another problem.  `automock` must appear above `async_trait`.  It won't work if you do it the other way.

**Comment by crocme10** [comment]
Thank you for your prompt response. I will consider the use of `&self` in an `async fn`, and see if it resolves my issue.

**Comment by asomers** [comment]
Closing under the assumption that no news is good news.

**Comment by crocme10** [comment]
:+1:
