### ISSUE TITLE
Create new_mock() method alongside new() method

### ISSUE THREAD

**Issue by bhumlie** [asomers/mockall#278]
The fact that mocking a struct with its own new method removes the mock creation new method makes working with those structs very annoying. I propose creating an extra method in the mock class that is new_mock() or a similar form to allow testing using mocked structs that contain their own new implementation.

**Comment by asomers** [comment]
Are you aware that mockall creates a `default` method that you can use even if your struct has its own `new` method?

**Comment by bhumlie** [comment]
I was not. I did look thru the generated documentation for such a method but must have overlooked it. Thanks for letting me know. Would it be worth adding to the documentation on new? When new is generated it mentions in its doc that it is not generated if a new exists.
