### ISSUE TITLE
Cannot mock a method returning a reference to !Send.

### ISSUE THREAD

**Issue by farmaazon** [asomers/mockall#281]
Having the following code
```rust
struct StatusNotifications;

#[automock]
pub trait API {
    fn status_notifications(&self) -> &Rc<StatusNotifications>;
}
```
I cannot set-up an expectation for the method, because in case of methods returning references I can only `return_const`: I have no `return_const_st` nor `returning_st`. 

I can do this with mutable references, however it does not fit my case, where I have the struct implementing the API trait often wrapped in Rc.

**Comment by asomers** [comment]
`return_const` should work, as it does not require `Send`.  Can you please show me your test method, with the compiler error you get?

**Comment by asomers** [comment]
Closing for lack of feedback.
