### ISSUE TITLE
Problems with expectation code lifetimes when mocking an async traid

### ISSUE THREAD

**Issue by alvico** [asomers/mockall#282]
I have the following scenario:

```
#[async_trait]
pub trait TopicRepository {
    fn metadata(&self) -> Vec<TopicConfig>;
    async fn bach_create<'a>(&self, topics_configs: &Vec<(&'a TopicConfig, i32)>) -> KafkaResult<Vec<TopicResult>>;
}
```

```
#[cfg(test)]
mock! {
    pub TopicRepository {}
    #[async_trait]
    impl TopicRepository for MockTopicRepository {
        fn metadata(&self) -> Vec<TopicConfig>;
        async fn bach_create<'a>(&self, topics_configs: &Vec<(&'a TopicConfig, i32)>) -> KafkaResult<Vec<TopicResult>>;
    }
}
```

And when I do my test I do the following one:

```
#[test]
    fn on_topic_in_config_and_not_in_kafka_topic_is_created(){
        env::set_var("KAFKA_TOPICS_REPLICATION_FACTORS", "default:1");
        let mut repo = mock_repository_with_metadata(vec![
            vec![TopicConfig::build("topic1".to_string(), 1)],
            vec![TopicConfig::build("topic3".to_string(), 2)],
            vec![TopicConfig::build("topic2".to_string(), 3)],
        ]);
    
        let topic_config: TopicConfig = TopicConfig {
            name: "topic1".to_string(),
            partitions: 1,
            retention_policy: Some("delete".to_string()),
            retention_size_in_mb: Some(10000),
            retention_time_in_hours: Some(720),
        };
        let topics:Vec<(&TopicConfig, i32)> = vec![(&topic_config, 1 as i32)];
        repo.expect_bach_create().with(&topics).times(1);
        task::block_on(create_missing_topics(&repo, &vec![topic_config.clone()]));
  }
```

The problem relays in the test with the with, the expectation it creates does not share the expect type defined in the mocked trait. 

It complains with the following error which I'm unsure how to circumvent I've tried quite some approaches but I'm still quite new to rust so got lost with it. But reading the issues it seems it might be related to  [#75](https://github.com/asomers/mockall/issues/75#issuecomment-566876462)

the trait bound` for<'a> &Vec<(&configuration::TopicConfig, i32)>: Predicate<Vec<(&'a configuration::TopicConfig, i32)>>` is not satisfied 
the trait` for<'a> Predicate<Vec<(&'a configuration::TopicConfig, i32)>>` is not implemented for `&Vec<(&configuration::TopicConfig, i32)>`

I apologize if this is not an issue from mockall rather me doing it wrong, as said I'm a bit new to the language and still struggling with it.

**Comment by asomers** [comment]
That's not the way that `with` works.  It expects an object that implements the [Predicate](https://docs.rs/mockall/0.9.1/mockall/trait.Predicate.html) trait.  If you look at the examples, they mostly look like `with(eq(5))`.  That `eq` is a function that returns a `Prediate`.  It seems to me that this is what you're intending to do.  However, it's tricky to work with non-`'static` `Predicate`s.  That's why it's often easier to use `withf`, which takes a function which will evaluate the argument.
