### ISSUE TITLE
Mock Struct with Mult implementation

### ISSUE THREAD

**Issue by manuel-leveugle** [asomers/mockall#285]
Hello, I have a question.

I have this code structure and, when i use impl Debug + impl Display in macro 'mock!'. I get this error:  
`duplicate definitions with name 'expect_fmt'`  
`duplicate definitions for 'expect_fmt'`  

``` Rust
// mod.rs
mod implementation;
mod implementation_clone;
mod implementation_debug;
mod implementation_display;
mod implementation_partial_eq;
mod implementation_my_traits;

pub struct MyStruct {
  /* Some fields */
}

mock! {
  pub MyStruct {
    /* Some pub method in file "implementation.rs" */
  }

  impl Clone for MyStruct {
    fn clone(&self) -> Self;
  }

  impl Debug for MyStruct {
    fn fmt<'a>(&self, formatter: &mut Formatter<'a>) -> FmtResult;
  }

  impl Display for MyStruct {
    fn fmt<'a>(&self, formatter: &mut Formatter<'a>) -> FmtResult;
  }

  impl PartialEq for MyStruct {
    fn eq(&self, other: &MockMyStruct) -> bool;
  }

  impl MyTraits for MyStruct {
    /* Some method in my traits */
  }
}
```
``` Rust
// implementation.rs
impl MyStruct {
  /* Some methods */
}

/* Some Tests */
```
``` Rust
// implementation_clone.rs
impl Clone for MyStruct {
  fn clone(&self) -> Self { /* Some actions */ }
}

/* Some Tests */
```
``` Rust
// implementation_debug.rs
impl Debug for MyStruct {
  fn fmt<'a>(&self, formatter: &mut Formatter<'a>) -> FmtResult { /* Some actions */ }
}

/* Some Tests */
```
``` Rust
// implementation_display.rs
impl Display for MyStruct {
  fn fmt<'a>(&self, formatter: &mut Formatter<'a>) -> FmtResult { /* Some actions */ }
}

/* Some Tests */
```
``` Rust
// implementation_partial_eq.rs
impl PartialEq for MyStruct {
  fn eq(&self, other: &MockMyStruct) -> bool { /* Some actions */ }
}

/* Some Tests */
```
``` Rust
// implementation_my_traits.rs
impl MyTraits for MyStruct {
  /* Some method in my traits */
}

/* Some Tests */
```
How can I implement Display and Debug at the same time in MockStruct please?  
Thanks you for you're help :D

**Comment by asomers** [comment]
Easy: manually implement those traits.  What you're doing, by putting Debug and Display within the `mock!`, is creating mock methods named `fmt`, which will panic if anything calls them without appropriate expectations set.  But that's probably not what you really want, especially for Debug.  So do it like this:
```rust
mock!{
    MyStruct {}
}
impl Debug for MockMyStruct {
  fn fmt<'a>(&self, formatter: &mut Formatter<'a>) -> FmtResult {
    /* Some actions.  "nothing" would be acceptable here. */
  }
}
```

**Comment by manuel-leveugle** [comment]
Thanks you for you're reactivity.
I understand. It is true that Debug should never panic. I implement it outside.
On the other side, the implementation of Display traits, I wish to be able to mock it, because in my code I sometimes do this:
``` Rust
format!("str...{}...str", my_struct);
```

It's ok if i do like this :
``` Rust
mock!{
  MyStruct {}

  impl Display for MyStruct{
    fn fmt<'a>(&self, formatter: &mut Formatter<'a>) -> FmtResult;
  }
}
impl Debug for MockMyStruct {
  fn fmt<'a>(&self, formatter: &mut Formatter<'a>) -> FmtResult {
    /* Some actions. */
  }
}
```

**Comment by asomers** [comment]
Yes, it's ok to do it the way you showed.  As for the next question, it's fine to derive Debug for `MyStruct`, but that won't have any effect on `MockMyStruct`.

**Comment by manuel-leveugle** [comment]
Precisely, I would like to know if it is possible to use #[derive(Debug)] (or something like that) for MockMyStruct

**Comment by asomers** [comment]
Try it, but I don't think it will work.  It would probably be a good thing to add, though.  Mockall should probably just implement Debug for all mock structs.

**Comment by manuel-leveugle** [comment]
I confirm it does not work.
Indeed, implementing Debug by default would be okay. I let you judge the usefulness. I'm not good enough at Rust at the moment to suggest a change to your Library.

I still have a little trouble with the fact that a mocked structure has no attributes, but otherwise I can confirm that your library is very powerful.

**Comment by asomers** [comment]
No attributes?  What do you mean by that?

**Comment by manuel-leveugle** [comment]
Access to fields in struct like this
``` Rust
pub MyStruct {
  pub field_a: String;
}

#[automock]
impl MyStruct {}

#[test]
fn test() {
  let mut my_struct: MockMyStruct = MockMyStruct{ field_a: "Field a".to_string() }

  assert_eq:("Field a".to_string(), my_struct.field_a);
}
```

**Comment by asomers** [comment]
Oh that.  Yes, Mockall certainly does not let you do that.  You have to use accessor methods, as you've discovered.

**Comment by manuel-leveugle** [comment]
Overall, this library is very well done. As we could discuss, You should implement automatically some very often used but still generic traits, like 'Debug, Clone, PartialEq'.

**Comment by asomers** [comment]
I don't think Mockall should derive Clone.  Because if it did, what would happen to a mock's expectations when it got cloned?  Would the clone share the same expectations or get a blank slate?  It's unclear.  So it's best to handle Clone the normal way.
Similarly with PartialEq.  What would be the basis for comparison?  It can't be derived, because the mock won't contain the same fields as the regular structure.  No, any mock needing to implement PartialEq will have to do it manually.
But Debug, yeah.  I can't come up with any good reasons not to automatically implement that one.
