### ISSUE TITLE
Mock unsafe traits

### ISSUE THREAD

**Issue by C0D3-M4513R** [asomers/mockall#305]
I have been wanting to program something ui, with rust.
I have been using vulkano and winit.

I now want to add a unit-test.  The Window creation boils down, to implementing this trait:
[link](https://github.com/rust-windowing/raw-window-handle/blob/cb628db982201c4c6a97ea56fb117e739cbc9c38/src/lib.rs#L52)
```rust
pub unsafe trait HasRawWindowHandle {
    fn raw_window_handle(&self) -> RawWindowHandle;
}
```

I am trying, to mock this, by doing the following:
```rust
        mock! {
            Window{}
            unsafe impl raw_window_handle::HasRawWindowHandle for Window{
                fn raw_window_handle(&self) -> raw_window_handle::RawWindowHandle;
            }
        }
```
The compiler just says the following: ```error[E0200]: the trait `HasRawWindowHandle` requires an `unsafe impl` declaration```
I thought, that I specified unsafe impl ? Is this supported?

EDIT: The unsafe in the mock! macro is ignored when the macro expands.

**Comment by asomers** [comment]
I think this should be pretty easy to support.
