### ISSUE TITLE
[bug] Rust docs incorrectly conflate `.times(1)` and `.once()`

### ISSUE THREAD

**Issue by ltchang2019** [asomers/mockall#321]
**Semantic bug between `.once()` and `.times(n)`**

The [.once() docs](https://docs.rs/mockall/0.10.2/mockall/examples/__mock_MockFoo_Foo/__foo/struct.Expectation.html#method.once) say `.once()` expects the function to be called "exactly once" but also says that it is a"shortcut for times(1)."

The [.times(n) docs](https://docs.rs/mockall/0.10.2/mockall/examples/__mock_MockFoo_Foo/__foo/struct.Expectation.html#method.times) say `.times(n)` "restrict[s] the number of times that that this method may be called." A `.times(1)` expectation will therefore pass for either 0 or 1 calls, which is inconsistent with the statement about `.once()` expecting the function to be called "exactly once".

Removing the part about `.once()` being an expectation for "exactly once" and unit testing the two functions (times and once) on the `Expectation` struct should clear up any confusion.

**Comment by asomers** [comment]
No, the docs are correct.  See https://github.com/asomers/mockall/blob/66d9934761eba7ae3a00582fa3f66fb049f5f48f/mockall_derive/src/mock_function.rs#L1008 .  And `.times(1)` requires the method to be called exactly 1 time, not either 0 or 1 times.  Why do you think otherwise?

**Comment by asomers** [comment]
Closing this issue as invalid.  I'm not sure what doc change could make it clearer.
