### ISSUE TITLE
Error when using Rust plugin with CLion/IntelliJ

### ISSUE THREAD

**Issue by krojew** [asomers/mockall#329]
Sorry if this should be reported to Rust plugin, but maybe it's a problem in the crate. When using the `mock!` macro to create a mock for a trait, every parameter to each function reports an error in the IDE (but builds nevertheless):

> `MaybeDebugger<Type>` doesn't implement `Debug` (required by {:?})

**Comment by asomers** [comment]
If your crate actually builds, then this must be a problem in the IDE.  I'm going to close this issue, but you can reopen it if you can demonstrate a bug that independent of the IDE.
