### ISSUE TITLE
Possibility to check that no method was called

### ISSUE THREAD

**Issue by Arjentix** [asomers/mockall#335]
Hello!
I just wanted to test, that my function doesn't call any method from mock, if something went wrong.
I could do this using a lot of `expect_something().times(0)`, but this is gonna be outdated every time I add/remove method to/from original struct.
So it would be cool, if you implemented it!

**Comment by asomers** [comment]
You don't need to do anything.  By default methods have no expectations, so they'll panic with "no matching expectation found" if you try to call them.

**Comment by Arjentix** [comment]
Oh, yeah, it works! Sorry, I haven't seen any information about this feature
