### ISSUE TITLE
Many "unused imports" warning occurs

### ISSUE THREAD

**Issue by ulwlu** [asomers/mockall#343]
thank you for this great library.

v0.10.2

Like example below,

```rust
#[mockall::automock]
pub mod forms {
    use std::convert::TryInto;

    pub async fn hoge() -> Hoge {
        let row = sth...
        Ok(row.try_into()?)
    }
}
```

In this case, TryInto surely is used but warns `unused imports`. Not only this, but also like below.

```rust
#[mockall::automock]
pub mod forms {
    use crate::{a, b}; // <- b occurs unused imports
    use crate::hoge::somepubfunction; // <- occurs
}
```

I think this related to https://github.com/asomers/mockall/pull/54/files, but I can't find where to fix.

**Comment by ulwlu** [comment]
Ah yes that's what I'm doing currently with allow unused_imports.

Thank you for replying. It will be great if that causes no warning without suppressing.

**Comment by asomers** [comment]
@ulwlu could you please test your crate against the branch in the linked PR?

**Comment by ulwlu** [comment]
Sure, now I am working but will try in a day.

**Comment by ulwlu** [comment]
@asomers 

I tried with the cargo.toml below, and all errors are gone! thx!!!

```
mockall = { git = "https://github.com/asomers/mockall", branch = "unused-warnings"}
```

**Comment by ulwlu** [comment]
@asomers

Hi do you plan to release this one in next version...?
I'm fine with this specifiying in Cargo.toml, but hopefully i would love to see if you can release next patch version soon.....

**Comment by asomers** [comment]
@ulwlu done!

**Comment by ulwlu** [comment]
Thank you very much!! And thank you for this great mocking library again.
