### ISSUE TITLE
allow `impl Struct` inside `mock!`

### ISSUE THREAD

**Issue by kylezs** [asomers/mockall#367]
I think there's currently a limitation here. Please let me know if there is currently a solution / workaround to do this.

Currently, any derive macros like `Clone` (except `Debug` which is mentioned explicitly in the docs), in order to be applied to the mock struct, they must go inside a `mock!()` block. 

However, `mock!()` does not allow for mocking the struct's `impl` block. You can only mock trait implementations. 

And so in the case that I have:

```rust
#[derive(Clone)]
struct MyStruct {}

impl MyStruct {
  fn do_stuff(&self) { .. }
}
```

I cannot mock it correctly, since I cannot mock `impl MyStruct` without losing `Clone`, or I can't add `Clone` to the mock if I mock the `impl` (with `automock`)

**Comment by asomers** [comment]
That's not correct.  `mock!` isn't just for traits.  It does inherent methods do.  The struct's inherent methods go above the first `impl` block.  In the first example (https://docs.rs/mockall/latest/mockall/macro.mock.html#examples), `MyStruct::bar` is a struct's inherent method.
Secondly, whether using `#[automock]`, or `mock!`, there's no way to derive `Clone`.  So if you need your mock objects to be `Clone`, you'll have to do it like this:
```rust
mock! {
    MyStruct {
        fn do_stuff(&self);
    }
    impl Clone for MyStruct {
        fn clone(&self) -> Self ;
    }
}
```
