### ISSUE TITLE
The example under #external-traits does not work

### ISSUE THREAD

**Issue by Jupp56** [asomers/mockall#368]
The following code, taken almost directly from the example https://docs.rs/mockall/latest/mockall/#external-traits, does not compile:
`#[cfg(test)]
mod tests {
    use mockall::mock;

    #[test]
    fn test() {
        mock! {
            MyStruct {}     // Name of the mock struct, less the "Mock" prefix
            impl Clone for MyStruct {   // specification of the trait to mock
                fn clone(&self) -> Self;
            }
        }
    }
}`

The cargo test - output:

error[E0412]: cannot find type `MockMyStruct` in this scope
 --> src\lib.rs:8:13
  |
8 |             MyStruct {}     // Name of the mock struct, less the "Mock" prefix
  |             ^^^^^^^^ not found in this scope

error[E0282]: type annotations needed
  --> src\lib.rs:7:9
   |
7  | /         mock! {
8  | |             MyStruct {}     // Name of the mock struct, less the "Mock" prefix
9  | |             impl Clone for MyStruct {   // specification of the trait to mock
10 | |                 fn clone(&self) -> Self;
11 | |             }
12 | |         }
   | |_________^ cannot infer type
   |
   = note: type must be known at this point
   = note: this error originates in the macro `mock` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `returning` found for mutable reference `&mut Expectation` in the current scope
  --> src\lib.rs:7:9
   |
7  | /         mock! {
8  | |             MyStruct {}     // Name of the mock struct, less the "Mock" prefix
9  | |             impl Clone for MyStruct {   // specification of the trait to mock
10 | |                 fn clone(&self) -> Self;
11 | |             }
12 | |         }
   | |_________^ method not found in `&mut Expectation`
   |
   = note: `mock! {
                       MyStruct {}     // Name of the mock struct, less the "Mock" prefix
                       impl Clone for MyStruct {   // specification of the trait to mock
                           fn clone(&self) -> Self;
                       }
                   }` is a function, perhaps you wish to call it
   = note: this error originates in the macro `mock` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `clone` found for type parameter `MockallOutput` in the current scope
  --> src\lib.rs:7:9
   |
7  | /         mock! {
8  | |             MyStruct {}     // Name of the mock struct, less the "Mock" prefix
9  | |             impl Clone for MyStruct {   // specification of the trait to mock
10 | |                 fn clone(&self) -> Self;
11 | |             }
12 | |         }
   | |_________^ method not found in `MockallOutput`
   |
   = note: `mock! {
                       MyStruct {}     // Name of the mock struct, less the "Mock" prefix
                       impl Clone for MyStruct {   // specification of the trait to mock
                           fn clone(&self) -> Self;
                       }
                   }` is a function, perhaps you wish to call it
   = help: items from traits can only be used if the type parameter is bounded by the trait
   = note: this error originates in the macro `mock` (in Nightly builds, run with -Z macro-backtrace for more info)
help: the following trait defines an item `clone`, perhaps you need to restrict type parameter `MockallOutput` with it:
   |
7  |         MockallOutput: Clone
   |

error[E0599]: no method named `returning_st` found for mutable reference `&mut Expectation` in the current scope
  --> src\lib.rs:7:9
   |
7  | /         mock! {
8  | |             MyStruct {}     // Name of the mock struct, less the "Mock" prefix
9  | |             impl Clone for MyStruct {   // specification of the trait to mock
10 | |                 fn clone(&self) -> Self;
11 | |             }
12 | |         }
   | |_________^ method not found in `&mut Expectation`
   |
   = note: `mock! {
                       MyStruct {}     // Name of the mock struct, less the "Mock" prefix
                       impl Clone for MyStruct {   // specification of the trait to mock
                           fn clone(&self) -> Self;
                       }
                   }` is a function, perhaps you wish to call it
   = note: this error originates in the macro `mock` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `lock` found for struct `Mutex<Rfunc>` in the current scope
  --> src\lib.rs:7:9
   |
7  | /         mock! {
8  | |             MyStruct {}     // Name of the mock struct, less the "Mock" prefix
9  | |             impl Clone for MyStruct {   // specification of the trait to mock
10 | |                 fn clone(&self) -> Self;
11 | |             }
12 | |         }
   | |_________^ method not found in `Mutex<Rfunc>`
   |
   = note: the method was found for
           - `Mutex<T>`
   = note: `mock! {
                       MyStruct {}     // Name of the mock struct, less the "Mock" prefix
                       impl Clone for MyStruct {   // specification of the trait to mock
                           fn clone(&self) -> Self;
                       }
                   }` is a function, perhaps you wish to call it
   = note: this error originates in the macro `mock` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0282, E0412, E0599.
For more information about an error, try `rustc --explain E0282`.
error: could not compile `mock_test` due to 6 previous errors

**Comment by Jupp56** [comment]
Btw: Why github formats it like that - i dont know.

**Comment by Jupp56** [comment]
Im on Windows with the following config: Mockall 0.11.0, stable-x86_64-pc-windows-msvc (default), rustc 1.59.0 (9d1b2106e 2022-02-23)

**Comment by asomers** [comment]
First of all, if you're going to type a block quote into Github, you should use triple backticks.  https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.

Secondly, your problem is that you're trying to declare your mock object with function scope.  But it needs global scope.  Just move the `mock!` part out of the `fn test(){...}` part.

**Comment by Jupp56** [comment]
> First of all, if you're going to type a block quote into Github, you should use triple backticks. https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.
> 
> Secondly, your problem is that you're trying to declare your mock object with function scope. But it needs global scope. Just move the `mock!` part out of the `fn test(){...}` part.

Thanks for the quick response. Triple Backticks make everything worse, though, as you can see... The documentation maybe could be a bit more explicit about that-  in the referenced example, there are trait declarations, the macro, and actual code right beside each other without any function in sight.

**Comment by asomers** [comment]
You need to put the triple backticks on their own line.  Sorry about the confusion in the example.  I suppressed the display of the function declaration boilerplate because I thought it just obscured the important parts.
