### ISSUE TITLE
Problem mocking structs with lifetimes

### ISSUE THREAD

**Issue by pilotniq** [asomers/mockall#376]
The following code gives me an error "use of undeclared lifetime" (E0261) on the `impl <'a> Transaction<'a>` line.

Is there a way to mock structures like Transaction (that have lifetimes)?

    use mockall::automock;

    pub struct Transaction<'a> {
        n: &'a usize,
    }

    #[automock]
    impl <'a> Transaction<'a> {
        #[allow(dead_code)]
        pub fn new(n: &'a usize) -> Self {
            Transaction { n }
        }
    }

    pub struct Database {
        n: usize
    }

    impl Database {
        #[allow(dead_code)]
        pub fn new() -> Self {
            Database { n: 1_usize }
        }

        pub fn make_transaction(&self) -> Transaction<'_> {
            Transaction::new(&(self.n))
        }
    }

**Comment by asomers** [comment]
I suggest that you mock this one with `mock!` instead of `#[automock]`.  That way you can make the mock version `'static`.

**Comment by pilotniq** [comment]
Thanks for the reply!

I've tried using `mock!`, but I don't understand how to do it.

Am I correct that I need to define a trait in order to use `mock!`?

If I try to do something like:

    trait TransactionTrait<'a> {
          fn new(n: &'a usize) -> Self;
    }
    mock! {
      pub Transaction<'a> {
      }

      impl <'a> TransactionTrait<'a> for Transaction<'a> {
           pub fn new(n: &'a usize) -> Self;
      }
    }

Then I get an error inside the `mock!`: on the `pub Transaction<'a> {` line: _'a undeclared lifetime._
If I put `'_` instead of `'a` on that line, I get: _\'\_:\_ expected named lifetime parameter_
If I put `'_static`, I get: error _'static is a reserved lifetime name"_
if I put nothing there, I get an error on the `impl <'a> TransactionTrait<'a> for Transaction<'a> {`-line saying _expected 0 lifetime arguments"_

I'm afraid I'm a beginner at Rust. I'd appreciate a simple example of how to mock the struct with `mock!`!
