### ISSUE TITLE
Problem Mocking Structs With Internal Values

### ISSUE THREAD

**Issue by dawsonfi** [asomers/mockall#377]
The following code gives me an error "struct `MockFoo` has no field named `value`".

Is there a way to avoid this problem that doesn't involve creating a trait?

```
use mockall_double::double;

mod thing {
    use mockall::automock;
    pub struct Foo {
        pub value: i32
    }

    #[automock]
    impl Foo {
        pub fn run() {
            println!("Hello, world@")
        }
    }
}

#[double]
use thing::Foo;

pub struct Bar {
    foo: Foo
}

impl Bar {
    pub fn new() -> Bar {
        Bar {
            foo: Foo { value: 32 }
        }
    }
}
```

**Comment by asomers** [comment]
There's no good way to mock accesses to an object's fields. And it's especially impossible to construct a mock object from its fields, as you're trying to do. Instead, create a constructor method. That's mockable.

**Comment by dawsonfi** [comment]
Hi @asomers, thanks for the help. I've tried your suggestion and it solved the original issue, but created another one:

It now give me "mismatched types expected struct `MockFoo`, found struct `thing::Foo`" on Bar constructor.

Is there a way to apply the `double` logic on the constructor as well?

```rust
use mockall_double::double;

mod thing {
    use mockall::automock;
    pub struct Foo {
        pub value: i32
    }

    #[automock]
    impl Foo {
        pub fn new() -> Foo {
            Foo { value: 0 }
        }

        pub fn run() {
            println!("Hello, world@")
        }
    }
}

#[double]
use thing::Foo;

pub struct Bar {
    foo: Foo
}

impl Bar {
    pub fn new() -> Bar {
        Bar {
            foo: Foo::new() // mismatched types expected struct `MockFoo`, found struct `thing::Foo`
        }
    }
}
```

**Comment by asomers** [comment]
Instead of `pub fn new() -> Foo`, try `pub fn new() -> Self`.

**Comment by dawsonfi** [comment]
Awesome, w
orked like a charm :)Thanks for the help @asomers.

Do you think we could modify the docs to include this field and help other people avoiding this same problem? I can submit a PR if you want to.

**Comment by asomers** [comment]
No, I don't think it's necessary.  The docs already contain an example of a constructor method returning `Self`.
