### ISSUE TITLE
Can't mock method returning &'static str

### ISSUE THREAD

**Issue by DGolubets** [asomers/mockall#38]
Hi!
Thanks for the great library!

I have one problem so far.
I'm straggling to mock this method:
``` Rust
fn name(&self) -> &'static str;
```
It seems like it wants me to supply it with &'static String which is hard to construct (I end up using lazy_static).

**Comment by asomers** [comment]
Hm, there's special code to handle types that implement `Deref` (like `String`), and special code for `&'static` references.  It looks like they're colliding.  I'll fix it.
