### ISSUE TITLE
Mocking `impl<Generic> Struct<Generic> {}` panic: Mock::new(): No matching expectation found

### ISSUE THREAD

**Issue by m-kuzmin** [asomers/mockall#383]
I want to mock a cache inside a web client, but I cant do that because at runtime the test panics:
```
---- core::test::should_not_panic stdout ----
thread 'core::test::should_not_panic' panicked at 'MockCache::new(): No matching expectation found', src/core/test.rs:8:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
### Usecase
```rust
struct WebClient {
    cache: WebCache<String, String>,
}
```

### Cache
```rust
use std::collections::HashMap;
pub struct Cache<T, U>(HashMap<T, U>);
```
### Mocking code
```rust
#[cfg_attr(test, double)]
use Cache as WebCache;

#[cfg_attr(test, automock)]
impl<T, U> Cache<T, U>
where
    T: 'static,
    U: 'static,
{
    pub fn new() -> Self {
        Self(HashMap::new())
    }
}

#[test]
fn should_not_panic() {
    let cache = WebCache::<String, String>::new();
}
```
Code above as a file: [sample.rs](https://github.com/asomers/mockall/files/8688135/sample.txt)

**Comment by asomers** [comment]
The problem is simple: you never set an expectation on the `new` method.  If you want a mock object that has no expectations already set, use `WebCache::default()`.  Otherwise, set an expectation on `new`.

**Comment by m-kuzmin** [comment]
Well, actually I just want to create an object of type (Mock)`WebCache` and then add `expect_get()` for example. How should I create the object then?

**Comment by m-kuzmin** [comment]
So something like this works for `mock_client` but not `mock_cache`
```rust
 let mut mock_cache = WebCache::<Link, String>::new();
 let mut mock_client = Client::new();
 let mut seq = Sequence::new();

mock_cache
    .expect_get()
    .times(1)
    .in_sequence(&mut seq)
    .with(eq((String::from("https://test.com"), None)))
    .returning(|_| None);

mock_client
    .expect_get()
    .times(1)
    .in_sequence(&mut seq)
    .with(eq("https://test.com"))
    .returning(|_| {Some(...)});
```
And the object panics on line with `#[automock]`

**Comment by asomers** [comment]
> Well, actually I just want to create an object of type (Mock)`WebCache` and then add `expect_get()` for example. How should I create the object then?

Like I said, with `WebCache::default()`

**Comment by m-kuzmin** [comment]
That solves it. Thank you for the quick response.
