### ISSUE TITLE
feat: allow detailed expection failure output on non-nightly Rust

### ISSUE THREAD

**Issue by justahero** [asomers/mockall#412]
When mocking a trait using `automock` a failing expectation displays `(?)` instead of the given function arguments.

For example:

```rust
use mockall::{automock, predicate::*};

#[automock]
trait System {
    fn foo(&self, input: &str) -> u32;
}

#[test]
fn mytest() {
    let mut mock = MockSystem::new();
        mock.expect_foo()
            .with(eq("bar"))
            .times(1);
    mock.foo("baz");
}
```

outputs the failed expectation as

```
thread 'mytest' panicked at 'MockSystem::foo(?): No matching expectation found', src/lib.rs:3:1
```

When using the `nightly` feature & a recent Rust the same code produces the following output.

```
thread 'mytest' panicked at 'MockSystem::foo("baz"): No matching expectation found', src/lib.rs:3:1
```

In a current project the detailed output would help a lot with debugging / understanding, while at the same time we are not able to use Rust nightly. One idea I evaluated is to "guard" this logic behind an argument to the `automock` attribute, for example:

```rust
#[automock(enforce_debug)]
trait System {
    fn foo(&self, input: &str) -> u32;
}
```

Given the flag it would enforce all function arguments to implement `Debug` & output the detailed version. The [`MockFunction::desc`](https://github.com/asomers/mockall/blob/3b8da11f45c54f50b79d9e94bb9b910ddf3b2906/mockall_derive/src/mock_function.rs#L591) function would then decide to format arguments using `{:?}` or the `MaybeDebugger`, depending on the flag.

My question is, do you think it's worth adding an option to enforce the same output for non-nightly Rust code?

**Comment by asomers** [comment]
Not really.  IMHO it seems like a high cost in maintenance for a small benefit, especially when the same result can be achieved by switching to the nightly compiler.

**Comment by justahero** [comment]
Thanks for your feedback!
