### ISSUE TITLE
Concretize doesn't work with cfg_attr

### ISSUE THREAD

**Issue by asomers** [asomers/mockall#427]
The `#[concretize]` attribute isn't processed as a real Rust attribute.  It's processed as text by Mockall, and used as a directive to tell it how to mock something that's already being mocked.  That's why it must be used with its canonical name; you can't do `use mockall::concretize as something_else`.
But as of this writing, Mockall doesn't process the text correctly if it appears within a `cfg_attr` directive.  Instead, it passes it through in the emitted code, causing various compile failures.  This example will trigger the problem.
```rust
use std::path::Path;

#[cfg(test)]
use mockall::{automock, concretize};

#[cfg_attr(test, automock)]
trait Foo {
    #[cfg_attr(test, concretize)]
    fn foo<P: AsRef<Path>>(&self, p: P);
}
```
First reported as https://github.com/asomers/mockall/pull/408#issuecomment-1312794561 .

**Comment by asomers** [comment]
@cjriches this should be fixed now.

**Comment by cjriches** [comment]
Thanks! Yup, seems to work now.

**Comment by horacimacias** [comment]
I'm trying to use this but if I understand correctly this `concretize` is on a non-released version of mockall.
Any idea when a new release containing concretize will be available?

**Comment by asomers** [comment]
I've held off from releasing it because it's a big change, not just to the implementation but to the API.  And it's a weird change, too.  I haven't heard much feedback about it.  Why don't you try it out, on the master branch, and let me know how it works for you?

**Comment by horacimacias** [comment]
sure, let me give it a try. thanks!
