### ISSUE TITLE
Duplicate definition for a generated mock function

### ISSUE THREAD

**Issue by altonen** [asomers/mockall#435]
Hi, I can't find any issue referencing this problem/relevant documentation so I'll create a new issue. I'm using `mockall` to generate mocks for an object that implements multiple different traits. These traits have functions with same names in them and `mockall` fails with the following error:

```
error[E0592]: duplicate definitions with name `expect_status`
  --> src/main.rs:12:1
   |
12 | / mockall::mock! {
13 | |     pub Test {}
14 | |
15 | |     impl Trait1 for Test {
...  |
23 | |     }
24 | | }
   | | ^
   | | |
   | |_duplicate definitions for `expect_status`
   |   other definition for `expect_status`
   |
   = note: this error originates in the macro `mockall::mock` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Basically both traits have a function call `status()` and using `mockall::mock!` to generate the mocks fails because there is a conflict in name and the library generates `expect_status()` twice.

```rust
trait Trait1 {
    fn status(&self);
    fn func1(&self);
}

trait Trait2 {
    fn status(&self);
    fn func2(&self);
}

mockall::mock! {
    pub Test {}

    impl Trait1 for Test {
        fn status(&self);
        fn func1(&self);
    }

    impl Trait2 for Test {
        fn status(&self);
        fn func2(&self);
    }
}
```

Is there any workaround for this that would not require changing existing code?

**Comment by asomers** [comment]
The only workaround is to manually implement one or both of the status methods on the mock object.  You can create a method like `_trait1_status` within `mock1`, and wrap that with the manually implemented method.

**Comment by altonen** [comment]
Thank you for response. Manually implementing one of the traits fixed the problem I was having. I didn't fully understand your proposal though, so I couldn't make the code expect the manually implemented trait implementation because it was not found in `__status::Expectations`. If you could elaborate on how did you get it working so that I could expect on both `status()` functions it would be much appreciated but I'm also happy to close this issue as resolved. Cheers!

**Comment by asomers** [comment]
I'm suggesting something like this:
```rust
mock! {
    pub Test {
        fn __trait1_status(&self);
        fn __trait1_func1(&self);
    }

    impl Trait2 for Test {
        fn status(&self);
        fn func2(&self);
    }
}

impl Trait1 for MockTest {
    fn status(&self) { self.__trait1_status()
    fn func1(&self) { self.__trait1_func1() }
}
```
This way you can still use expectations to drive your tests.

**Comment by altonen** [comment]
That worked perfectly, thank you very much
