### ISSUE TITLE
No override on _expect

### ISSUE THREAD

**Issue by bhoudebert** [asomers/mockall#446]
Hello,

First things first, thanks for your work.

Doing some heavy testing I discover that declaring multiple times in a row the same `_expect_functionA` in a test function will never replace the first one.

```Rust
// 
 mock,expect_g()...
 mock,expect_k()...
 mock,expect_r()...
// some tests
// ...
mock.expect_f().returning(|_| 1)
// ... lots of code in a very complex scenario and condition
mock.expect_f().returning(|_| 2)
// Using mock at this point will never return 2 if f() is called.
```

In my peculiar case the mock contains lots of mock and I play around the mock result to assess all error combination.

Yes, I could create new mock (totally inconvenient, we are talking about lots of combination)
Yes, I could clone the mock at different `valid` phase.

Still, I am wondering if there is a simple way (maybe I missed something) to simply override any previous defined `Expectation`.

Thanks.

**Comment by asomers** [comment]
Are you hoping that the first time your test code calls `f()` it will return `1`, and the second time it will return `2`?  That doesn't happen in your example because by default all mocks are allowed to be called any number of times.  So the first expectation never gets satisfied.  You need to retrict that like this:
```rust
mock.expect_f().times(1).returning(|_| 1);
mock.expect_f().times(1).returning(|_| 2);
```
You may also need to use `Sequence`s to have more control over the order in which the expectations are evaluated.  See the docs for more details.

**Comment by bhoudebert** [comment]
In reality just after the first expect_f let's say I can the real stuff. It works fine, returning 1.
Then I update the mock with 2, recall the real stuff and it is still retuning 1.

Gonna have a look at the Sequence

**Comment by bhoudebert** [comment]
From what I get in the Sequence that would not do any difference than cloning just before setting the value 1, and using the clone  for defining the value 2.  It still is very painful (hard to explain the overall pain without a full concrete example which I cannot fully copy/paste here)

**Comment by asomers** [comment]
It definitely sounds like your problem is caused by not using `times()`.

**Comment by bhoudebert** [comment]
> It definitely sounds like your problem is caused by not using `times()`.

Oh I added times(1) on each and it definitely somehow use the second expectation once it was used, I did not expect this to work like this.

Sounds enough for me, thanks!
