### ISSUE TITLE
Different behavior between mock object and real object with the same code

### ISSUE THREAD

**Issue by dizzy27** [asomers/mockall#453]
code:
```
#[cfg(test)]
mod test {

    use ......

    #[automock]
    trait TestMock {
        fn execute_function();
    }

    struct MyStruct {}
    impl MyStruct {
        pub async fn start<M>(&self)
        where
            M: TestMock + 'static,
        {
            for _ in 0..5 {
                self.mother_function::<M>();
                std::thread::sleep(Duration::from_millis(3000));
            }
        }

        fn mother_function<M>(&self)
        where
            M: TestMock + 'static,
        {
            for _i in 0..3 {
                tokio::spawn(child_function::<M>());
            }
        }
    }

    impl TestMock for MyStruct {
        fn execute_function() {
            block_on(execute_function())
        }
    }

    async fn child_function<M>()
    where
        M: TestMock + 'static,
    {
        M::execute_function()
        // execute_function().await
    }

    async fn execute_function() {
        let data = String::from("test");
        log::info!("{} sleeping", data.clone());
        std::thread::sleep(tokio::time::Duration::from_millis(1000));
        log::info!("{} sleeped", data.clone());
    }

    #[tokio::test(flavor = "multi_thread", worker_threads = 8)]
    async fn test_price_feed_test() {
        let env = env_logger::Env::default().filter_or(env_logger::DEFAULT_FILTER_ENV, "info");
        env_logger::Builder::from_env(env).init();

        let t = MyStruct {};
        // t.start::<MyStruct>().await // this will run simultaneously
        // ===================================================================
        // this will not run simultaneously
        let execute_function_ctx = MockTestMock::execute_function_context();
        execute_function_ctx.expect().returning(|| {
            let data = String::from("test");
            log::info!("{} sleeping", data.clone());
            std::thread::sleep(tokio::time::Duration::from_millis(1000));
            log::info!("{} sleeped", data.clone());
        });
        t.start::<MockTestMock>().await
    }
}
```
When using the mock object "MockTestMock", it will not run in threads simultaneously, but real object "MyStruct" with the same code of execute_function.

**Comment by asomers** [comment]
Before I read your entire program to try to understand what's going on, could you please explain the problem more clearly?  State what you expect to happen, what actually happened, and your theory (if any) about the nature of the problem.  And try to use grammatically correct English, as best you can.

**Comment by dizzy27** [comment]
> Before I read your entire program to try to understand what's going on, could you please explain the problem more clearly? State what you expect to happen, what actually happened, and your theory (if any) about the nature of the problem. And try to use grammatically correct English, as best you can.

This piece of code starts multiple threads to perform blocking operations(async fn execute_function()) in parallel. When the code is running without mock object, the blocking operations of these threads can be executed in parallel, but when the same code is executed in the mock object, these threads become serial execution. Here are two different outputs when run normally and when run with a mock object:
---------------use mock object:
```
running 1 test
[2023-02-04T12:47:39Z INFO  test::test] test sleeping
[2023-02-04T12:47:40Z INFO  test::test] test sleeped
[2023-02-04T12:47:40Z INFO  test::test] test sleeping
[2023-02-04T12:47:41Z INFO  test::test] test sleeped
[2023-02-04T12:47:41Z INFO  test::test] test sleeping
[2023-02-04T12:47:42Z INFO  test::test] test sleeped
[2023-02-04T12:47:42Z INFO  test::test] test sleeping
[2023-02-04T12:47:43Z INFO  test::test] test sleeped
[2023-02-04T12:47:43Z INFO  test::test] test sleeping
```
---------------without mock object(only run code "t.start::<MyStruct>().await"):
```
running 1 test
[2023-02-04T12:51:36Z INFO  test::test] test sleeping
[2023-02-04T12:51:36Z INFO  test::test] test sleeping
[2023-02-04T12:51:36Z INFO  test::test] test sleeping
[2023-02-04T12:51:37Z INFO  test::test] test sleeped
[2023-02-04T12:51:37Z INFO  test::test] test sleeped
[2023-02-04T12:51:37Z INFO  test::test] test sleeped
[2023-02-04T12:51:39Z INFO  test::test] test sleeping
[2023-02-04T12:51:39Z INFO  test::test] test sleeping
[2023-02-04T12:51:39Z INFO  test::test] test sleeping
[2023-02-04T12:51:40Z INFO  test::test] test sleeped
[2023-02-04T12:51:40Z INFO  test::test] test sleeped
[2023-02-04T12:51:40Z INFO  test::test] test sleeped
```

**Comment by asomers** [comment]
The `returning` callback executes synchronously and returns immediately.  Returning immediately is valid behavior for an async function.  This is not a problem.  I will note, however, that using a blocking function like `std::thread::sleep` inside of an async function is almost never a good idea.  Presumably you did it in this case just to investigate how Tokio's multithreaded runtime works.  But if not, I suggest you replace it with [`tokio::time::sleep`](https://docs.rs/tokio/latest/tokio/time/fn.sleep.html#) instead.

**Comment by dizzy27** [comment]
> The `returning` callback executes synchronously and returns immediately. Returning immediately is valid behavior for an async function. This is not a problem. I will note, however, that using a blocking function like `std::thread::sleep` inside of an async function is almost never a good idea. Presumably you did it in this case just to investigate how Tokio's multithreaded runtime works. But if not, I suggest you replace it with [`tokio::time::sleep`](https://docs.rs/tokio/latest/tokio/time/fn.sleep.html#) instead.

Okay, thanks.
