### ISSUE TITLE
Question about blanket implementations

### ISSUE THREAD

**Issue by scoolen** [asomers/mockall#465]
Hi. Suppose I have a constraint:

```rust
where:
    T: Foo + Bar
```
And `Bar` has a blanket implementation:

```rust
pub trait Bar: Foo {
    ...
}

impl<T> Bar for T where T: Foo {}
```
How do I mock methods of `Bar`? I tried:
```rust
mock! {
    Thing {}
    impl Foo for Thing {
        fn foo();
    }
    impl Bar for Thing {
        fn bar();
    }
}
```
This leads to
```
= note: conflicting implementation in crate `foo_bar`:
        - impl<T> foo_bar::Bar for T
          where T: Foo;
= note: this error originates in the macro `mock`
```
Omitting the `Bar` implementation leads to an error **`` method not found in `MockThing` ``**

Thanks!

**Comment by scoolen** [comment]
To be less foo-barry, I am trying to mock `GraphCommands` here: https://github.com/tompro/redis_graph/blob/main/src/commands.rs#L27

**Comment by scoolen** [comment]
Thank you. I managed to get it working by indeed removing the `Bar` impl and putting the expectation on one of the `Foo` methods (which was actually called by the `Bar` method I put the expectation originally on).
So this had nothing to do with mockall but was more of a PEBCAK.

**Comment by asomers** [comment]
Glad to help.
