### ISSUE TITLE
Supporting mock with methods that return an object with a generic lifetime? 

### ISSUE THREAD

**Issue by Galgamins** [asomers/mockall#470]
Currently, you cannot use mockall to mock a method with a lifetime parameter where that lifetime is also part of the return type. 

For example

```
pub struct MyStruct<'a>{
    test: &'a u8
}

impl<'a> MyStruct<'a>{
    pub fn create() -> MyStruct<'a>{
        MyStruct{
            test : &0
        }
    }
}
```

If you try to automock this you get an error
use of undeclared lifetime name `'a`

Is this something that can be supported in the future, or is this completely impossible to support?

**Comment by asomers** [comment]
It looks like you're trying to mock a constructor.  The Expectation for a constructor must inherently be `'static`, since it isn't associated with any mock object.  That means that the `returning` closure can't capture any non-`'static` data.  So the best you can do would be to use `mock!` instead of `#[automock]`, and define the mock object's constructor to always return a static struct, like this:
```rust
mock! {
    pub struct MyStruct<'a> {
        pub fn create() -> MyStruct<'static>;
    }
}
```

**Comment by asomers** [comment]
No, not if you don't paste in the error.

**Comment by Galgamins** [comment]
test.rs

```
mock! {

    pub static struct MyStruct<'a> {

        pun fm create() -> MyStruct<'static>;

    }

}
```

```
error: expected identifier

  --> test.rs:16:9

   |

16 |     pub static struct MyStruct<'a> {

   |         ^^^^^^

 error: could not compile `test` due to previous error

```

**Comment by asomers** [comment]
Why did you put that `static` in between `pub` and `struct`?  Are you forgetting that you aren't using C++ anymore?

**Comment by Galgamins** [comment]
Ah oops, yes I did. Though funny enough the same issue happens without the static. 

```
mock! {

    pub struct MyStruct<'a> {

        pub fm create() -> MyStruct<'static>;

    }

}
```


```
error: expected identifier

  --> test.rs:16:9

   |

16 |     pub struct MyStruct<'a> {

   |         ^^^^^^

 error: could not compile `test` due to previous error

```

**Comment by asomers** [comment]
Now get rid of the "struct", like the error suggests.

**Comment by Galgamins** [comment]
Thanks, that solved the problem!
