### ISSUE TITLE
Clippy warning in generated code: too many arguments

### ISSUE THREAD

**Issue by RickySyndica** [asomers/mockall#480]
Perhaps it'd be possible to suppress this in generated code? I have a function with 7 arguments, which becomes 8 when the mock is generated

Thanks!

**Comment by asomers** [comment]
I suppress that warning at the module level.  See https://github.com/asomers/mockall/blob/5938237eb73531283b9d5c2e59b3eaba442fcec1/mockall/tests/automock_many_args.rs#L3 .  I assume you also suppress it somewhere?  I suppose that if you only suppress it on the function that needs it, you'd see this warning for the mock function.  Are you using mock! or automock?  If the latter, than mockall should copy the suppression attribute.

**Comment by asomers** [comment]
I mean, don't you need to add a `#![allow(clippy::too_many_arguments)]` yourself to suppress that warning on the regular object instead of the mock one?

**Comment by asomers** [comment]
Ahh, so this is only really an issue when mocking static functions with exactly 7 arguments?
