### ISSUE TITLE
Support for multiple calls for functions that take no parameters

### ISSUE THREAD

**Issue by QnJ1c2kNCg** [asomers/mockall#481]
After reading this section: https://docs.rs/mockall/latest/mockall/#matching-multiple-calls

It's unclear if there is support to mock multiple calls to the same function, if that function does not take an parameter.

**Comment by asomers** [comment]
Sure there is.  What's your question?  Are you unsure how to order them?  Use a `Sequence`.

**Comment by QnJ1c2kNCg** [comment]
Thanks, this did the trick. Sorry for the trouble.
