### ISSUE TITLE
Integration with googletest?

### ISSUE THREAD

**Issue by mgeisler** [asomers/mockall#490]
Hi there,

I work in Android and we're planning on using the Rust [googletest](https://docs.rs/googletest/) as our default assertion library in Rust (just like we [do in C++](http://google.github.io/googletest/)).

Would it be possible to integrate mockall with googletest? The [gMock](http://google.github.io/googletest/gmock_for_dummies.html) library takes the same matchers as the [`EXPECT_THAT`](http://google.github.io/googletest/reference/assertions.html#EXPECT_THAT) macro, which allows us to reuse things between normal tests and tests that use mocks.

I skimmed the code here a bit and it seems we need to implement [`mockall::Predicate`](https://docs.rs/mockall/latest/mockall/trait.Predicate.html) for [`googletest::matcher::Matcher`](https://docs.rs/googletest/latest/googletest/matcher/trait.Matcher.html).

**Comment by asomers** [comment]
What exactly do you want?  Are you asking to use the same predicates with Mockall's `with` method as with googletest's assertions?

**Comment by mgeisler** [comment]
> Are you asking to use the same predicates with Mockall's `with` method as with googletest's assertions?

Yes, that would be the goal.

It could go in both directions: GoogleTest users could benefit from the predicates written for MockAll, and MockAll users could use matchers written for GoogleTest. If that sounds interesting, I could work on a PR which would add a blanket implementation of `mockall::Predicate` for `googletest::matcher::Matcher`.

**Comment by asomers** [comment]
That does sound potentially interesting.  However, you're looking at the wrong crate.  Mockall reexports Predicates from the predicates crate.  See https://github.com/assert-rs/predicates-rs .  You can probably do everything you want there, without changing Mockall's code.

**Comment by mgeisler** [comment]
Ah, thanks for the pointer! I had not seen this at all :smile: I'll go take a look there instead.
