### ISSUE TITLE
Question: Unit testing a mocked trait implementation

### ISSUE THREAD

**Issue by QnJ1c2kNCg** [asomers/mockall#497]
### Context
We have a `struct` what we are mocking
```rust
struct Value {...}

#[cfg_attr(test, mockall::automock)]
impl Value {...}
```

We have a trait, that uses this mock struct as a return type.
```rust
#[mockall_double::double]
use Value;

#[cfg_attr(test, mockall::automock)]
pub trait MyStore {
    fn insert(&self, ...) -> Value;
    ...
}
```

This is great, because we can use `MockMyStore` in the code base, and it returns `MockValue`.

However, we are having issues unit testing the implementation of this store.
```rust
#[mockall_double::double]
use Value;

struct MyStoreImpl {...}

impl MyStore for MyStoreImpl {
    fn insert(&self, ...) -> Value {
        ...
    }
}
```

Is there a way to have unit tests for the *actual* implementation of `MyStoreImpl` that do not use `MockValue`, but instead use the concrete type of `Value`?

Thanks a ton!

**Comment by asomers** [comment]
So you want, say, main.rs to use `MockValue` in unit tests, while in `my_store.rs` you use `Value` always?  If `main.rs` also uses `MyStore`, then you'll have to somehow compile `MyStore` twice in the unit tests.  You'll have to compile a version that uses both `Value` and one that uses `MockValue`.  `automock` isn't smart enough to do that, so you'll have to use `mock!`.  Something like this:


my_store.rs
```rust
use crate::value::Value;
#[cfg(test)]
use crate::value::MockValue;

pub trait MyStore {
    fn insert(&self, ...) -> Value;
}
mock! {
    MyStore {}
    impl Store for MyStore {
       fn insert(&self, ...) -> MockValue;
    }
}
```
main.rs
```rust
#[mockall_double::double]
use crate::my_store::MyStore
```

**Comment by QnJ1c2kNCg** [comment]
I'm not sure I completely follow.

I can add a bit more details, but maybe a quick question first. In your snippet what is `Store`? (in the `mock!` macro)

**Comment by QnJ1c2kNCg** [comment]
I guess I'm confused how we'll compile the trait twice, the `MyStoreImpl` will need the version that returns `Value` for its UT.

**Comment by asomers** [comment]
In my snippet, I meant `MyStore` instead of `Store`.  And the way my snippet compiles it twice is that the first time is the regular `MyStore` and the second is the `MockMyStore`.
