### ISSUE TITLE
Stateful mocks

### ISSUE THREAD

**Issue by mgeisler** [asomers/mockall#509]
Hello,

I'm looking into using mockall to replace some home-grown mocking code in Android: [`mock_uci_manager.rs`](https://cs.android.com/android/platform/superproject/main/+/main:external/uwb/src/rust/uwb_core/src/uci/mock_uci_manager.rs) and the sibling `mock_*.rs` files.

The current mocking sets up [expected calls](https://cs.android.com/android/platform/superproject/main/+/main:external/uwb/src/rust/uwb_core/src/uci/mock_uci_manager.rs;l=82;drc=fd81b7d6756feca1cd2218b615b214f924578dfe) ahead of time and reacts on the [actual calls](https://cs.android.com/android/platform/superproject/main/+/main:external/uwb/src/rust/uwb_core/src/uci/mock_uci_manager.rs;l=485;drc=fd81b7d6756feca1cd2218b615b214f924578dfe). This is similar to what you would do with mockall! However, the mock struct also has a bunch of channels which the unit tests configure before starting the system. The mock uses them to implement the business logic, such as [sending notifications](https://cs.android.com/android/platform/superproject/main/+/main:external/uwb/src/rust/uwb_core/src/uci/mock_uci_manager.rs;l=490;drc=fd81b7d6756feca1cd2218b615b214f924578dfe) when the trait methods are called.

As far as I can tell, it is not possible for me to have custom state in my mock, so it's hard to replicate this directly. I think there are two alternatives currently:

1.  Extending the `UciManager` trait with methods to get access to the channels: something like

    ```rust
    fn get_core_notification_sender(&self) -> mpsc::UnboundedSender<CoreNotification>
    ```

    However, the rest of the system doesn't really need such a method. I suppose I could hide it behind a `cfg(test)` or similar?

2. Let the state live in the unit test and refer back to it when configuring the expectations. Something like

    ```rust
    fn test_open_hal() {
        let (sender, receiver) = mpsc::unbounded_channel();
        let mock_uci_manager = MockUciManager::new();
        mock_uci_manager.expect_open_hal().returning(|| {
            sender.send(...)
            Ok(())
        });
    ```

    However, I think this would make it hard for me to build a reusable mock: many tests need to configure the expectations the same way, so I would like to have the code for this in a single place.

Are there other common patterns here that I haven't thought of? Thanks for any advice!

**Comment by mgeisler** [comment]
Hi @asomers, thanks for confirming that the second approach is viable approach!

Initially, I was worried about composition, but it now occurs to me that I can stash away as much state as I want in a different struct. Here is an example which allows me to configure the two methods independently but still have them share state:

```rust
use mockall::automock;

#[automock]
trait Foo {
    fn make_msg(&self) -> String;
    fn set_x(&mut self, x: i32);
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::{Arc, Mutex};

    #[derive(Debug, Default)]
    struct MockFooState {
        x: i32,
        updates: Vec<String>,
    }

    fn configure_make_msg(foo: &mut MockFoo, state: Arc<Mutex<MockFooState>>) {
        foo.expect_make_msg().times(..).returning(move || {
            let mut state = state.lock().unwrap();
            state.x += 1;
            format!("x is {}", state.x)
        });
    }

    fn configure_set_x(foo: &mut MockFoo, state: Arc<Mutex<MockFooState>>) {
        foo.expect_set_x().times(..).returning(move |x| {
            let mut state = state.lock().unwrap();
            let old_x = state.x;
            state.updates.push(format!("{old_x} -> {x}"));
            state.x = x;
        });
    }

    #[test]
    fn test_stateful_mock() {
        let state = Arc::new(Mutex::new(MockFooState::default()));
        let mut foo = MockFoo::new();

        configure_make_msg(&mut foo, state.clone());
        configure_set_x(&mut foo, state.clone());

        foo.set_x(10);

        assert_eq!(foo.make_msg(), "x is 11");
        assert_eq!(foo.make_msg(), "x is 12");

        foo.set_x(100);
        assert_eq!(foo.make_msg(), "x is 101");
        assert_eq!(foo.make_msg(), "x is 102");

        assert_eq!(state.lock().unwrap().updates, vec!["0 -> 10", "12 -> 100"]);
    }
}
```

Thanks for the help!

**Comment by asomers** [comment]
Glad to help.  It sounds like your problem is resolved, so I'll close the issue.
