### ISSUE TITLE
How to mock a Struct

### ISSUE THREAD

**Issue by kingsleyh** [asomers/mockall#519]
Hi I'm new to rust and trying to mock a Struct but after reading the docs I'm still confused

if the implementation was:

```rust
pub struct Apple {}
#[automock]
impl Apple {
    pub fn foo(&self) -> String {
        String::from("foo")
    }
}
pub fn bar(apple: Apple) -> String {
    apple.foo()
}
```

and the test

```rust
#[cfg(test)]
mod tests {
    use super::*;
    use googletest::prelude::*;

    #[googletest::test]
    fn test_bar() {
        let mock_apple = MockApple::default();
        let result = bar(mock_apple);
    }
}
```

I get an error saying

```
   let result = bar(mock_apple);
    |                      --- ^^^^^^^^^^ expected `Apple`, found `MockApple`
```

I tried then to:

```rust
let result = bar(mock_apple as Apple);
```

but it complains that can't cast a non primitive type.

Is it possible to mock a Struct?

**Comment by asomers** [comment]
Your problem is that `Apple` and `MockApple` are different structs, and you've defined `bar` to take the former in all cases.  What you want to do is to define `bar` to accept `MockApple` in test mode.  A key requirement is that you define `bar` and `Apple` in different modules.  See the example at https://docs.rs/mockall/latest/mockall/#mocking-structs .  The example uses mockall_double , but you can also do it by hand with the appropriate `#[cfg()]` statements.

**Comment by kingsleyh** [comment]
aahhh I understand now - so I had to do this:

```rust
mod first {
    use mockall::*;
    pub struct Apple {}
    #[automock]
    impl Apple {
        pub fn foo(&self) -> String {
            String::from("foo")
        }
    }
}

mod second {
    use mockall_double::double;
    #[double]
    use super::first::Apple;

    pub fn bar(apple: Apple) -> String {
        apple.foo()
    }
}

#[cfg(test)]
mod tests {
    use crate::{super::{first::MockApple, second::bar}};

    use super::*;
    use googletest::prelude::*;

    #[googletest::test]
    fn test_generate_tokens_for_user() {
      let mut mock_apple = MockApple::default();
      mock_apple.expect_foo().returning(|| "mock foo".to_string());
      let result = bar(mock_apple);
      println!("result: {}", result);
    }
}
```

I grabbed the mockall_double crate - which I guess handles the magic of swapping the structs out for test etc

Thanks for the help
