### ISSUE TITLE
How to add expectations for multiple arguments?

### ISSUE THREAD

**Issue by andresovela** [asomers/mockall#522]
All the examples mock trait methods that take a single argument.

If I have 

```
trait Foo {
     fn do_something(&self, x: u32, y:u32);
}
```

how do I set expectations for both x and y?

**Comment by asomers** [comment]
It's easy.  You can use `withf`, which will take a closure with two arguments.  Or, you can use `with`, which will take two arguments, both of which are `Predicate`s.
https://docs.rs/mockall/latest/mockall/#matching-arguments

**Comment by andresovela** [comment]
Can't believe I missed that, sorry
