### ISSUE TITLE
Raw method identifiers stopped working with mockall `0.12.0`

### ISSUE THREAD

**Issue by tim3z** [asomers/mockall#533]
Since `mockall` `0.12.0` the following

```rust
#[mockall::automock]
trait Foo {
    fn r#match(&self);
}
```

doesn't compile anymore:
```
error: custom attribute panicked
 --> src/main.rs:1:1
1 | #[mockall::automock]
  | ^^^^^^^^^^^^^^^^^^^^
  |
  = help: message: `"expect_r#match"` is not a valid identifier
```

With `0.11.4` this worked just fine.

**Comment by asomers** [comment]
This is odd: the buggy code was recommended by Clippy: 60acf8e4 .  I'll have it fixed soon.  Thanks for reporting it.

**Comment by tim3z** [comment]
Odd indeed. Clippy should probably not propose changes to formatting macros from crates outside the stdlib...

**Comment by asomers** [comment]
> Odd indeed. Clippy should probably not propose changes to formatting macros from crates outside the stdlib...

The current nightly Clippy doesn't.  So maybe that proposed change was due to a short-lived bug in Clippy, now fixed.
