### ISSUE TITLE
MSRV is listed as 1.64.0, but varies because of `predicates` dependency

### ISSUE THREAD

**Issue by clechasseur** [asomers/mockall#535]
`mockall` 0.12.0 lists its MSRV as 1.64.0, but it depends on `predicates` 3. Version `3.0.0` of `predicates` indeed had an MSRV of 1.64.0, but that varied across fix versions of `predicates`. Current version of `predicates` 3 is 3.0.4 and has an MSRV of 1.70.0 because of its dependency on `itertools` 0.11. This can be seen here:

https://github.com/clechasseur/mini_exercism/actions/runs/7229809158/job/19701142187

I'm not sure if this is critical or not; `mockall` is for testing, so I'm guessing it can't really leak MSRV as much. But I just thought I'd point it out. Maybe update the documentation?

**Comment by asomers** [comment]
Indeed the MSRV _is_ 1.64.0.  That just means that it's possible to build the crate with Rust 1.64.0, not that it's possible to build it with the latest versions of all of its dependencies.  A Rust 1.64.0 user would probably have to `cargo update -p predicates --precise 3.0.3`.  We do basically the same thing during CI.
