### ISSUE TITLE
Support returning of generic parameter using `mock!` macro

### ISSUE THREAD

**Issue by Velnbur** [asomers/mockall#536]
I'm trying to do something like this:

```rust
/*
[dependencies]
mockall = "0.12.0"
*/

trait Trait {
    fn generic_method<T: From<u64>>(&self, num: u64) -> T;
}

struct Implementor;

impl Trait for Implementor {
    fn generic_method<T: From<u64>>(&self, num: u64) -> T {
        T::from(num)
     }
}

mockall::mock! {
    pub Mock {}

    impl Trait for Mock {
        #[mockall::concretize]
        fn generic_method<T: From<u64>>(&self, num: u64) -> T;
    }
}

fn main() {
    let i = Implementor;
    println!("{}", i.generic_method::<u64>(3u64));
}
```

It's just a representation for reproducing the issue. The problem is that for some reason `mock!` in the expanded form is leaving the generic parameter `T` in the returning type of the method in the related `Expectation` structure as it is. Which leads to this error:

```
error[E0412]: cannot find type `T` in this scope
  --> src/main.rs:23:61
   |
23 |         fn generic_method<T: From<u64>>(&self, num: u64) -> T;
   |                                                             ^ not found in this scope

For more information about this error, try `rustc --explain E0412`.
error: could not compile `playground` (bin "playground") due to 1 previous error
```

Maybe, I'm doing something wrong, but I haven't found any similar issues, so leaving it here

**Comment by Velnbur** [comment]
Oh, Im found #242

**Comment by asomers** [comment]
That's probably a bug in `#[concretize]`.  However, you shouldn't be using `#[concretize]` for methods that return generic parameters.  It's only useful for methods that take generic parameters as arguments.  You don't need it for this method.  You might, however, need to add a `'static` bound to `T`.
```rust
#[automock]
trait Trait {
    fn generic_method<T: From<u64> + 'static>(&self, num: u64) -> T;
}
```
