### ISSUE TITLE
mocking struct & mockall_double::double not working as expected

### ISSUE THREAD

**Issue by zaidoon1** [asomers/mockall#564]
project directory:

```
src
----> main.rs
----> storage
          --------> client.rs
```

client.rs:

```
#[cfg(test)]
use mockall::automock;

pub struct HelloClient {
    client: ....,
}

#[cfg_attr(test, automock)]
impl HelloClient {
......
} 

```

main.rs:
```
#[mockall_double::double]
use <project_name>::storage::client::HelloClient;

async fn delete_records(
    records: &[Vec<u8>],
    hello_client: &HelloClient,
) {
xxxx
}
```

compiler complains with: 
```
unresolved import `<project_name>::storage::client::MockHelloClient`
no `MockHelloClient` in `storage::client`
```

If I move `mockall` from dev-dependencies to dependencies in cargo.toml and and update storage.rs to:
```
#[automock]
impl HelloClient {
......
} 
``` 

Things appear to work? But I don't want mockall to be a dependency. What am I doing wrong?

**Comment by zaidoon1** [comment]
maybe it's in the mod file?

What I have is:
```
src
----> main.rs
----> storage
          --------> client.rs
          ---------> mod.rs
 ```
 
 my mod.rs looks like:
 ```
 pub mod client;
 ```
 
 I already posted the entire code for client.rs. I have a lib.rs in the same directory as main.rs that has:
 ```
 pub mod storage;
 ```
 
 That's pretty much it..

**Comment by asomers** [comment]
When do you see the error?  Is it when you do `cargo build` or `cargo test --bin` ?  What version of Mockall are you using?

**Comment by asomers** [comment]
But `cargo test` does lots of things: unit tests, integration tests, and doc tests.  It even checks the examples.  That's why I asked specifically for `cargo test --bin`.  That will tell you if your project builds successfully in test mode.

**Comment by zaidoon1** [comment]
just ran it with cargo test --bin:

```
error[E0432]: unresolved import `cache_index_plunger::cachedb::client::MockCachedbClient`
  --> src/main.rs:38:5
   |
38 | use < project_name>::storage::client:: HelloClient;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^-------------
   |     |                                     |
   |     |                                     help: a similar name exists in the module: `HelloClient`
   |     no `MockHelloClient ` in `storage::client`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `project_name` (bin "project_name" test) due to 1 previous error

**Comment by asomers** [comment]
That tells you that your project fails to build in test mode.  You also said that it fails during `cargo build`.  But that error message doesn't make sense for non-test mode.  Are you sure that you get the same error during `cargo build`?

**Comment by zaidoon1** [comment]
sorry, that's my bad, `cargo build` works fine.

**Comment by asomers** [comment]
Your problem is that your crate contains both a library and a binary.  When you build the binary in test mode, the library is built in non-test mode, just like an external dependency.  So you need to either:
* Eliminate the library and move everything into the binary
* Make mockall a full dependency, possibly feature-gated, and export the mocks always
* Define the mock structure using `mock!` in the binary, not `#[automock]` in the library.

**Comment by zaidoon1** [comment]
oh i see. thank you!
