### ISSUE TITLE
In predicate functions, use deref()ed type for argument types that are Deref

### ISSUE THREAD

**Issue by dsarlis** [asomers/mockall#58]
We recently started using `mockall` and we hit a case where it looks like there's a problem with the code expansion/conversion happening inside the `mock!` macro. The following code snippet is enough to repro the issue:

```
trait Foo {
    fn f(input: Vec<u32>);
}

#[cfg(test)]
mod test {
    use super::*;
    use mockall::*;

    mock! {
        pub Foo {}

        trait Foo {
            fn f(input: Vec<u32>);
        }
    }
}
```

If you run `cargo clippy --tests -- -D clippy::all`, then you get the following warning (which we treat as an error) and we have to add an `#![allow(clippy::ptr_arg)]` to go around for now:
```
error: writing `&Vec<_>` instead of `&[_]` involves one more reference and cannot be used with non-Vec-based slices.
  --> src/main.rs:10:5
   |
10 | /     mock! {
11 | |         pub Foo {}
12 | |
13 | |         trait Foo {
14 | |             fn f(input: Vec<u32>);
15 | |         }
16 | |     }
   | |_____^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg
```

**Comment by asomers** [comment]
Adding that allow statement is a totally valid way to handle the problem.  However, much as Mockall understands the relationship between `CString` and `CStr` it could also use `&[T]` for predicate functions of methods taking `Vec<T>` arguments.  I'll treat this as a feature request.

**Comment by asomers** [comment]
I've decided against adding this feature.  It sounded like a good idea, but it would actually make writing tests more difficult.  It's not a problem to write tests with `withf`, but it can create lifetime problems for `with`.  For example, the status quo is that, for your function above, `with` should have an argument of type `Predicate<Vec<u32>> + Send + 'static`.  If I implement this feature as described, that would become `Predicate<[u32]> + Send + 'static`.  No problem perhaps, if your expected arguments are known at compile-time.  But if you must compose them at runtime, then you have a problem.  Instead, I'll just silence the Clippy warning.
