### ISSUE TITLE
Mocking an async trait with generics

### ISSUE THREAD

**Issue by Tockra** [asomers/mockall#580]
Hello,

I still have to use the `async_trait` crate because I have a trait where I need to create trait objects. This seems to be impossible if the trait contains async methods. So I have this:

```rust
#[async_trait]
pub trait DatabaseService<T: model::Element>: Debug + Sync + Send {
    fn as_any(&self) -> &dyn Any;
    async fn connect(&mut self, config: &Config) -> Result<(), mongodb::error::Error>;
    async fn get_documents(
        &self,
        conditions: Conditions
    ) -> Vec<T>;
}
```

Now I'm having problems using `mockall` with this. `Automock` does not work, and I have tried multiple variants of `mock!`.

Maybe somebody can give me a hint on how I can mock a test for the following function:

```rust
pub async fn get_positions(db: &dyn DatabaseService<Position>, filters: Filters) -> Vec<Position> {
    db.get_documents(
        Conditions::from(filters.clone())
    )
    .await
}
```

I just want to test a few things:
1. My `get_positions` function calls the `get_documents` function of the passed `DatabaseService`.
2. My `get_positions` function returns the result of `db.get_documents()`.

Does anybody have a hint for me on how to achieve this?

Thanks!

**Comment by asomers** [comment]
automock does work with async_trait.  For example, see https://github.com/asomers/mockall/blob/master/mockall/tests/automock_async_trait.rs .  The main thing to be aware of is that the automock attribute must _precede_ the async_trait attribute.

**Comment by Tockra** [comment]
Okay, my program does not compile if I do it. Maybe somebody could assist to fix the example above.

**Comment by asomers** [comment]
Maybe you could post the error message?

**Comment by Tockra** [comment]
Of course:
```bash
error: future cannot be sent between threads safely
  --> src/db/mod.rs:30:1
   |
30 | #[automock]
   | ^^^^^^^^^^^ future created by async block is not `Send`
   |
note: captured value is not `Send` because `&mut` references cannot be sent unless their referent is `Send`
  --> src/db/mod.rs:45:27
   |
45 |     async fn connect(&mut self, config: &Config) -> Result<(), mongodb::error::Error>;
   |                           ^^^^ has type `&mut MockDatabaseService<T>` which is not `Send`, because `MockDatabaseService<T>` is not `Send`
   = note: required for the cast from `Pin<Box<{async block@src/db/mod.rs:30:1: 30:12}>>` to `Pin<Box<(dyn futures::Future<Output = Result<(), mongodb::error::Error>> + std::marker::Send + 'async_trait)>>`
   = note: this error originates in the attribute macro `automock` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider further restricting this bound
   |
32 | pub trait DatabaseService<T: model::Element + std::marker::Send>: Debug + Sync + Send {
   |                                             +++++++++++++++++++


```

**Comment by asomers** [comment]
Did you try following the compiler's advice?

**Comment by Tockra** [comment]
I am not sure how to archive this.
As you saw in my first post the Traits restriction already assume Sync + Send

**Comment by Tockra** [comment]
After fullfilling the suggestions step for step I arrived at:
```rs
#[cfg(test)]
use mockall::{automock, mock, predicate::*};
#[cfg_attr(test, automock)]
#[async_trait]
pub trait DatabaseService<T: model::Element + std::marker::Send + std::marker::Sync>:
    Debug + Sync + Send
    // ...
```

With error message:
```
error[E0277]: `(dyn std::any::Any + 'static)` cannot be sent between threads safely
   --> src/db/mod.rs:30:11
    |
30  | pub trait DatabaseService<T: model::Element + std::marker::Send + std::marker::Sync>:
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `(dyn std::any::Any + 'static)` cannot be sent between threads safely
    |
    = help: the trait `std::marker::Send` is not implemented for `(dyn std::any::Any + 'static)`, which is required by `MockDatabaseService<T>: std::marker::Send`
    = note: required for `Unique<(dyn std::any::Any + 'static)>` to implement `std::marker::Send`
note: required because it appears within the type `Box<(dyn std::any::Any + 'static)>`
   --> /Users/titan/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:197:12
    |
197 | pub struct Box<
    |            ^^^
note: required because it appears within the type `__as_any::Rfunc<T>`
   --> src/db/mod.rs:28:18
    |
28  | #[cfg_attr(test, automock)]
    |                  ^^^^^^^^
note: required because it appears within the type `__as_any::Expectation<T>`
   --> src/db/mod.rs:28:18
    |
28  | #[cfg_attr(test, automock)]
    |                  ^^^^^^^^
    = note: required for `Unique<__as_any::Expectation<T>>` to implement `std::marker::Send`
note: required because it appears within the type `alloc::raw_vec::RawVec<__as_any::Expectation<T>>`
   --> /Users/titan/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/raw_vec.rs:69:19
    |
69  | pub(crate) struct RawVec<T, A: Allocator = Global> {
    |                   ^^^^^^
note: required because it appears within the type `Vec<__as_any::Expectation<T>>`
   --> /Users/titan/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:398:12
    |
398 | pub struct Vec<T, #[unstable(feature = "allocator_api", issue = "32838")] A: Allocator = Global> {
    |            ^^^
note: required because it appears within the type `__as_any::Expectations<T>`
   --> src/db/mod.rs:28:18
    |
28  | #[cfg_attr(test, automock)]
    |                  ^^^^^^^^
note: required because it appears within the type `MockDatabaseService_DatabaseService_13065831140148901594<T>`
   --> src/db/mod.rs:30:11
    |
30  | pub trait DatabaseService<T: model::Element + std::marker::Send + std::marker::Sync>:
    |           ^^^^^^^^^^^^^^^
note: required because it appears within the type `MockDatabaseService<T>`
   --> src/db/mod.rs:30:11
    |
30  | pub trait DatabaseService<T: model::Element + std::marker::Send + std::marker::Sync>:
    |           ^^^^^^^^^^^^^^^
note: required by a bound in `DatabaseService`
   --> src/db/mod.rs:31:20
    |
30  | pub trait DatabaseService<T: model::Element + std::marker::Send + std::marker::Sync>:
    |           --------------- required by a bound in this trait
31  |     Debug + Sync + Send
    |                    ^^^^ required by this bound in `DatabaseService`
    = note: this error originates in the attribute macro `automock` (in Nightly builds, run with -Z macro-backtrace for more info)


```

**Comment by asomers** [comment]
That message is telling you that the `as_any` method's return value is not `Send`.  Try adding a `+ Send` trait bound to it.

**Comment by iddm** [comment]
Hey there! I can't make it to work with my code:

```rust
#[cfg_attr(test, automock)]
#[async_trait]
pub trait VirtualMachine: std::fmt::Debug + Send + Sync {
    fn as_any(&self) -> &(dyn std::any::Any + Send + Sync + 'static);
}
```

There are **always** issues which prevent the `automock` from expanding, for example, in this case:

```
error[E0277]: the size for values of type `(dyn std::any::Any + std::marker::Send + std::marker::Sync + 'static)` cannot be known at compilation time
   --> src/services/mod.rs:463:26
    |
463 |     fn as_any(&self) -> &(dyn std::any::Any + Send + Sync + 'static);
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `(dyn std::any::Any + std::marker::Send + std::marker::Sync + 'static)`
help: you can use `impl Trait` as the argument type
    |
463 |     fn as_any(&self) -> &(impl std::any::Any + Send + Sync + 'static);
    |                           ~~~~
help: function arguments must have a statically known size, borrowed types always have a known size
    |
463 |     fn as_any(&self) -> &(&(dyn std::any::Any + Send + Sync + 'static));
    |                           ++                                         +
```
It is always one thing or another. What would you suggest here? I really want to avoid using `Arc` or `Box` here just because I want the' auto mock` to work. I have had this code working with a reference to `Any` for ages, and I want to avoid the unnecessary overhead.

**Comment by Tockra** [comment]
> Hey there! I can't make it to work with my code:
> 
> #[cfg_attr(test, automock)]
> #[async_trait]
> pub trait VirtualMachine: std::fmt::Debug + Send + Sync {
>     fn as_any(&self) -> &(dyn std::any::Any + Send + Sync + 'static);
> }
> There are **always** issues which prevent the `automock` from expanding, for example, in this case:
> 
> ```
> error[E0277]: the size for values of type `(dyn std::any::Any + std::marker::Send + std::marker::Sync + 'static)` cannot be known at compilation time
>    --> src/services/mod.rs:463:26
>     |
> 463 |     fn as_any(&self) -> &(dyn std::any::Any + Send + Sync + 'static);
>     |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
>     |
>     = help: the trait `std::marker::Sized` is not implemented for `(dyn std::any::Any + std::marker::Send + std::marker::Sync + 'static)`
> help: you can use `impl Trait` as the argument type
>     |
> 463 |     fn as_any(&self) -> &(impl std::any::Any + Send + Sync + 'static);
>     |                           ~~~~
> help: function arguments must have a statically known size, borrowed types always have a known size
>     |
> 463 |     fn as_any(&self) -> &(&(dyn std::any::Any + Send + Sync + 'static));
>     |                           ++                                         +
> ```
> 
> It is always one thing or another. What would you suggest here? I really want to avoid using `Arc` or `Box` here just because I Hey, I can't help you with your problem directly. But I would like to know if you need the Any here. 

I built it in the past to have a possibility to receive my implementation type without pin it. 
Later I decided just to set a global type, which pin the main used `fn get_service(&self) -> &CurrentDatabaseService<T>;`. 'And somewhere `pub type CurrentDatabaseService<T> = mongo::MongodbDatabaseService<T>;` .

**Comment by iddm** [comment]
Thank you for jumping in so quickly!

So, I use the downcasting in my implementation code for another trait, which uses the objects of `dyn VirtualMachine`. I allow one implementation of `VirtualMachineManager` to use its own version of `VirtualMachine` **and** work with another implementation of a `VirtualMachine` in some cases. This is perfect in my code and allows me to write the common code directly in some extension traits, which **really** provide a lot of flexibility and make life much easier. So, I use `as_any` primarily to be able to downcast to some specific implementation. Also, I cannot really make it generic but rather only have it as a polymorphic object for that runtime purpose.
