### ISSUE TITLE
`#[derive(Clone)]` is not generating the implementation

### ISSUE THREAD

**Issue by cernicc** [asomers/mockall#583]
version: 0.12.1

[This ](https://github.com/asomers/mockall/blob/11a9206e0d1cd63c446527fa9d23b7aac3d0599c/mockall/src/lib.rs#L1055) doesn't work. If I implement the Clone manually it works.

```
mockall::mock! {
    #[derive(Clone)]
    pub Something {}
}
```

**Comment by asomers** [comment]
Mock objects cannot automatically implement `Clone`.  If they did, what should happen to expectations when an object gets cloned?  Should the expectations be cloned too?  That's not always desirable, and not always even possible.  Instead, Mockall treats `Clone` like any other trait.

**Comment by cernicc** [comment]
Aha. Good point. Thanks for the quick response
