### ISSUE TITLE
Is there a way to specify derives for the generated mock struct?

### ISSUE THREAD

**Issue by tobz** [asomers/mockall#59]
I have a use case where the trait I'm mocking is always available as a `Clone`able concrete type.  It looks like there's no option currently to specify custom derives for the mocked struct.

Is this technically feasible to provide? I understand that it would likely be impossible for the cloned copies to contribute to the expectations/assertions/etc but it would allow me to use a unified mock implementation which would be sweet. ❤️ 

At any rate, thanks for this crate! 😄

**Comment by asomers** [comment]
Are you saying that you have a struct like this:
```rust
#[derive(Clone)]
struct Foo {}
impl MyTrait for Foo {
    ...
}
```
And you want `MockFoo` to `impl Clone`?  Currently the way to do that is to do:
```rust
mock!{
    MockFoo
    {
        // Foo's methods
    }
    Clone
    {
        fn clone(&self) -> MockFoo {...}
    }
}
```
Does that work for you?

**Comment by tobz** [comment]
I'm not sure that it does.

Since `MockFoo` would have internal fields that I wouldn't know until the procedural macro rewrote the code, how could I reasonably provide a manual `Clone` implementation?

**Comment by asomers** [comment]
Well, you could `impl Clone` by returning `Self::default()`.  That's probably the best that you could possibly do.  Deriving `Clone` is fundamentally incompatible with methods like `return_once` that rely on non-`Clone` closures.

**Comment by asomers** [comment]
Actually, the example I wrote above isn't correct.  `mock!` doesn't contain an implementation of clone; it just allows the `clone` method to be mocked, like this:
```rust
mock!{
    Foo
    {
        // Foo's methods
    }
    Clone
    {
        fn clone(&self) -> Self;
    }
}
let mut mock = MockFoo::new();
mock.expect_clone()
    .returning(|| MockFoo::new());
```

**Comment by tobz** [comment]
Ahaaaa.  That makes more sense, yeah.  I was pigeonholing myself on thinking I needed to be constructing `MockFoo` manually. :)

I'll give that a shot and report back.

**Comment by tobz** [comment]
This is what I'm up against now:

    error: Unsupported in this context
      --> src/backend/processor/mod.rs:93:5
       |
    93 |     Clone {
       |     ^^^^^


For the following code: https://gist.github.com/tobz/117eb496c6bc374b0d5b6f1555117065

**Comment by asomers** [comment]
s/Clone/trait Clone/

**Comment by tobz** [comment]
Still the exact same error even with `trait Clone`.

**Comment by asomers** [comment]
Take a look at this test: https://github.com/asomers/mockall/blob/master/mockall/tests/mock_clone.rs .  If you still can't get it to work, point me at your repo, or send a complete self-contained gist, and I'll take a look.

**Comment by tobz** [comment]
For posterity, I solved this and then iterated to a simpler design:

I realized by reading the documentation more carefully that `mock!` had more stringent/esoteric content requirements i.e. the duplication of the trait itself.  Initially, the code I wrote was pigeonholed on the advice you gave, but I realized it wasn't intended to be a bit-perfect representation of the code to use.  Once I fixed that -- both following the documentation more close and also mocking the `Clone` trait, things worked.

This still placed weird constraints on using the mock in practice, though, because the mocked type was being passed multiple levels deep via clones, which would have required some un-heretofore known magic to propagate those expectations into the clones to avoid panicking.

I solved this by killing two birds with one impl: creating a forward trait impl for `Arc<T>` and wrapping my mock.  The `Arc<T>` provided the cloning I needed _and_ because my trait has no mutability, I could seamlessly forward through to the underlying trait object through the `Arc<T>` without any issues.

Thanks again for the help / rubberducking.  Looking forward to finally being able to utilize `mockall`. 👍

**Comment by sweatybridge** [comment]
I ran into the same issue trying to mock a trait that's cloned multiple times by warp filter. Here's the implementation that I came up with following @tobz's comment. Could you help me check if it makes sense?

```rust
use std::sync::Arc;

/// When mock objects are cloned, their expectations cannot be carried over automatically. This
/// means we need to nest multiple levels of mocked clone to set expectations on the correct
/// instance. To avoid such boilerplate, we use an Arc<T> inner field to wrap an instance of T.
/// When cloned, only its reference count is incremented and not the whole mock object.
pub struct MockWrapper<T> {
    inner: Arc<T>,
}

impl<T> Clone for MockWrapper<T> {
    fn clone(&self) -> Self {
        MockWrapper {
            inner: self.inner.clone(),
        }
    }
}

impl<T> MockWrapper<T> {
    pub fn new(inner: T) -> MockWrapper<T> {
        MockWrapper {
            inner: Arc::new(inner),
        }
    }

    pub fn get(&self) -> &T {
        self.inner.as_ref()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use mockall::automock;

    #[automock]
    trait Foo {
        fn foo(&self) -> i64;
    }

    #[test]
    fn test_mock_clone() {
        let mut mock = MockFoo::new();
        mock.expect_foo().times(2).returning(|| 42);
        let wrapper = MockWrapper::new(mock);
        // Cloned wrapper sets expectations on inner mock
        let cloned = wrapper.clone();
        cloned.get().foo();
        cloned.clone().get().foo();
    }
}
```

**Comment by asomers** [comment]
Yeah, that seems like a reasonable approach, if you have a mock object that you're going to clone many times.

**Comment by AurelienFT** [comment]
Hello,
I try to use you wrapper @sweatybridge but can I add more except on the object after placing it in the wrapper ?

**Comment by tvsfx** [comment]
> I ran into the same issue trying to mock a trait that's cloned multiple times by warp filter. Here's the implementation that I came up with following @tobz's comment. Could you help me check if it makes sense?
> 
> ```rust
> use std::sync::Arc;
> 
> /// When mock objects are cloned, their expectations cannot be carried over automatically. This
> /// means we need to nest multiple levels of mocked clone to set expectations on the correct
> /// instance. To avoid such boilerplate, we use an Arc<T> inner field to wrap an instance of T.
> /// When cloned, only its reference count is incremented and not the whole mock object.
> pub struct MockWrapper<T> {
>     inner: Arc<T>,
> }
> 
> impl<T> Clone for MockWrapper<T> {
>     fn clone(&self) -> Self {
>         MockWrapper {
>             inner: self.inner.clone(),
>         }
>     }
> }
> 
> impl<T> MockWrapper<T> {
>     pub fn new(inner: T) -> MockWrapper<T> {
>         MockWrapper {
>             inner: Arc::new(inner),
>         }
>     }
> 
>     pub fn get(&self) -> &T {
>         self.inner.as_ref()
>     }
> }
> 
> #[cfg(test)]
> mod tests {
>     use super::*;
>     use mockall::automock;
> 
>     #[automock]
>     trait Foo {
>         fn foo(&self) -> i64;
>     }
> 
>     #[test]
>     fn test_mock_clone() {
>         let mut mock = MockFoo::new();
>         mock.expect_foo().times(2).returning(|| 42);
>         let wrapper = MockWrapper::new(mock);
>         // Cloned wrapper sets expectations on inner mock
>         let cloned = wrapper.clone();
>         cloned.get().foo();
>         cloned.clone().get().foo();
>     }
> }
> ```

Just had to use this pattern in some code that internally calls `clone` on my mocked, injected dependency; thanks!
 
It seems to me that this pattern is more generally useful; I often have tests where a mock is injected into some larger structure as a dependency, where if one wants to call e.g. `checkpoint` on the mock and create new expectations, one needs to dig through the larger structure's private fields to recover the mock and do this. If a generic wrapping scheme like this were to be supported, it would be easy to just clone the mock before injecting it.

**Comment by YarekTyshchenko** [comment]
After some research I found a solution to this: https://github.com/asomers/mockall/discussions/327#discussioncomment-10693846
