### ISSUE TITLE
Define mocks in #[cfg(test)]

### ISSUE THREAD

**Issue by janosimas** [asomers/mockall#591]
Hey, great work with the crate!

I don't know if I missed something but is there a way of defining the mock inside `#[cfg(test)]`?
Ideally with `automock`.

Currently, the mocks are visible, for example, in the docs.

**Comment by asomers** [comment]
Yes, that's a very common need.  Do `#[cfg_attr(test, automock)]`.

**Comment by sergeda** [comment]
I have issue with this config.
I have this trait:
```
#[cfg_attr(test, mockall::automock)]
#[allow(async_fn_in_trait)]
pub trait IpResolver {
    async fn resolve(&self, ip: &str) -> Result<Location, IpResolverError>;
}
```

Then it tests I'm trying to use it:
```
    use my::ip2loc::MockIpResolver;
    use mockall::*;
    use mockall::predicate::*;


    #[tokio::test]
    async fn test_all_path() {
        let mut mocked_resolver = MockIpResolver::new();
```

But I'm getting error:

> unresolved import `my::ip2loc::MockIpResolver`
>    --> src/main.rs:144:9
>     |
> 144 |     use my::ip2loc::MockIpResolver;
>     |         ^^^^^^^^^^^^^^^--------------
>     |         |              |
>     |         |              help: a similar name exists in the module: `IpResolver`
>     |         no `MockIpResolver` in `ip2loc`

How to solve this?

**Comment by janosimas** [comment]
@sergeda is you test under a `#[cfg(test)]`?

**Comment by sergeda** [comment]
> @sergeda is you test under a `#[cfg(test)]`?

Yes, sure @janosimas

**Comment by asomers** [comment]
@sergeda what is `my`?  Is that a crate name?  Does IpResolver live in a different crate than the one where the test is?  Because even when cargo builds a crate with `#[cfg(test)]` on, it doesn't build the dependencies with `#[cfg(test)]`.

**Comment by sergeda** [comment]
> @sergeda what is `my`? Is that a crate name? Does IpResolver live in a different crate than the one where the test is? Because even when cargo builds a crate with `#[cfg(test)]` on, it doesn't build the dependencies with `#[cfg(test)]`.

yes, it's my crate. IpResolver lives in the same crate

**Comment by asomers** [comment]
There isn't enough information here for me to solve this problem for you.  But it's got to be one of a few things:
* You are trying to use MockIpResolver somewhere that isn't `#[cfg(test)]`
* You are trying to use MockIpResolver from a different crate than the one where it's declared
* You just specified the path wrong

**Comment by sergeda** [comment]
Moving tests out of main.rs fixed the issue somehow. Everything works fine. Thanks

**Comment by asomers** [comment]
Ahh,  Probably your crate had two targets: a lib target and a bin target.  When building the bin in test mode, the lib gets built in non-test mode.
