### ISSUE TITLE
Is it possible to mock a trait method that has no return?

### ISSUE THREAD

**Issue by mgumbley-resilient** [asomers/mockall#592]
Hi, thank you for mockall - I'm trying to assert that a method in a trait that has no return type is being called:
```
#[cfg_addr(test, automock)]
pub trait Thing {
  fn start(&mut self);
}
#[test]
fn thing_starts() {
  let mut thing = MockThing::new();
  thing.expect_start().once();
  let mut sut = ThingUser::new(Box::new(thing)); // takes a Box<dyn Thing>
  sut.start_the_thing(); // will call thing.start()
}
```

When I run this, I have a panic with:
```
MockThing::start: Expectation(<anything>) Returning default values requires the "nightly" feature
```

I'm not using "nightly" - and am not actually returning anything: the function is called for its side-effects.

I can work around this by making the start method return unit (`-> ()`) and in my test, use `thing.expect_start().once().return_const(());` but it's a little messy. Could this case be simplified?

**Comment by asomers** [comment]
A function that has "no return" really does just return `()`.  And when you write your expectations, you really do need to do `.return_const(())`.  But as the error message says, you can leave that part out if you enable the "nightly" feature.  The specific nightly compiler feature that we need is Specialization, and unfortunately that one looks a long way from stabilization.

**Comment by mgumbley-resilient** [comment]
Thank you Alan.
