### ISSUE TITLE
How to correctly define associated types? 

### ISSUE THREAD

**Issue by jakegallow** [asomers/mockall#599]
I'm not sure what i need to do to correctly define an associated type in mockall, and im not able to find this in the docs. Here's an example:

```rs
pub trait OutsideTrait {
    type AssociatedType;

    fn fn_returning_associated_type() -> Self::AssociatedType;
}

#[cfg(test)]
mod test {
    use super::OutsideTrait;
    use mockall::mock;

    mock! {
        MyS {}

        impl OutsideTrait for MyS {
            type AssociatedType = i32;

            fn returning_associated_type() -> Self::AssociatedType;
        }
    }
}
```

**In the real code im not able to use automock because it's an external module so please dont suggest that!**

```
error[E0223]: ambiguous associated type
  --> src\lib.rs:33:9
   |
33 | /         MyS {}
34 | |
35 | |         impl MyTrait for MyS {
36 | |             type AssociatedType = i32;
37 | |
38 | |             fn returning_associated_type() -> Self::AssociatedType;
   | |_____________________________________________________________________^ help: use fully-qualified syntax: `<test::MockMyS as MyTrait>::AssociatedType`
```

This seems like kind of an infinite box problem. That `MockMyS` is not known until the module is compiled, so I dont know how you could use the fully qualified syntax at this point. Is there a known way of dealing with this constraint of having an associated type for a type where you own the struct but not the trait? Should I be using double or something else?

**Comment by asomers** [comment]
It's possible to do what you want.  See https://github.com/asomers/mockall/blob/master/mockall/tests/mock_associated_types.rs for an example.

**Comment by jakegallow** [comment]
sigh, im sorry. I should have read the examples dir. Sorry for the inconvenience.
