### ISSUE TITLE
project structure / dev. dependency

### ISSUE THREAD

**Issue by blittable** [asomers/mockall#60]
A question...

The doc shows the crate as a dev-dependency.  In a minimal bin this leads to an error if a trait is defined per the doc.  If it is a regular dependency, all works well.

Are project mocks somehow defined in integration tests?  If so, are the traits duplicated in those integration test crates?  

Thanks!

**Comment by asomers** [comment]
Normally Mockall is declared as a dev-dependency and only used in unit tests, not in integration tests.  If you want to use it in integration tests, you must either:
* define the mock trait within the `tests/` directory using `mock!`
* declare Mockall as a regular dependency, gated by an off-by-default feature flag, and always enable that flag when running your tests.

**Comment by asomers** [comment]
Did that answer your question?

**Comment by blittable** [comment]
It got me moving in the right direction... thanks!

I hit a bump (or wall) when trying no_std, but let me shape it into a more annoying question next week.  

I'll send a PR for a runnable example at some point:

Right now... working with something like:

```
#[cfg(test)]
use mockall::*;

#[cfg_attr(test, automock)]
trait MyTrait {
    fn foo(&self, x: u32) -> u32;
}

#[cfg(test)]
mod test {
#![allow(unused_imports)]
    use super::*;
    use crate::prelude::*;
    #[test]
    fn test_x() {
        #[allow(unused_variables)]
        let mut mock = MockMyTrait::new();
        mock.expect_foo()
            .with(mockall::predicate::eq(4))
            .times(1)
            .returning(|x| x + 1);
        assert_eq!(5, mock.foo(4));
    }
}
```

**Comment by asomers** [comment]
Yes, that's the easiest way.  Just use Mockall in unit tests.

BTW, `#[no_std]` support would be awesome.  You aren't the first person to ask for it, either.  I don't think it would be difficult to do, but I don't have any experience using `#[no_std]`.  If you can show me an example of a `#[no_std]` project that uses `#[test]`, then I could probably get mockall working for it.
