### ISSUE TITLE
Clippy warning on beta channel for optional parameters

### ISSUE THREAD

**Issue by ChrisGreenaway** [asomers/mockall#617]
With the following code:

```
#![warn(clippy::ref_option)]

#[mockall::automock]
pub trait Store {
    fn find(&self, name: Option<String>) -> bool;
}
```

Running `cargo +beta clippy` generates a warning against the generated mock code:

```
warning: it is more idiomatic to use `Option<&T>` instead of `&Option<T>`
```

**Comment by asomers** [comment]
@ChrisGreenaway can you please try the linked PR?

**Comment by ChrisGreenaway** [comment]
Works. 👍

**Comment by ChrisGreenaway** [comment]
Thanks for the quick fix. :-)

It would be helpful to get a new release, but appreciate it's a pain to release for every small change.
