### ISSUE TITLE
Struct example doesn't work (maybe just for me?)

### ISSUE THREAD

**Issue by mrcosta** [asomers/mockall#69]
Hey people, I was trying to run the [struct example](https://docs.rs/mockall/0.5.2/mockall/#mocking-structs) but it didn't work. Some of the errors were intuitive to fix, but I didn't get too far. Can you guide in making it work? And nice work by the way.

The whole example:

```rust
use mockall::*;
use crate::thing::Thing;

mod thing {
    pub struct Thing{}
    #[automock]
    impl Thing {
        pub fn foo(&self) -> u32 {
            return 32;
        }
    }
}

cfg_if! {
    if #[cfg(test)] {
        use self::thing::MockThing as Thing;
    } else {
        use self::thing::Thing;
    }
}

fn do_stuff(thing: &Thing) -> u32 {
    thing.foo()
}

#[cfg(test)]
mod t {
    use super::*;

    #[test]
    fn test_foo() {
        let mut mock = Thing::default();
        mock.expect_foo().returning(|| 42);
        do_stuff(&mock);
    }
}

```

The error with rust 1.36:

```sh
error[E0658]: The attribute `automock` is currently unknown to the compiler and may have meaning added to it in the future
 --> src/main.rs:6:7
  |
6 |     #[automock]
  |       ^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/29642

error: cannot find macro `cfg_if!` in this scope
  --> src/main.rs:14:1
   |
14 | cfg_if! {
   | ^^^^^^

warning: unused import: `mockall::*`
 --> src/main.rs:1:5
  |
1 | use mockall::*;
  |     ^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `mockall_example`.

To learn more, run the command again with --verbose.
```

The error with rust 1.39:

```sh
error: cannot find macro `cfg_if` in this scope
  --> src/main.rs:14:1
   |
14 | cfg_if! {
   | ^^^^^^

error: cannot find attribute `automock` in this scope
 --> src/main.rs:6:7
  |
6 |     #[automock]
  |       ^^^^^^^^

warning: unused import: `mockall::*`
 --> src/main.rs:1:5
  |
1 | use mockall::*;
  |     ^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error: aborting due to 2 previous errors

error: could not compile `mockall_example`.

To learn more, run the command again with --verbose.
```

and not necessarily related: I'm doing an evaluation of mocking libraries specific for structs and you're my last hope haha. I tested others with conditional compilation but yours seems more promising and complete. And I'm wondering how it works when the struct is composed of more complex structs. I would love to help more in the crate.

**Comment by mrcosta** [comment]
Thanks for answering! About your points:

* Can I update the example with this information then? Probably it is obvious for people with more experience in the language, but I missed such a basic thing.
* I didn't get that `cfg_if` would be a different dependency. Do you mind if I add an additional comment phrasing it? And related to that, do you think that [test_double](https://github.com/pcsm/test_double) could be an option to `cfg_if`?
* It worked, thanks.

Yes, I saw your article (good work again) and I will check Simulacrum again as well but I'm not convinced is going to work to some cases that I have here. I got to your work through https://tech.labs.oliverwyman.com/blog/2018/05/21/on-mocking-rust/ and I'm not convinced any library can still mock such complex structures as this one mentioned in the article. I will try more and see how far I go.

Another example: with conditional compilation been used, I had stumbled in a case where the struct was used several times in a module and calling different methods and it would be too much boilerplate to write behaviour for all the methods that were been calling different places. It would be nice if we could in somehow use conditional compilation just for a specific method per example. Sorry if my example is hard to picture just writing. If I can manage I can try to write with examples and showing specifically the problems that I have with the different crates trying to mock some different scenarios and see if they make sense and if would be possible to us to try to work on it.

**Comment by asomers** [comment]
> Thanks for answering! About your points:
> 
>     * Can I update the example with this information then? Probably it is obvious for people with more experience in the language, but I missed such a basic thing.

In fact I deliberately hid that line as an uninteresting detail.  Your experience suggests that maybe I shouldn't have.  I'll unhide it, and any others like it.

> 
>     * I didn't get that `cfg_if` would be a different dependency. Do you mind if I add an additional comment phrasing it? And related to that, do you think that [test_double](https://github.com/pcsm/test_double) could be an option to `cfg_if`?

If you add any info about `cfg-if`, it should go in the Usage section of the README.  I've been thinking about `test_double`, too.  It can't be dropped right in because it assumes a different naming convention than Mockall.  But it's super-short, so Mockall could reimplement it and export it in the `mockall::` namespace.  I'd have to see how widely applicable it would be.

> 
>     * It worked, thanks.
> 
> 
> Yes, I saw your article (good work again) and I will check Simulacrum again as well but I'm not convinced is going to work to some cases that I have here. I got to your work through https://tech.labs.oliverwyman.com/blog/2018/05/21/on-mocking-rust/ and I'm not convinced any library can still mock such complex structures as this one mentioned in the article. I will try more and see how far I go.
> 
> Another example: with conditional compilation been used, I had stumbled in a case where the struct was used several times in a module and calling different methods and it would be too much boilerplate to write behaviour for all the methods that were been calling different places. It would be nice if we could in somehow use conditional compilation just for a specific method per example. Sorry if my example is hard to picture just writing. If I can manage I can try to write with examples and showing specifically the problems that I have with the different crates trying to mock some different scenarios and see if they make sense and if would be possible to us to try to work on it.

Are you asking if `cfg-if` can be used to substitute a single method rather than the entire structure?  No, that's not possible.  But I may not be understanding you correctly.  An example would help.

**Comment by mrcosta** [comment]
(I didn't want to flood the repo with maybe more weird questions)

Hi, again @asomers. I worked with different examples here and pretty much all of them worked. Could you help me in one scenario specifically? There is some internals of the language that I probably don't understand yet so I may say something stupid.

Long history short, what I'm trying to do is to mock a struct from an external crate. Obviously doesn't work because the `impl` block of the struct doesn't belong to me. What I was trying to do was creating a Tuple struct the wraps the external struct in it. This is an example, but I believe the fundamental problem is to check "what are the declared methods for the external structure".

```rust
use rspotify::spotify::senum::AlbumType;
use rspotify::spotify::model::album::SimplifiedAlbum;
use rspotify::spotify::model::user::PublicUser;
use cfg_if::cfg_if;

mod spotify {
    use rspotify::spotify::client::Spotify;
    use mockall::automock;
    use rspotify::spotify::model::user::PublicUser;

    pub struct SpotifyTypeWrapper(pub Spotify);

    #[automock]
    impl SpotifyTypeWrapper {
    }
}

pub struct SpotifyWrapper {
    pub client: SpotifyTypeWrapper,
}

impl SpotifyWrapper {
    pub fn test(&self) -> PublicUser {
        self
            .client.0.user("1").unwrap
    }
}

cfg_if! {
    if #[cfg(test)] {
        use self::spotify::MockSpotifyTypeWrapper as SpotifyTypeWrapper;
    } else {
        use self::spotify::SpotifyTypeWrapper;
    }
}

#[cfg(test)]
mod test {
    use super::*;
    use rspotify::spotify::senum::Type;

    #[test]
    fn test_foo() {
        let mut mock = SpotifyTypeWrapper::default();
        mock.expect_user().returning(|| PublicUser {
            display_name: None,
            external_urls: Default::default(),
            followers: None,
            href: "".to_string(),
            id: "2".to_string(),
            images: None,
            _type: Type::Artist,
            uri: "".to_string()
        });
        let spotify = SpotifyWrapper {
            client: mock
        };

        assert_eq!("2".to_string(), spotify.test().id);
    }
}
```

In sum my question is: is there ia way to extend `automock` to external crates structures? What is the limitation here? Is it hard/impossible to check what are the methods for an external structure?

**Comment by asomers** [comment]
No, it's not possible to use `automock` on external crates' structures.  The proc macro doesn't have any information about the environment in which it's called.  For cases like that you'll have to use `mock!`, which entails repeating the definitions of the external struct's public methods.  Using proc macros alone, there is no way to do what you are asking.  Perhaps a standalone program could extract such information from the .rlib files and spit out the `mock!` syntax, but I wouldn't know how to do it.
