### ISSUE TITLE
Allow mocking generic methods with non-'static return values

### ISSUE THREAD

**Issue by asomers** [asomers/mockall#76]
PR #48 added the ability to mock generic methods whose arguments had lifetime parameters.  But it didn't handle the case of return values with lifetime parameters.  So the following still doesn't work:
```rust
struct X<'a>(&'a u32);

mock!{
    Foo {
        fn foo<'a>() -> X<'a>;
    }
}
```

**Comment by DGolubets** [comment]
Hi @asomers ! Have you started working on this feature? If not, I may look into it.

I need it to mock methods returning BoxFuture with lifetime. I didn't dig deep so far, sill looking at your code and trying stuff. But my last experiment replacing lifetimes in return types with static seems to work.

Do you already have ideas on what is the right approach handling this case?

**Comment by asomers** [comment]
Yeah, I'm already working on it.  I've got it about 50% working.  Could you share the signature of one of the methods you're trying to mock?  I might stick it in the test case.

**Comment by DGolubets** [comment]
Great!
I have a simple method like this:
```

#[cfg_attr(test, automock)]
pub trait Scraper {
    fn scrape(&self) -> BoxFuture<'_, Result<Vec<ScrapeResult>>, Error>;
}
```
