### ISSUE TITLE
Better support for non-Send types

### ISSUE THREAD

**Issue by Monnoroch** [asomers/mockall#80]
`mockall` has `returning_st` method to return non-Send types. However, this capability is not present for other parts of the API:

- [ ] Add `return_const_st`
- [x] Add `withf_st`

This is actually a bit of a pain for me currently as I'm mocking C functions that accept / return pointers. Currently I have to give up on `return_const` and pass pointers casted with `as usize` to `withf`, which is ugly.

**Comment by Monnoroch** [comment]
I might be able to contribute, but would like to confirm that this is indeed something maintainers would like implemented.

**Comment by asomers** [comment]
I don't understand why the lack of `return_const_st` should cause very much pain.  A little bit of pain, sure.  But can't you simply do `returning_st(move |_| my_constant)`?  OTOH, I very much understand the need for `withf_st`.  That would be an important new feature.

`return_const_st` could also be useful, and I would also accept it.  An even cooler implementation would be to use specialization to automatically select the implementation to use, based on whether the argument is `Send`.  However, that would require nightly.

**Comment by Monnoroch** [comment]
Fair enough, the lack of `return_const_st` is a little bit of pain. Still, would be nice to have.
