### ISSUE TITLE
Support for anonymous lifetimes

### ISSUE THREAD

**Issue by DGolubets** [asomers/mockall#87]
This example doesn't work:
```
struct X<'a>(&'a u32);

#[automock]
trait Foo {
    fn foo(&self) -> X<'_>;
}
```
```
`'_` is a reserved lifetime name
```

If I specify the lifetime explicitly it does.

**Comment by asomers** [comment]
Hm, while I see your point, I don't think the benefit to this feature is very great, since the workaround is trivial.  Is there any method that can't be mocked just by naming the liftetimes?  If not, then I'm not going to give this feature much priority.

**Comment by DGolubets** [comment]
>  Is there any method that can't be mocked just by naming the liftetimes?

Hopefully not :)

I agree it's not a priority. 
Just a little annoying that it makes the code more verbose than required. 
But yeah, nothing critical.

**Comment by MOZGIII** [comment]
`async_trait` workaround kind of needs this

**Comment by asomers** [comment]
How so, @MOZGIII ?

**Comment by MOZGIII** [comment]
https://github.com/asomers/mockall/issues/75#issuecomment-554762890
Here you suggest using `'static`, while it really can be just `'_` :smile: 
But that's out of date anyways.

**Comment by asomers** [comment]
If that's your only concern then I wouldn't say _need_ since you can always specify a named lifetime, just like in https://github.com/asomers/mockall/blob/master/mockall/tests/mock_generic_method_returning_nonstatic.rs .

**Comment by MOZGIII** [comment]
That would require changing the trait. You can’t always do that, so it’s not a fair solution.

**Comment by asomers** [comment]
patches welcome.
