### ISSUE TITLE
Sequence documentation missing information

### ISSUE THREAD

**Issue by krojew** [asomers/mockall#90]
Sequence documentation and examples don't mention sequences require exact call counts. Using a sequence without them results in a panic.

**Comment by asomers** [comment]
What's wrong with "Each expectation must expect to be called a fixed number of times."?
https://docs.rs/mockall/0.5.2/mockall/struct.Sequence.html

**Comment by krojew** [comment]
Take a look at the main doc page - it's missing that information.

**Comment by asomers** [comment]
Yeah, the main page is an overview.  The overview is larger for Mockall than for most crates, because so much of Mockall is generated code.  But for organization's sake, anything that didn't have to go in the overview I didn't put there.
