### ISSUE TITLE
Trait: default implementation not working?

### ISSUE THREAD

**Issue by nbigaouette** [asomers/mockall#94]
I want to mock a trait which contains both [default implementation of functions](https://doc.rust-lang.org/book/ch10-02-traits.html#default-implementations) and functions that need to be implemented. For example, `function_to_mock()` needs to be mocked but the default implementation `function_with_default_impl()` should be used:

```rust
trait MyTrait {
    fn function_to_mock(&self);

    fn function_with_default_impl(&self) {
        println!("This is MyTrait::function_with_default_impl()");
        self.function_to_mock();
    }
}
```

I would expect to be able to do the following to only mock `MyTraitfunction_to_mock()`: (with `mockall` version 0.6.0):

```rust
use mockall::predicate::*;
use mockall::*;

#[automock]
trait MyTrait {
    fn function_to_mock(&self);

    fn function_with_default_impl(&self) {
        println!("This is MyTrait::function_with_default_impl()");
        self.function_to_mock();
    }
}

struct MyStruct;

impl MyTrait for MyStruct {
    fn function_to_mock(&self) {
        println!("This is MyStruct::function_to_mock()");
    }
}

fn main() {
    println!("---------------------------------------------------");
    let m = MyStruct {};
    m.function_with_default_impl();

    println!("---------------------------------------------------");
    let mut mock = MockMyTrait::new();
    mock.expect_function_to_mock()
        .times(1)
        .returning(|| println!("This is MockMyTrait::function_to_mock()"));
    mock.function_with_default_impl();
}
```

I would expect the output to be:

```
---------------------------------------------------
This is MyTrait::function_with_default_impl()
This is MyStruct::function_to_mock()
---------------------------------------------------
This is MyTrait::function_with_default_impl()
This is MockMyTrait::function_to_mock()
```

but I get a panic instead:

```
---------------------------------------------------
This is MyTrait::function_with_default_impl()
This is MyStruct::function_to_mock()
---------------------------------------------------
thread 'main' panicked at 'MockMyTrait::function_with_default_impl: No matching expectation found', src/libcore/option.rs:1190:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Is something like that even possible with `mockall`?

Thanks!

**Comment by asomers** [comment]
Mockall does not consider a trait method's default implementation.  It requires every method to be driven by expectations.  Nor do I think it would be wise for Mockall to use the trait's default implementation instead.  What if the programmer didn't want that?  However, the workaround is easy.  You can always move the default implementation into a standalone function, set an expectation for that method and use `returning` to call the function.

**Comment by nbigaouette** [comment]
> What if the programmer didn't want that?

This is true if the user overwrites the function. I think though that a default trait impl is meant for this kind of usage. See for example the docs: https://doc.rust-lang.org/book/ch10-02-traits.html#default-implementations 

> For example, we could define the `Summary` trait to have a `summarize_author` method whose implementation is required, and then define a `summarize` method that has a default implementation that calls the `summarize_author` method.

which is exactly what I am trying to do. I am trying to isolate as much as possible the interaction of my code with environment variables (`std::env::{var,set_var}`). There is a single variable controlling the home directory of my project (`$PROJECT_HOME`), and a multitude of subdirectories (`$PROJECT_HOME/bin`, `$PROJECT_HOME/docs`, etc.). The trait I came up with has a method to get the "home" directory. This method _has_ to be implemented (like `Summary::summarize_author()`). The trait also contains other methods to get the subdirectories (`.../bin`, `.../docs`, etc.) using default implementations, similar to `Summary::summarize()`. This way, my struct `HomeDirFromEnv` only needs to implement `MyTrait::home()` and the remaining methods are provided automatically.

I thus only want to mock the (non-default) method that accesses the environment variables, and leave all others "untouched". My first impression of `mockall` was that it could support this workflow.

Having the trait have these default implementations simplified some things. For example instantiating the struct implementing the trait gives me directly the default methods. But then the struct could overwrite those which is not a good thing... Is all this an antipattern?

I'll try your suggestion and will see if I need to change my implementations with something else.

Thanks!

**Comment by asomers** [comment]
Unlike in C++ or Ruby, in Rust there's no such thing as a superclass, so there's no way for a struct to call a superclass's implementation of a method.  So Mockall can't check whether there is an expectation set for the `summarize` method and if not call the default implementation.

Another workaround that wouldn't require changing your non-test code would be to use `mock!` instead of `#[automock]`.  I haven't tried it, but I think that if you simply omit the `summarize` method, you'll get the behavior you want.  `mock!` requires you to repeat the trait's definition, but it's more flexible than `#[automock]`.

**Comment by nbigaouette** [comment]
I haven't tried the `mock!` macro after all. I ended up splitting the functionality into:
1. a trait with a single method (non-default)
2. a generic struct with a member that implements the above trait
3. plain impl for the struct with the remaining methods, forwarding to the member when required
4. a second struct plus its trait impl for environment variable accessing (this is what gets used in normal code)

There's more boilerplate than I expected, but I think it makes more sense as I don't depend on default trait implementations.

Thanks!

**Comment by asomers** [comment]
Glad you got it solved.
