### ISSUE TITLE
Support for trait's associated const

### ISSUE THREAD

**Issue by alexsednz** [asomers/mockall#97]
The following code, when compiled, throws the "missing C in an implementation" error:
```
use mockall::predicate::*;
use mockall::*;

trait A {
    type T;
    const C: &'static str;

    fn foo(t: Self::T) -> bool;
}

mock! {
    S {}

    trait A {
        type T = isize;
        const C: &'static str = "Mock";

        fn foo(t: isize) -> bool;
    }
}

fn main() {
    println!("Hello, world!");
    let foo_ctx = MockS::foo_context();
    foo_ctx.expect().times(1).return_const(true);
    MockS::foo(0);
    foo_ctx.checkpoint();
}
```

**Comment by alexsednz** [comment]
Hi Alan,

Thank you for this very useful library. I have had the above issue that seems to be caused by the lack of supporting trait consts. However, if you already know a workaround for that, I will appreciate if you can let us know.

Best regards,
Alex

**Comment by asomers** [comment]
I don't think this is something I've tried yet, so it doesn't surprise me that it doesn't work.  But I doubt it's difficult to add.  What happens if you do this:
```rust
mock! {
    S {
        const C: &'static str = "foo";
    }

    trait A {
        type T = isize;
        const C: &'static str = "Mock";

        fn foo(t: isize) -> bool;
    }
}
```

**Comment by alexsednz** [comment]
I get a different vague build error: 

> error: Unsupported in this context
>   --> src/main.rs:16:5
>    |
> 16 |     trait A {
>    |     ^^^^^

**Comment by asomers** [comment]
Yep, that means I have some work to do.  Unfortunately, I can't suggest any workaround.  However, you'll get a better error message if you build Mockall with the "nightly" feature.
