### ISSUE TITLE
Document usage as dev-depency properly

### ISSUE THREAD

**Issue by e00E** [asomers/mockall#98]
The readme recommends using mockall as a dev-depency only. However, adapting the following example will fail during a normal build.
This seems like the correct way to fix this:
```rust
#[cfg(test)]
use mockall::automock;

#[cfg_attr(test, automock)]
trait MyTrait {
    fn foo(&self, x: u32) -> u32;
}
```
and should be mentioned in the readme.

**Comment by asomers** [comment]
Yeah, I should change that.  The reason the doc tests don't do it that way is because rustdoc always builds doc tests without `#[cfg(test)]`.  But that doesn't apply to the README.
